/* C code for program sscbasClearanceSNC, generated by snc from ../sscbasClearanceSNC.stt */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 3 "../sscbasClearanceSNC.stt"

#include "vcs_var_mes.h" // define this here so C functions are seen
	
#define	STOK       	0
#define FAIL		-1
#define WFVC		55
#define B42ON		176
#define B43OFF		179
#define DA005ON		172
#define DA005OFF	178
#define SPC1BASPNK	184


/* Variable declarations */
# line 17 "../sscbasClearanceSNC.stt"
static	short SPC1BAS_VC;
# line 18 "../sscbasClearanceSNC.stt"
static	short SPC1BAS_W42_STS;
# line 19 "../sscbasClearanceSNC.stt"
static	short SPC1BAS_W43_STS;
# line 20 "../sscbasClearanceSNC.stt"
static	short SPC1BAS_FAIL_COND;
# line 21 "../sscbasClearanceSNC.stt"
static	short SPC1BAS_RST_OUTS;
# line 22 "../sscbasClearanceSNC.stt"
static	short SPC1BAS_PNK;
# line 24 "../sscbasClearanceSNC.stt"
static	string SPC1BAS_CLR_STATS;
# line 25 "../sscbasClearanceSNC.stt"
static	string SPC1BAS_INTLCK_STATS;
# line 29 "../sscbasClearanceSNC.stt"
static	short SPC1BAS_OLD_FAIL_COND;
# line 30 "../sscbasClearanceSNC.stt"
static	short SPC1BAS_FAILED_RST;


/* Function declarations */
# line 214 "../sscbasClearanceSNC.stt"
static void initVault(SS_ID seqg_env);
# line 224 "../sscbasClearanceSNC.stt"
static void resetVault(SS_ID seqg_env);
# line 229 "../sscbasClearanceSNC.stt"
static void SPC1BAS_update_failed(SS_ID seqg_env, short report);
# line 238 "../sscbasClearanceSNC.stt"
static void SPC1BAS_update_report(SS_ID seqg_env, short intlck);
# line 243 "../sscbasClearanceSNC.stt"
static void SPC1BAS_status(SS_ID seqg_env);
# line 251 "../sscbasClearanceSNC.stt"
static void SPC1BAS_clear_underway(SS_ID seqg_env);

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "init" in state set "SPC1BAS_clearance_status" ******/

/* Event function for state "init" in state set "SPC1BAS_clearance_status" */
static seqBool seqg_event_SPC1BAS_clearance_status_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 53 "../sscbasClearanceSNC.stt"
	if (seq_delay(seqg_env, 2))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "SPC1BAS_clearance_status" */
static void seqg_action_SPC1BAS_clearance_status_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 54 "../sscbasClearanceSNC.stt"
			initVault(seqg_env);
# line 55 "../sscbasClearanceSNC.stt"
			printf("\n%sSPC1 BASEMENT VAULT INITIALISATION COMPLETED%s\n", OK, DEF);
		}
		return;
	}
}

/****** Code for state "watchman_42_pressed" in state set "SPC1BAS_clearance_status" ******/

/* Event function for state "watchman_42_pressed" in state set "SPC1BAS_clearance_status" */
static seqBool seqg_event_SPC1BAS_clearance_status_0_watchman_42_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 61 "../sscbasClearanceSNC.stt"
	if (SPC1BAS_FAIL_COND != STOK)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 66 "../sscbasClearanceSNC.stt"
	if (SPC1BAS_W42_STS == WFVC)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 70 "../sscbasClearanceSNC.stt"
	if (SPC1BAS_W42_STS == B42ON)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_42_pressed" in state set "SPC1BAS_clearance_status" */
static void seqg_action_SPC1BAS_clearance_status_0_watchman_42_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 62 "../sscbasClearanceSNC.stt"
			SPC1BAS_OLD_FAIL_COND = SPC1BAS_FAIL_COND;
		}
		return;
	case 1:
		{
		}
		return;
	case 2:
		{
# line 71 "../sscbasClearanceSNC.stt"
			SPC1BAS_clear_underway(seqg_env);
# line 72 "../sscbasClearanceSNC.stt"
			SPC1BAS_update_report(seqg_env, B42ON);
		}
		return;
	}
}

/****** Code for state "clearance_pending" in state set "SPC1BAS_clearance_status" ******/

/* Entry function for state "clearance_pending" in state set "SPC1BAS_clearance_status" */
static void seqg_entry_SPC1BAS_clearance_status_0_clearance_pending(SS_ID seqg_env)
{
# line 81 "../sscbasClearanceSNC.stt"
	resetVault(seqg_env);
# line 82 "../sscbasClearanceSNC.stt"
	SPC1BAS_update_report(seqg_env, WFVC);
}

/* Event function for state "clearance_pending" in state set "SPC1BAS_clearance_status" */
static seqBool seqg_event_SPC1BAS_clearance_status_0_clearance_pending(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 85 "../sscbasClearanceSNC.stt"
	if (SPC1BAS_W42_STS != WFVC)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "clearance_pending" in state set "SPC1BAS_clearance_status" */
static void seqg_action_SPC1BAS_clearance_status_0_clearance_pending(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "watchman_42_released" in state set "SPC1BAS_clearance_status" ******/

/* Event function for state "watchman_42_released" in state set "SPC1BAS_clearance_status" */
static seqBool seqg_event_SPC1BAS_clearance_status_0_watchman_42_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 93 "../sscbasClearanceSNC.stt"
	if (SPC1BAS_FAIL_COND != STOK)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 97 "../sscbasClearanceSNC.stt"
	if (SPC1BAS_W42_STS != B42ON)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_42_released" in state set "SPC1BAS_clearance_status" */
static void seqg_action_SPC1BAS_clearance_status_0_watchman_42_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "door_a005_closed" in state set "SPC1BAS_clearance_status" ******/

/* Entry function for state "door_a005_closed" in state set "SPC1BAS_clearance_status" */
static void seqg_entry_SPC1BAS_clearance_status_0_door_a005_closed(SS_ID seqg_env)
{
# line 107 "../sscbasClearanceSNC.stt"
	SPC1BAS_update_report(seqg_env, DA005OFF);
}

/* Event function for state "door_a005_closed" in state set "SPC1BAS_clearance_status" */
static seqBool seqg_event_SPC1BAS_clearance_status_0_door_a005_closed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 110 "../sscbasClearanceSNC.stt"
	if (SPC1BAS_FAIL_COND != STOK)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 114 "../sscbasClearanceSNC.stt"
	if (SPC1BAS_W43_STS != DA005OFF)
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "door_a005_closed" in state set "SPC1BAS_clearance_status" */
static void seqg_action_SPC1BAS_clearance_status_0_door_a005_closed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "watchman_43_pressed" in state set "SPC1BAS_clearance_status" ******/

/* Entry function for state "watchman_43_pressed" in state set "SPC1BAS_clearance_status" */
static void seqg_entry_SPC1BAS_clearance_status_0_watchman_43_pressed(SS_ID seqg_env)
{
# line 125 "../sscbasClearanceSNC.stt"
	SPC1BAS_update_report(seqg_env, B43OFF);
}

/* Event function for state "watchman_43_pressed" in state set "SPC1BAS_clearance_status" */
static seqBool seqg_event_SPC1BAS_clearance_status_0_watchman_43_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 128 "../sscbasClearanceSNC.stt"
	if (SPC1BAS_FAIL_COND != STOK)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 133 "../sscbasClearanceSNC.stt"
	if (SPC1BAS_W43_STS == STOK)
	{
		*seqg_pnst = 6;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 139 "../sscbasClearanceSNC.stt"
	if (SPC1BAS_W43_STS != B43OFF)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_43_pressed" in state set "SPC1BAS_clearance_status" */
static void seqg_action_SPC1BAS_clearance_status_0_watchman_43_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 135 "../sscbasClearanceSNC.stt"
			SPC1BAS_status(seqg_env);
		}
		return;
	case 2:
		{
		}
		return;
	}
}

/****** Code for state "vault_cleared" in state set "SPC1BAS_clearance_status" ******/

/* Entry function for state "vault_cleared" in state set "SPC1BAS_clearance_status" */
static void seqg_entry_SPC1BAS_clearance_status_0_vault_cleared(SS_ID seqg_env)
{
# line 148 "../sscbasClearanceSNC.stt"
	printf("%sSPC1 BASEMENT VAULT IN CLEARED STATE%s\n", CLR, DEF);
}

/* Event function for state "vault_cleared" in state set "SPC1BAS_clearance_status" */
static seqBool seqg_event_SPC1BAS_clearance_status_0_vault_cleared(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 150 "../sscbasClearanceSNC.stt"
	if (SPC1BAS_VC != STOK)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "vault_cleared" in state set "SPC1BAS_clearance_status" */
static void seqg_action_SPC1BAS_clearance_status_0_vault_cleared(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "paniq_faillure" in state set "SPC1BAS_clearance_status" ******/

/* Event function for state "paniq_faillure" in state set "SPC1BAS_clearance_status" */
static seqBool seqg_event_SPC1BAS_clearance_status_0_paniq_faillure(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 158 "../sscbasClearanceSNC.stt"
	if (SPC1BAS_VC != SPC1BASPNK)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 0;
		return TRUE;
	}
	if (TRUE)
	{
		*seqg_pnst = 8;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "paniq_faillure" in state set "SPC1BAS_clearance_status" */
static void seqg_action_SPC1BAS_clearance_status_0_paniq_faillure(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 163 "../sscbasClearanceSNC.stt"
			printf("SPC1 BASEMENT VAULT CLEARED FAILURE CONDITION: ");
# line 164 "../sscbasClearanceSNC.stt"
			SPC1BAS_update_failed(seqg_env, SPC1BASPNK);
		}
		return;
	}
}

/****** Code for state "recover_from_paniq" in state set "SPC1BAS_clearance_status" ******/

/* Exit function for state "recover_from_paniq" in state set "SPC1BAS_clearance_status" */
static void seqg_exit_SPC1BAS_clearance_status_0_recover_from_paniq(SS_ID seqg_env)
{
# line 177 "../sscbasClearanceSNC.stt"
	SPC1BAS_FAILED_RST = FALSE;
}

/* Event function for state "recover_from_paniq" in state set "SPC1BAS_clearance_status" */
static seqBool seqg_event_SPC1BAS_clearance_status_0_recover_from_paniq(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 173 "../sscbasClearanceSNC.stt"
	if (!SPC1BAS_PNK)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "recover_from_paniq" in state set "SPC1BAS_clearance_status" */
static void seqg_action_SPC1BAS_clearance_status_0_recover_from_paniq(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "clearance_faillures" in state set "SPC1BAS_clearance_status" ******/

/* Entry function for state "clearance_faillures" in state set "SPC1BAS_clearance_status" */
static void seqg_entry_SPC1BAS_clearance_status_0_clearance_faillures(SS_ID seqg_env)
{
# line 186 "../sscbasClearanceSNC.stt"
	printf("SPC1 BASEMENT CLEARANCE FAILURE CONDITION: ");
# line 187 "../sscbasClearanceSNC.stt"
	SPC1BAS_OLD_FAIL_COND = SPC1BAS_FAIL_COND;
# line 188 "../sscbasClearanceSNC.stt"
	SPC1BAS_FAILED_RST = FALSE;
}

/* Event function for state "clearance_faillures" in state set "SPC1BAS_clearance_status" */
static seqBool seqg_event_SPC1BAS_clearance_status_0_clearance_faillures(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "clearance_faillures" in state set "SPC1BAS_clearance_status" */
static void seqg_action_SPC1BAS_clearance_status_0_clearance_faillures(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 193 "../sscbasClearanceSNC.stt"
			SPC1BAS_update_failed(seqg_env, SPC1BAS_FAIL_COND == FAIL ? STOK : SPC1BAS_FAIL_COND);
		}
		return;
	}
}

/****** Code for state "recover_from_faillure" in state set "SPC1BAS_clearance_status" ******/

/* Event function for state "recover_from_faillure" in state set "SPC1BAS_clearance_status" */
static seqBool seqg_event_SPC1BAS_clearance_status_0_recover_from_faillure(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 199 "../sscbasClearanceSNC.stt"
	if (!SPC1BAS_FAIL_COND)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 206 "../sscbasClearanceSNC.stt"
	if (SPC1BAS_FAIL_COND != SPC1BAS_OLD_FAIL_COND)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "recover_from_faillure" in state set "SPC1BAS_clearance_status" */
static void seqg_action_SPC1BAS_clearance_status_0_recover_from_faillure(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 201 "../sscbasClearanceSNC.stt"
			printf("%sSPC1 BASEMENT RECOVERING FROM FAILLURE : ENTERING W42 STATE%s\n", OK, DEF);
		}
		return;
	case 1:
		{
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{SYS}:RST-SPC1BAS.PROC", (size_t)&SPC1BAS_RST_OUTS, "SPC1BAS_RST_OUTS", P_SHORT, 1, 1, 0, 0, 0, 0},
	{"{SYS}:SPC1BAS-CLR-STATS", (size_t)&SPC1BAS_CLR_STATS, "SPC1BAS_CLR_STATS", P_STRING, 1, 2, 0, 0, 0, 0},
	{"{SYS}:SPC1BAS-INTLCK-STATS", (size_t)&SPC1BAS_INTLCK_STATS, "SPC1BAS_INTLCK_STATS", P_STRING, 1, 3, 0, 0, 0, 0},
	{"{SYS}:SPC1BAS-VC", (size_t)&SPC1BAS_VC, "SPC1BAS_VC", P_SHORT, 1, 4, 0, 1, 0, 0},
	{"{SYS}:SPC1-W42-STS", (size_t)&SPC1BAS_W42_STS, "SPC1BAS_W42_STS", P_SHORT, 1, 5, 0, 1, 0, 0},
	{"{SYS}:SPC1-W43-STS", (size_t)&SPC1BAS_W43_STS, "SPC1BAS_W43_STS", P_SHORT, 1, 6, 0, 1, 0, 0},
	{"{SYS}:SPC1BAS-FAIL-COND", (size_t)&SPC1BAS_FAIL_COND, "SPC1BAS_FAIL_COND", P_SHORT, 1, 7, 0, 1, 0, 0},
	{"{SYS}:SPC1BAS-PNK", (size_t)&SPC1BAS_PNK, "SPC1BAS_PNK", P_SHORT, 1, 8, 0, 1, 0, 0},
};

/* Event masks for state set "SPC1BAS_clearance_status" */
static const seqMask seqg_mask_SPC1BAS_clearance_status_0_init[] = {
	0x00000000,
};
static const seqMask seqg_mask_SPC1BAS_clearance_status_0_watchman_42_pressed[] = {
	0x000000a0,
};
static const seqMask seqg_mask_SPC1BAS_clearance_status_0_clearance_pending[] = {
	0x00000020,
};
static const seqMask seqg_mask_SPC1BAS_clearance_status_0_watchman_42_released[] = {
	0x000000a0,
};
static const seqMask seqg_mask_SPC1BAS_clearance_status_0_door_a005_closed[] = {
	0x000000c0,
};
static const seqMask seqg_mask_SPC1BAS_clearance_status_0_watchman_43_pressed[] = {
	0x000000c0,
};
static const seqMask seqg_mask_SPC1BAS_clearance_status_0_vault_cleared[] = {
	0x00000010,
};
static const seqMask seqg_mask_SPC1BAS_clearance_status_0_paniq_faillure[] = {
	0x00000010,
};
static const seqMask seqg_mask_SPC1BAS_clearance_status_0_recover_from_paniq[] = {
	0x00000100,
};
static const seqMask seqg_mask_SPC1BAS_clearance_status_0_clearance_faillures[] = {
	0x00000000,
};
static const seqMask seqg_mask_SPC1BAS_clearance_status_0_recover_from_faillure[] = {
	0x00000080,
};

/* State table for state set "SPC1BAS_clearance_status" */
static seqState seqg_states_SPC1BAS_clearance_status[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_SPC1BAS_clearance_status_0_init,
	/* event function */    seqg_event_SPC1BAS_clearance_status_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPC1BAS_clearance_status_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_42_pressed",
	/* action function */   seqg_action_SPC1BAS_clearance_status_0_watchman_42_pressed,
	/* event function */    seqg_event_SPC1BAS_clearance_status_0_watchman_42_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPC1BAS_clearance_status_0_watchman_42_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "clearance_pending",
	/* action function */   seqg_action_SPC1BAS_clearance_status_0_clearance_pending,
	/* event function */    seqg_event_SPC1BAS_clearance_status_0_clearance_pending,
	/* entry function */    seqg_entry_SPC1BAS_clearance_status_0_clearance_pending,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPC1BAS_clearance_status_0_clearance_pending,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "watchman_42_released",
	/* action function */   seqg_action_SPC1BAS_clearance_status_0_watchman_42_released,
	/* event function */    seqg_event_SPC1BAS_clearance_status_0_watchman_42_released,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPC1BAS_clearance_status_0_watchman_42_released,
	/* state options */     (0)
	},
	{
	/* state name */        "door_a005_closed",
	/* action function */   seqg_action_SPC1BAS_clearance_status_0_door_a005_closed,
	/* event function */    seqg_event_SPC1BAS_clearance_status_0_door_a005_closed,
	/* entry function */    seqg_entry_SPC1BAS_clearance_status_0_door_a005_closed,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPC1BAS_clearance_status_0_door_a005_closed,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "watchman_43_pressed",
	/* action function */   seqg_action_SPC1BAS_clearance_status_0_watchman_43_pressed,
	/* event function */    seqg_event_SPC1BAS_clearance_status_0_watchman_43_pressed,
	/* entry function */    seqg_entry_SPC1BAS_clearance_status_0_watchman_43_pressed,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPC1BAS_clearance_status_0_watchman_43_pressed,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "vault_cleared",
	/* action function */   seqg_action_SPC1BAS_clearance_status_0_vault_cleared,
	/* event function */    seqg_event_SPC1BAS_clearance_status_0_vault_cleared,
	/* entry function */    seqg_entry_SPC1BAS_clearance_status_0_vault_cleared,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPC1BAS_clearance_status_0_vault_cleared,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "paniq_faillure",
	/* action function */   seqg_action_SPC1BAS_clearance_status_0_paniq_faillure,
	/* event function */    seqg_event_SPC1BAS_clearance_status_0_paniq_faillure,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPC1BAS_clearance_status_0_paniq_faillure,
	/* state options */     (0)
	},
	{
	/* state name */        "recover_from_paniq",
	/* action function */   seqg_action_SPC1BAS_clearance_status_0_recover_from_paniq,
	/* event function */    seqg_event_SPC1BAS_clearance_status_0_recover_from_paniq,
	/* entry function */    0,
	/* exit function */     seqg_exit_SPC1BAS_clearance_status_0_recover_from_paniq,
	/* event mask array */  seqg_mask_SPC1BAS_clearance_status_0_recover_from_paniq,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
	{
	/* state name */        "clearance_faillures",
	/* action function */   seqg_action_SPC1BAS_clearance_status_0_clearance_faillures,
	/* event function */    seqg_event_SPC1BAS_clearance_status_0_clearance_faillures,
	/* entry function */    seqg_entry_SPC1BAS_clearance_status_0_clearance_faillures,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPC1BAS_clearance_status_0_clearance_faillures,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
	{
	/* state name */        "recover_from_faillure",
	/* action function */   seqg_action_SPC1BAS_clearance_status_0_recover_from_faillure,
	/* event function */    seqg_event_SPC1BAS_clearance_status_0_recover_from_faillure,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPC1BAS_clearance_status_0_recover_from_faillure,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "SPC1BAS_clearance_status",
	/* states */            seqg_states_SPC1BAS_clearance_status,
	/* number of states */  11
	},
};

/* Program table (global) */
seqProgram sscbasClearanceSNC = {
	/* magic number */      2002001,
	/* program name */      "sscbasClearanceSNC",
	/* channels */          seqg_chans,
	/* num. channels */     8,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 214 "../sscbasClearanceSNC.stt"
static void initVault(SS_ID seqg_env)
{
# line 215 "../sscbasClearanceSNC.stt"
	SPC1BAS_OLD_FAIL_COND = SPC1BAS_FAIL_COND;
# line 216 "../sscbasClearanceSNC.stt"
	SPC1BAS_RST_OUTS = TRUE;
# line 217 "../sscbasClearanceSNC.stt"
	not_cleared(SPC1BAS_CLR_STATS);
# line 218 "../sscbasClearanceSNC.stt"
	report_error(SPC1BAS_INTLCK_STATS, 0);
# line 219 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*SPC1BAS_RST_OUTS*/, SYNC, DEFAULT_TIMEOUT);
# line 220 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SPC1BAS_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 221 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*SPC1BAS_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 224 "../sscbasClearanceSNC.stt"
static void resetVault(SS_ID seqg_env)
{
# line 225 "../sscbasClearanceSNC.stt"
	not_cleared(SPC1BAS_CLR_STATS);
# line 226 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SPC1BAS_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 229 "../sscbasClearanceSNC.stt"
static void SPC1BAS_update_failed(SS_ID seqg_env, short report)
{
# line 231 "../sscbasClearanceSNC.stt"
	clear_failed(SPC1BAS_CLR_STATS);
# line 232 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SPC1BAS_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 233 "../sscbasClearanceSNC.stt"
	report_error(SPC1BAS_INTLCK_STATS, report);
# line 234 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*SPC1BAS_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 235 "../sscbasClearanceSNC.stt"
	printf("%s%s%s\n", ERROR, SPC1BAS_INTLCK_STATS, DEF);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 238 "../sscbasClearanceSNC.stt"
static void SPC1BAS_update_report(SS_ID seqg_env, short intlck)
{
# line 239 "../sscbasClearanceSNC.stt"
	report_error(SPC1BAS_INTLCK_STATS, intlck);
# line 240 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*SPC1BAS_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 243 "../sscbasClearanceSNC.stt"
static void SPC1BAS_status(SS_ID seqg_env)
{
# line 245 "../sscbasClearanceSNC.stt"
	cleared(SPC1BAS_CLR_STATS);
# line 246 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SPC1BAS_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 247 "../sscbasClearanceSNC.stt"
	report_error(SPC1BAS_INTLCK_STATS, 0);
# line 248 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*SPC1BAS_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 251 "../sscbasClearanceSNC.stt"
static void SPC1BAS_clear_underway(SS_ID seqg_env)
{
# line 253 "../sscbasClearanceSNC.stt"
	clear_underway(SPC1BAS_CLR_STATS);
# line 254 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SPC1BAS_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var
# line 258 "../sscbasClearanceSNC.stt"


inline void cleared(string vault_status) {   
    strcpy(vault_status, mes_array[1]); // Area cleared  
}
////////////////////////////////////////////////
inline void not_cleared(string vault_status) {  
   strcpy(vault_status, mes_array[2]); // Area not cleared    
}
///////////////////////////////////////////////
inline void clear_underway(string vault_status) { 
   strcpy(vault_status, mes_array[3]);  // Area clearance underway    
}
//////////////////////////////////////////////
inline void clear_failed(string vault_status) { 
   strcpy(vault_status, mes_array[5]); // Area clearance fail   
}
////////////////////////////////////////////////
inline void report_error(string vault_interlock, short intlock)
{
   strcpy(vault_interlock, mes_array[intlock]);
}
	


/* Register sequencer commands and program */
#include "epicsExport.h"
static void sscbasClearanceSNCRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&sscbasClearanceSNC);
}
epicsExportRegistrar(sscbasClearanceSNCRegistrar);
