/* C code for program ssclClearanceSNC, generated by snc from ../ssclClearanceSNC.stt */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 3 "../ssclClearanceSNC.stt"

/*******************************************************************/
#include "vcs_var_mes.h" // define this here so C functions are seen
/*******************************************************************/
	
#define STOK   	0
#define FAIL		-1
#define WFVC		193
#define G2OFF  53
#define B1ON   46
#define B2OFF  41
#define B2ON   42
#define B3OFF  43  
#define B3ON   44 
#define B4OFF  45 
#define B5OFF  47 
#define B4_5ON 50
#define B4ON   51 
#define B5ON   52 
#define B6OFF  57
#define SSCLPNK	58


/* Variable declarations */
# line 27 "../ssclClearanceSNC.stt"
static	short SSCL_VC;
# line 28 "../ssclClearanceSNC.stt"
static	short SSC_W1_STS;
# line 29 "../ssclClearanceSNC.stt"
static	short SSC_W2_STS;
# line 30 "../ssclClearanceSNC.stt"
static	short SSC_W3_STS;
# line 31 "../ssclClearanceSNC.stt"
static	short SSC_W4_STS;
# line 32 "../ssclClearanceSNC.stt"
static	short SSC_W5_STS;
# line 33 "../ssclClearanceSNC.stt"
static	short SSC_W6_STS;
# line 35 "../ssclClearanceSNC.stt"
static	short SSCL_FAIL_COND;
# line 36 "../ssclClearanceSNC.stt"
static	short SSCL_RST_OUTS;
# line 37 "../ssclClearanceSNC.stt"
static	short SSCL_PNK;
# line 39 "../ssclClearanceSNC.stt"
static	string SSCL_CLR_STATS;
# line 40 "../ssclClearanceSNC.stt"
static	string SSCL_INTLCK_STATS;
# line 44 "../ssclClearanceSNC.stt"
static	short SSCL_OLD_FAIL_COND;
# line 45 "../ssclClearanceSNC.stt"
static	short SSCL_FAILED_RST;


/* Function declarations */
# line 359 "../ssclClearanceSNC.stt"
static void initVault(SS_ID seqg_env);
# line 369 "../ssclClearanceSNC.stt"
static void resetVault(SS_ID seqg_env);
# line 374 "../ssclClearanceSNC.stt"
static void SSCL_update_failed(SS_ID seqg_env, short report);
# line 383 "../ssclClearanceSNC.stt"
static void SSCL_update_report(SS_ID seqg_env, short intlck);
# line 388 "../ssclClearanceSNC.stt"
static void SSCL_status(SS_ID seqg_env);
# line 397 "../ssclClearanceSNC.stt"
static void SSCL_clear_underway(SS_ID seqg_env);

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "init" in state set "SSCL_clearance_status" ******/

/* Event function for state "init" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 77 "../ssclClearanceSNC.stt"
	if (seq_delay(seqg_env, 2))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 78 "../ssclClearanceSNC.stt"
			initVault(seqg_env);
# line 79 "../ssclClearanceSNC.stt"
			printf("\n%sSSC BASEMENT VAULT INITIALISATION COMPLETED%s\n", OK, DEF);
		}
		return;
	}
}

/****** Code for state "watchman_1_pressed" in state set "SSCL_clearance_status" ******/

/* Event function for state "watchman_1_pressed" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_watchman_1_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 85 "../ssclClearanceSNC.stt"
	if (SSCL_FAIL_COND != STOK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 90 "../ssclClearanceSNC.stt"
	if (SSC_W1_STS == WFVC)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 94 "../ssclClearanceSNC.stt"
	if (SSC_W1_STS == B2OFF)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_1_pressed" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_watchman_1_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 86 "../ssclClearanceSNC.stt"
			SSCL_OLD_FAIL_COND = SSCL_FAIL_COND;
		}
		return;
	case 1:
		{
		}
		return;
	case 2:
		{
# line 95 "../ssclClearanceSNC.stt"
			SSCL_update_report(seqg_env, B2OFF);
# line 96 "../ssclClearanceSNC.stt"
			SSCL_clear_underway(seqg_env);
		}
		return;
	}
}

/****** Code for state "clearance_pending" in state set "SSCL_clearance_status" ******/

/* Entry function for state "clearance_pending" in state set "SSCL_clearance_status" */
static void seqg_entry_SSCL_clearance_status_0_clearance_pending(SS_ID seqg_env)
{
}

/* Event function for state "clearance_pending" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_clearance_pending(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 113 "../ssclClearanceSNC.stt"
	if (SSC_W1_STS != WFVC)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "clearance_pending" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_clearance_pending(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "watchman_2_pressed" in state set "SSCL_clearance_status" ******/

/* Event function for state "watchman_2_pressed" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_watchman_2_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 122 "../ssclClearanceSNC.stt"
	if (SSCL_FAIL_COND != STOK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 126 "../ssclClearanceSNC.stt"
	if (SSC_W2_STS == B2ON)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_2_pressed" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_watchman_2_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 127 "../ssclClearanceSNC.stt"
			SSCL_update_report(seqg_env, B2ON);
		}
		return;
	}
}

/****** Code for state "watchman_2_released" in state set "SSCL_clearance_status" ******/

/* Event function for state "watchman_2_released" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_watchman_2_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 133 "../ssclClearanceSNC.stt"
	if (SSCL_FAIL_COND != STOK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 137 "../ssclClearanceSNC.stt"
	if (SSC_W2_STS != B2ON)
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_2_released" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_watchman_2_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 138 "../ssclClearanceSNC.stt"
			SSCL_update_report(seqg_env, B3OFF);
		}
		return;
	}
}

/****** Code for state "watchman_3_pressed" in state set "SSCL_clearance_status" ******/

/* Event function for state "watchman_3_pressed" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_watchman_3_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 144 "../ssclClearanceSNC.stt"
	if (SSCL_FAIL_COND != STOK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 148 "../ssclClearanceSNC.stt"
	if (SSC_W3_STS == B3ON)
	{
		*seqg_pnst = 6;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_3_pressed" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_watchman_3_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 149 "../ssclClearanceSNC.stt"
			SSCL_update_report(seqg_env, B3ON);
		}
		return;
	}
}

/****** Code for state "watchman_3_released" in state set "SSCL_clearance_status" ******/

/* Event function for state "watchman_3_released" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_watchman_3_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 156 "../ssclClearanceSNC.stt"
	if (SSCL_FAIL_COND != STOK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 160 "../ssclClearanceSNC.stt"
	if (SSC_W3_STS != B3ON)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_3_released" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_watchman_3_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 161 "../ssclClearanceSNC.stt"
			SSCL_update_report(seqg_env, B4OFF);
		}
		return;
	}
}

/****** Code for state "watchman_4_pressed" in state set "SSCL_clearance_status" ******/

/* Event function for state "watchman_4_pressed" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_watchman_4_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 167 "../ssclClearanceSNC.stt"
	if (SSCL_FAIL_COND != STOK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 171 "../ssclClearanceSNC.stt"
	if (!SSC_W4_STS)
	{
		*seqg_pnst = 8;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_4_pressed" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_watchman_4_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 172 "../ssclClearanceSNC.stt"
			SSCL_update_report(seqg_env, B1ON);
		}
		return;
	}
}

/****** Code for state "watchman_1_released" in state set "SSCL_clearance_status" ******/

/* Event function for state "watchman_1_released" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_watchman_1_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 178 "../ssclClearanceSNC.stt"
	if (SSCL_FAIL_COND != STOK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 182 "../ssclClearanceSNC.stt"
	if (SSC_W1_STS == B1ON)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_1_released" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_watchman_1_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 184 "../ssclClearanceSNC.stt"
			SSCL_update_report(seqg_env, B5OFF);
		}
		return;
	}
}

/****** Code for state "watchman_5_pressed" in state set "SSCL_clearance_status" ******/

/* Event function for state "watchman_5_pressed" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_watchman_5_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 190 "../ssclClearanceSNC.stt"
	if (SSCL_FAIL_COND != STOK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 195 "../ssclClearanceSNC.stt"
	if (!SSC_W5_STS)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_5_pressed" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_watchman_5_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 197 "../ssclClearanceSNC.stt"
			SSCL_update_report(seqg_env, B4_5ON);
		}
		return;
	}
}

/****** Code for state "watchman_4_5_pressed" in state set "SSCL_clearance_status" ******/

/* Event function for state "watchman_4_5_pressed" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_watchman_4_5_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 204 "../ssclClearanceSNC.stt"
	if (SSCL_FAIL_COND != STOK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 208 "../ssclClearanceSNC.stt"
	if (SSC_W4_STS == B5ON)
	{
		*seqg_pnst = 12;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 213 "../ssclClearanceSNC.stt"
	if (SSC_W5_STS == B4ON)
	{
		*seqg_pnst = 11;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_4_5_pressed" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_watchman_4_5_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	case 2:
		{
		}
		return;
	}
}

/****** Code for state "watchman_4_released" in state set "SSCL_clearance_status" ******/

/* Entry function for state "watchman_4_released" in state set "SSCL_clearance_status" */
static void seqg_entry_SSCL_clearance_status_0_watchman_4_released(SS_ID seqg_env)
{
# line 223 "../ssclClearanceSNC.stt"
	SSCL_update_report(seqg_env, B4ON);
}

/* Event function for state "watchman_4_released" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_watchman_4_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 226 "../ssclClearanceSNC.stt"
	if (SSCL_FAIL_COND != STOK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 230 "../ssclClearanceSNC.stt"
	if (SSC_W4_STS == G2OFF)
	{
		*seqg_pnst = 13;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_4_released" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_watchman_4_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "watchman_5_released" in state set "SSCL_clearance_status" ******/

/* Entry function for state "watchman_5_released" in state set "SSCL_clearance_status" */
static void seqg_entry_SSCL_clearance_status_0_watchman_5_released(SS_ID seqg_env)
{
# line 240 "../ssclClearanceSNC.stt"
	SSCL_update_report(seqg_env, B5ON);
}

/* Event function for state "watchman_5_released" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_watchman_5_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 243 "../ssclClearanceSNC.stt"
	if (SSCL_FAIL_COND != STOK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 247 "../ssclClearanceSNC.stt"
	if (SSC_W5_STS == B4ON)
	{
		*seqg_pnst = 13;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_5_released" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_watchman_5_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "gate_g2_closed" in state set "SSCL_clearance_status" ******/

/* Entry function for state "gate_g2_closed" in state set "SSCL_clearance_status" */
static void seqg_entry_SSCL_clearance_status_0_gate_g2_closed(SS_ID seqg_env)
{
# line 257 "../ssclClearanceSNC.stt"
	SSCL_update_report(seqg_env, G2OFF);
}

/* Event function for state "gate_g2_closed" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_gate_g2_closed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 260 "../ssclClearanceSNC.stt"
	if (SSCL_FAIL_COND != STOK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 264 "../ssclClearanceSNC.stt"
	if (SSC_W6_STS != G2OFF)
	{
		*seqg_pnst = 14;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "gate_g2_closed" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_gate_g2_closed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "watchman_6_pressed" in state set "SSCL_clearance_status" ******/

/* Entry function for state "watchman_6_pressed" in state set "SSCL_clearance_status" */
static void seqg_entry_SSCL_clearance_status_0_watchman_6_pressed(SS_ID seqg_env)
{
# line 274 "../ssclClearanceSNC.stt"
	SSCL_update_report(seqg_env, B6OFF);
}

/* Event function for state "watchman_6_pressed" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_watchman_6_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 276 "../ssclClearanceSNC.stt"
	if (SSCL_FAIL_COND != STOK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 280 "../ssclClearanceSNC.stt"
	if (!SSC_W6_STS)
	{
		*seqg_pnst = 15;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 285 "../ssclClearanceSNC.stt"
	if (SSC_W6_STS != B6OFF)
	{
		*seqg_pnst = 13;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_6_pressed" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_watchman_6_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 282 "../ssclClearanceSNC.stt"
			SSCL_status(seqg_env);
		}
		return;
	case 2:
		{
		}
		return;
	}
}

/****** Code for state "vault_cleared" in state set "SSCL_clearance_status" ******/

/* Entry function for state "vault_cleared" in state set "SSCL_clearance_status" */
static void seqg_entry_SSCL_clearance_status_0_vault_cleared(SS_ID seqg_env)
{
# line 293 "../ssclClearanceSNC.stt"
	printf("%sSSC BASEMENT VAULT IN CLEARED STATE%s\n", CLR, DEF);
}

/* Event function for state "vault_cleared" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_vault_cleared(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 295 "../ssclClearanceSNC.stt"
	if (SSCL_VC != STOK)
	{
		*seqg_pnst = 16;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "vault_cleared" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_vault_cleared(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "paniq_faillure" in state set "SSCL_clearance_status" ******/

/* Event function for state "paniq_faillure" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_paniq_faillure(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 303 "../ssclClearanceSNC.stt"
	if (SSCL_VC != SSCLPNK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
	if (TRUE)
	{
		*seqg_pnst = 17;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "paniq_faillure" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_paniq_faillure(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 308 "../ssclClearanceSNC.stt"
			printf("SSC BASEMENT VAULT CLEARED FAILURE CONDITION: ");
# line 309 "../ssclClearanceSNC.stt"
			SSCL_update_failed(seqg_env, SSCLPNK);
		}
		return;
	}
}

/****** Code for state "recover_from_paniq" in state set "SSCL_clearance_status" ******/

/* Exit function for state "recover_from_paniq" in state set "SSCL_clearance_status" */
static void seqg_exit_SSCL_clearance_status_0_recover_from_paniq(SS_ID seqg_env)
{
# line 322 "../ssclClearanceSNC.stt"
	SSCL_FAILED_RST = FALSE;
}

/* Event function for state "recover_from_paniq" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_recover_from_paniq(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 318 "../ssclClearanceSNC.stt"
	if (!SSCL_PNK)
	{
		*seqg_pnst = 19;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "recover_from_paniq" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_recover_from_paniq(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "clearance_faillures" in state set "SSCL_clearance_status" ******/

/* Entry function for state "clearance_faillures" in state set "SSCL_clearance_status" */
static void seqg_entry_SSCL_clearance_status_0_clearance_faillures(SS_ID seqg_env)
{
# line 331 "../ssclClearanceSNC.stt"
	printf("SSC BASEMENT CLEARANCE FAILURE CONDITION: ");
# line 332 "../ssclClearanceSNC.stt"
	SSCL_OLD_FAIL_COND = SSCL_FAIL_COND;
# line 333 "../ssclClearanceSNC.stt"
	SSCL_FAILED_RST = FALSE;
}

/* Event function for state "clearance_faillures" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_clearance_faillures(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 19;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "clearance_faillures" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_clearance_faillures(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 338 "../ssclClearanceSNC.stt"
			SSCL_update_failed(seqg_env, SSCL_FAIL_COND == FAIL ? STOK : SSCL_FAIL_COND);
		}
		return;
	}
}

/****** Code for state "recover_from_faillure" in state set "SSCL_clearance_status" ******/

/* Event function for state "recover_from_faillure" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_recover_from_faillure(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 344 "../ssclClearanceSNC.stt"
	if (!SSCL_FAIL_COND)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 351 "../ssclClearanceSNC.stt"
	if (SSCL_FAIL_COND != SSCL_OLD_FAIL_COND)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "recover_from_faillure" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_recover_from_faillure(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 346 "../ssclClearanceSNC.stt"
			printf("%sSSC BASEMENT RECOVERING FROM FAILLURE : ENTERING W1 STATE%s\n", OK, DEF);
		}
		return;
	case 1:
		{
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{SYS}:RST-SSCL.PROC", (size_t)&SSCL_RST_OUTS, "SSCL_RST_OUTS", P_SHORT, 1, 1, 0, 0, 0, 0},
	{"{SYS}:SSCL-CLR-STATS", (size_t)&SSCL_CLR_STATS, "SSCL_CLR_STATS", P_STRING, 1, 2, 0, 0, 0, 0},
	{"{SYS}:SSCL-INTLCK-STATS", (size_t)&SSCL_INTLCK_STATS, "SSCL_INTLCK_STATS", P_STRING, 1, 3, 0, 0, 0, 0},
	{"{SYS}:SSCL-VC", (size_t)&SSCL_VC, "SSCL_VC", P_SHORT, 1, 4, 0, 1, 0, 0},
	{"{SYS}:SSC-W1-STS", (size_t)&SSC_W1_STS, "SSC_W1_STS", P_SHORT, 1, 5, 0, 1, 0, 0},
	{"{SYS}:SSC-W2-STS", (size_t)&SSC_W2_STS, "SSC_W2_STS", P_SHORT, 1, 6, 0, 1, 0, 0},
	{"{SYS}:SSC-W3-STS", (size_t)&SSC_W3_STS, "SSC_W3_STS", P_SHORT, 1, 7, 0, 1, 0, 0},
	{"{SYS}:SSC-W4-STS", (size_t)&SSC_W4_STS, "SSC_W4_STS", P_SHORT, 1, 8, 0, 1, 0, 0},
	{"{SYS}:SSC-W5-STS", (size_t)&SSC_W5_STS, "SSC_W5_STS", P_SHORT, 1, 9, 0, 1, 0, 0},
	{"{SYS}:SSC-W6-STS", (size_t)&SSC_W6_STS, "SSC_W6_STS", P_SHORT, 1, 10, 0, 1, 0, 0},
	{"{SYS}:SSCL-FAIL-COND", (size_t)&SSCL_FAIL_COND, "SSCL_FAIL_COND", P_SHORT, 1, 11, 0, 1, 0, 0},
	{"{SYS}:SSCL-PNK", (size_t)&SSCL_PNK, "SSCL_PNK", P_SHORT, 1, 12, 0, 1, 0, 0},
};

/* Event masks for state set "SSCL_clearance_status" */
static const seqMask seqg_mask_SSCL_clearance_status_0_init[] = {
	0x00000000,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_watchman_1_pressed[] = {
	0x00000820,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_clearance_pending[] = {
	0x00000020,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_watchman_2_pressed[] = {
	0x00000840,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_watchman_2_released[] = {
	0x00000840,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_watchman_3_pressed[] = {
	0x00000880,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_watchman_3_released[] = {
	0x00000880,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_watchman_4_pressed[] = {
	0x00000900,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_watchman_1_released[] = {
	0x00000820,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_watchman_5_pressed[] = {
	0x00000a00,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_watchman_4_5_pressed[] = {
	0x00000b00,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_watchman_4_released[] = {
	0x00000900,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_watchman_5_released[] = {
	0x00000a00,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_gate_g2_closed[] = {
	0x00000c00,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_watchman_6_pressed[] = {
	0x00000c00,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_vault_cleared[] = {
	0x00000010,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_paniq_faillure[] = {
	0x00000010,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_recover_from_paniq[] = {
	0x00001000,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_clearance_faillures[] = {
	0x00000000,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_recover_from_faillure[] = {
	0x00000800,
};

/* State table for state set "SSCL_clearance_status" */
static seqState seqg_states_SSCL_clearance_status[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_SSCL_clearance_status_0_init,
	/* event function */    seqg_event_SSCL_clearance_status_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_1_pressed",
	/* action function */   seqg_action_SSCL_clearance_status_0_watchman_1_pressed,
	/* event function */    seqg_event_SSCL_clearance_status_0_watchman_1_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_watchman_1_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "clearance_pending",
	/* action function */   seqg_action_SSCL_clearance_status_0_clearance_pending,
	/* event function */    seqg_event_SSCL_clearance_status_0_clearance_pending,
	/* entry function */    seqg_entry_SSCL_clearance_status_0_clearance_pending,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_clearance_pending,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "watchman_2_pressed",
	/* action function */   seqg_action_SSCL_clearance_status_0_watchman_2_pressed,
	/* event function */    seqg_event_SSCL_clearance_status_0_watchman_2_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_watchman_2_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_2_released",
	/* action function */   seqg_action_SSCL_clearance_status_0_watchman_2_released,
	/* event function */    seqg_event_SSCL_clearance_status_0_watchman_2_released,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_watchman_2_released,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_3_pressed",
	/* action function */   seqg_action_SSCL_clearance_status_0_watchman_3_pressed,
	/* event function */    seqg_event_SSCL_clearance_status_0_watchman_3_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_watchman_3_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_3_released",
	/* action function */   seqg_action_SSCL_clearance_status_0_watchman_3_released,
	/* event function */    seqg_event_SSCL_clearance_status_0_watchman_3_released,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_watchman_3_released,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_4_pressed",
	/* action function */   seqg_action_SSCL_clearance_status_0_watchman_4_pressed,
	/* event function */    seqg_event_SSCL_clearance_status_0_watchman_4_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_watchman_4_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_1_released",
	/* action function */   seqg_action_SSCL_clearance_status_0_watchman_1_released,
	/* event function */    seqg_event_SSCL_clearance_status_0_watchman_1_released,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_watchman_1_released,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_5_pressed",
	/* action function */   seqg_action_SSCL_clearance_status_0_watchman_5_pressed,
	/* event function */    seqg_event_SSCL_clearance_status_0_watchman_5_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_watchman_5_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_4_5_pressed",
	/* action function */   seqg_action_SSCL_clearance_status_0_watchman_4_5_pressed,
	/* event function */    seqg_event_SSCL_clearance_status_0_watchman_4_5_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_watchman_4_5_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_4_released",
	/* action function */   seqg_action_SSCL_clearance_status_0_watchman_4_released,
	/* event function */    seqg_event_SSCL_clearance_status_0_watchman_4_released,
	/* entry function */    seqg_entry_SSCL_clearance_status_0_watchman_4_released,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_watchman_4_released,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "watchman_5_released",
	/* action function */   seqg_action_SSCL_clearance_status_0_watchman_5_released,
	/* event function */    seqg_event_SSCL_clearance_status_0_watchman_5_released,
	/* entry function */    seqg_entry_SSCL_clearance_status_0_watchman_5_released,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_watchman_5_released,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "gate_g2_closed",
	/* action function */   seqg_action_SSCL_clearance_status_0_gate_g2_closed,
	/* event function */    seqg_event_SSCL_clearance_status_0_gate_g2_closed,
	/* entry function */    seqg_entry_SSCL_clearance_status_0_gate_g2_closed,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_gate_g2_closed,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "watchman_6_pressed",
	/* action function */   seqg_action_SSCL_clearance_status_0_watchman_6_pressed,
	/* event function */    seqg_event_SSCL_clearance_status_0_watchman_6_pressed,
	/* entry function */    seqg_entry_SSCL_clearance_status_0_watchman_6_pressed,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_watchman_6_pressed,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "vault_cleared",
	/* action function */   seqg_action_SSCL_clearance_status_0_vault_cleared,
	/* event function */    seqg_event_SSCL_clearance_status_0_vault_cleared,
	/* entry function */    seqg_entry_SSCL_clearance_status_0_vault_cleared,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_vault_cleared,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "paniq_faillure",
	/* action function */   seqg_action_SSCL_clearance_status_0_paniq_faillure,
	/* event function */    seqg_event_SSCL_clearance_status_0_paniq_faillure,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_paniq_faillure,
	/* state options */     (0)
	},
	{
	/* state name */        "recover_from_paniq",
	/* action function */   seqg_action_SSCL_clearance_status_0_recover_from_paniq,
	/* event function */    seqg_event_SSCL_clearance_status_0_recover_from_paniq,
	/* entry function */    0,
	/* exit function */     seqg_exit_SSCL_clearance_status_0_recover_from_paniq,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_recover_from_paniq,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
	{
	/* state name */        "clearance_faillures",
	/* action function */   seqg_action_SSCL_clearance_status_0_clearance_faillures,
	/* event function */    seqg_event_SSCL_clearance_status_0_clearance_faillures,
	/* entry function */    seqg_entry_SSCL_clearance_status_0_clearance_faillures,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_clearance_faillures,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
	{
	/* state name */        "recover_from_faillure",
	/* action function */   seqg_action_SSCL_clearance_status_0_recover_from_faillure,
	/* event function */    seqg_event_SSCL_clearance_status_0_recover_from_faillure,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_recover_from_faillure,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "SSCL_clearance_status",
	/* states */            seqg_states_SSCL_clearance_status,
	/* number of states */  20
	},
};

/* Program table (global) */
seqProgram ssclClearanceSNC = {
	/* magic number */      2002001,
	/* program name */      "ssclClearanceSNC",
	/* channels */          seqg_chans,
	/* num. channels */     12,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 359 "../ssclClearanceSNC.stt"
static void initVault(SS_ID seqg_env)
{
# line 360 "../ssclClearanceSNC.stt"
	SSCL_OLD_FAIL_COND = SSCL_FAIL_COND;
# line 361 "../ssclClearanceSNC.stt"
	SSCL_RST_OUTS = TRUE;
# line 362 "../ssclClearanceSNC.stt"
	not_cleared(SSCL_CLR_STATS);
# line 363 "../ssclClearanceSNC.stt"
	report_error(SSCL_INTLCK_STATS, 0);
# line 364 "../ssclClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*SSCL_RST_OUTS*/, SYNC, DEFAULT_TIMEOUT);
# line 365 "../ssclClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SSCL_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 366 "../ssclClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*SSCL_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 369 "../ssclClearanceSNC.stt"
static void resetVault(SS_ID seqg_env)
{
# line 370 "../ssclClearanceSNC.stt"
	not_cleared(SSCL_CLR_STATS);
# line 371 "../ssclClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SSCL_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 374 "../ssclClearanceSNC.stt"
static void SSCL_update_failed(SS_ID seqg_env, short report)
{
# line 376 "../ssclClearanceSNC.stt"
	clear_failed(SSCL_CLR_STATS);
# line 377 "../ssclClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SSCL_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 378 "../ssclClearanceSNC.stt"
	report_error(SSCL_INTLCK_STATS, report);
# line 379 "../ssclClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*SSCL_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 380 "../ssclClearanceSNC.stt"
	printf("%s%s%s\n", ERROR, SSCL_INTLCK_STATS, DEF);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 383 "../ssclClearanceSNC.stt"
static void SSCL_update_report(SS_ID seqg_env, short intlck)
{
# line 384 "../ssclClearanceSNC.stt"
	report_error(SSCL_INTLCK_STATS, intlck);
# line 385 "../ssclClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*SSCL_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 388 "../ssclClearanceSNC.stt"
static void SSCL_status(SS_ID seqg_env)
{
# line 390 "../ssclClearanceSNC.stt"
	cleared(SSCL_CLR_STATS);
# line 392 "../ssclClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SSCL_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 393 "../ssclClearanceSNC.stt"
	report_error(SSCL_INTLCK_STATS, 0);
# line 394 "../ssclClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*SSCL_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 397 "../ssclClearanceSNC.stt"
static void SSCL_clear_underway(SS_ID seqg_env)
{
# line 399 "../ssclClearanceSNC.stt"
	clear_underway(SSCL_CLR_STATS);
# line 400 "../ssclClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SSCL_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

/* Register sequencer commands and program */
#include "epicsExport.h"
static void ssclClearanceSNCRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&ssclClearanceSNC);
}
epicsExportRegistrar(ssclClearanceSNCRegistrar);
