/* C code for program speClearanceSNC, generated by snc from ../speClearanceSNC.stt */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 3 "../speClearanceSNC.stt"

/*******************************************************************/
#include "vcs_var_mes.h" // define this here so C functions are seen
/*******************************************************************/
#define	VCOK       	0
#define FAIL		-1
#define	B25OFF      120
#define	B24ON      	119
#define DA9S1OFF	122 
#define DA9S2OFF	121


/* Variable declarations */
# line 15 "../speClearanceSNC.stt"
static	short SPE_INIT;
# line 16 "../speClearanceSNC.stt"
static	short SPE_VC;
# line 17 "../speClearanceSNC.stt"
static	short SPE_W24_STS;
# line 18 "../speClearanceSNC.stt"
static	short SPE_W25_STS;
# line 19 "../speClearanceSNC.stt"
static	short SPE_FAIL_COND;
# line 20 "../speClearanceSNC.stt"
static	string SPE_CLR_STATS;
# line 21 "../speClearanceSNC.stt"
static	string SPE_INTLCK_STATS;
# line 23 "../speClearanceSNC.stt"
static	short SPEUpdate;
# line 24 "../speClearanceSNC.stt"
static	short SPE_OLD_FAIL_COND;


/* Function declarations */
# line 166 "../speClearanceSNC.stt"
static void initVault(SS_ID seqg_env);
# line 176 "../speClearanceSNC.stt"
static void resetStatus(SS_ID seqg_env);
# line 184 "../speClearanceSNC.stt"
static void SPE_update_failed(SS_ID seqg_env, short report);
# line 193 "../speClearanceSNC.stt"
static void SPE_update_report(SS_ID seqg_env, short intlck);
# line 198 "../speClearanceSNC.stt"
static void SPE_status(SS_ID seqg_env);
# line 206 "../speClearanceSNC.stt"
static void SPE_clear_underway(SS_ID seqg_env);

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "init" in state set "SPE_clearance_status" ******/

/* Event function for state "init" in state set "SPE_clearance_status" */
static seqBool seqg_event_SPE_clearance_status_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 43 "../speClearanceSNC.stt"
	if (seq_delay(seqg_env, 6.5))
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "SPE_clearance_status" */
static void seqg_action_SPE_clearance_status_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 44 "../speClearanceSNC.stt"
			initVault(seqg_env);
# line 45 "../speClearanceSNC.stt"
			printf("\n%sSPECTROMETER VAULT INITIALISATION COMPLETED%s\n", OK, DEF);
		}
		return;
	}
}

/****** Code for state "vault_cleared" in state set "SPE_clearance_status" ******/

/* Entry function for state "vault_cleared" in state set "SPE_clearance_status" */
static void seqg_entry_SPE_clearance_status_0_vault_cleared(SS_ID seqg_env)
{
# line 53 "../speClearanceSNC.stt"
	printf("%sSPECTROMETER VAULT IN CLEARED STATE%s\n", CLR, DEF);
}

/* Event function for state "vault_cleared" in state set "SPE_clearance_status" */
static seqBool seqg_event_SPE_clearance_status_0_vault_cleared(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 55 "../speClearanceSNC.stt"
	if (SPE_VC != VCOK)
	{
		*seqg_pnst = 8;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "vault_cleared" in state set "SPE_clearance_status" */
static void seqg_action_SPE_clearance_status_0_vault_cleared(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "recover_faillure" in state set "SPE_clearance_status" ******/

/* Event function for state "recover_faillure" in state set "SPE_clearance_status" */
static seqBool seqg_event_SPE_clearance_status_0_recover_faillure(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 62 "../speClearanceSNC.stt"
	if (!SPE_FAIL_COND)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 69 "../speClearanceSNC.stt"
	if (SPE_FAIL_COND != SPE_OLD_FAIL_COND)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "recover_faillure" in state set "SPE_clearance_status" */
static void seqg_action_SPE_clearance_status_0_recover_faillure(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 63 "../speClearanceSNC.stt"
			if (!SPEUpdate)
			{
# line 64 "../speClearanceSNC.stt"
				printf("%sRECOVERING FROM FAILLURE - ENTERING W24 STATE%s\n", OK, DEF);
# line 65 "../speClearanceSNC.stt"
				SPEUpdate = TRUE;
			}
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "watchman_24_pressed" in state set "SPE_clearance_status" ******/

/* Event function for state "watchman_24_pressed" in state set "SPE_clearance_status" */
static seqBool seqg_event_SPE_clearance_status_0_watchman_24_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 75 "../speClearanceSNC.stt"
	if (SPE_FAIL_COND != VCOK)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 79 "../speClearanceSNC.stt"
	if (SPE_W24_STS == B24ON)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_24_pressed" in state set "SPE_clearance_status" */
static void seqg_action_SPE_clearance_status_0_watchman_24_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 76 "../speClearanceSNC.stt"
			SPE_OLD_FAIL_COND = SPE_FAIL_COND;
		}
		return;
	case 1:
		{
# line 80 "../speClearanceSNC.stt"
			SPE_clear_underway(seqg_env);
# line 81 "../speClearanceSNC.stt"
			SPE_update_report(seqg_env, B24ON);
		}
		return;
	}
}

/****** Code for state "watchman_24_released" in state set "SPE_clearance_status" ******/

/* Event function for state "watchman_24_released" in state set "SPE_clearance_status" */
static seqBool seqg_event_SPE_clearance_status_0_watchman_24_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 87 "../speClearanceSNC.stt"
	if (SPE_FAIL_COND != VCOK)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 91 "../speClearanceSNC.stt"
	if (SPE_W24_STS != B24ON)
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_24_released" in state set "SPE_clearance_status" */
static void seqg_action_SPE_clearance_status_0_watchman_24_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "door_a9_closed" in state set "SPE_clearance_status" ******/

/* Event function for state "door_a9_closed" in state set "SPE_clearance_status" */
static seqBool seqg_event_SPE_clearance_status_0_door_a9_closed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 97 "../speClearanceSNC.stt"
	if (SPE_FAIL_COND != VCOK)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 101 "../speClearanceSNC.stt"
	if (SPE_W25_STS == DA9S1OFF)
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 105 "../speClearanceSNC.stt"
	if (SPE_W25_STS == DA9S2OFF)
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 2;
		return TRUE;
	}
	if (TRUE)
	{
		*seqg_pnst = 6;
		*seqg_ptrn = 3;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "door_a9_closed" in state set "SPE_clearance_status" */
static void seqg_action_SPE_clearance_status_0_door_a9_closed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 102 "../speClearanceSNC.stt"
			SPE_update_report(seqg_env, DA9S1OFF);
		}
		return;
	case 2:
		{
# line 106 "../speClearanceSNC.stt"
			SPE_update_report(seqg_env, DA9S2OFF);
		}
		return;
	case 3:
		{
# line 111 "../speClearanceSNC.stt"
			SPE_update_report(seqg_env, B25OFF);
		}
		return;
	}
}

/****** Code for state "watchman_25_pressed" in state set "SPE_clearance_status" ******/

/* Event function for state "watchman_25_pressed" in state set "SPE_clearance_status" */
static seqBool seqg_event_SPE_clearance_status_0_watchman_25_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 118 "../speClearanceSNC.stt"
	if (SPE_FAIL_COND != VCOK)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 123 "../speClearanceSNC.stt"
	if (!SPE_W25_STS)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_25_pressed" in state set "SPE_clearance_status" */
static void seqg_action_SPE_clearance_status_0_watchman_25_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 125 "../speClearanceSNC.stt"
			SPE_status(seqg_env);
		}
		return;
	}
}

/****** Code for state "clearance_faillures" in state set "SPE_clearance_status" ******/

/* Entry function for state "clearance_faillures" in state set "SPE_clearance_status" */
static void seqg_entry_SPE_clearance_status_0_clearance_faillures(SS_ID seqg_env)
{
# line 134 "../speClearanceSNC.stt"
	printf("SPE CLEARANCE FAILURE CONDITION: ");
# line 135 "../speClearanceSNC.stt"
	SPEUpdate = FALSE;
}

/* Exit function for state "clearance_faillures" in state set "SPE_clearance_status" */
static void seqg_exit_SPE_clearance_status_0_clearance_faillures(SS_ID seqg_env)
{
# line 143 "../speClearanceSNC.stt"
	SPE_OLD_FAIL_COND = SPE_FAIL_COND;
}

/* Event function for state "clearance_faillures" in state set "SPE_clearance_status" */
static seqBool seqg_event_SPE_clearance_status_0_clearance_faillures(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "clearance_faillures" in state set "SPE_clearance_status" */
static void seqg_action_SPE_clearance_status_0_clearance_faillures(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 139 "../speClearanceSNC.stt"
			SPE_update_failed(seqg_env, SPE_FAIL_COND);
		}
		return;
	}
}

/****** Code for state "vc_faillures" in state set "SPE_clearance_status" ******/

/* Entry function for state "vc_faillures" in state set "SPE_clearance_status" */
static void seqg_entry_SPE_clearance_status_0_vc_faillures(SS_ID seqg_env)
{
# line 152 "../speClearanceSNC.stt"
	printf("SPE CLEAR FAILURE CONDITION: ");
# line 153 "../speClearanceSNC.stt"
	SPEUpdate = FALSE;
}

/* Exit function for state "vc_faillures" in state set "SPE_clearance_status" */
static void seqg_exit_SPE_clearance_status_0_vc_faillures(SS_ID seqg_env)
{
# line 161 "../speClearanceSNC.stt"
	SPE_OLD_FAIL_COND = SPE_FAIL_COND;
}

/* Event function for state "vc_faillures" in state set "SPE_clearance_status" */
static seqBool seqg_event_SPE_clearance_status_0_vc_faillures(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "vc_faillures" in state set "SPE_clearance_status" */
static void seqg_action_SPE_clearance_status_0_vc_faillures(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 157 "../speClearanceSNC.stt"
			SPE_update_failed(seqg_env, SPE_VC);
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{SYS}:SPE-CLR-STATS", (size_t)&SPE_CLR_STATS, "SPE_CLR_STATS", P_STRING, 1, 1, 0, 0, 0, 0},
	{"{SYS}:SPE-INTLCK-STATS", (size_t)&SPE_INTLCK_STATS, "SPE_INTLCK_STATS", P_STRING, 1, 2, 0, 0, 0, 0},
	{"{SYS}:SPE-VC", (size_t)&SPE_VC, "SPE_VC", P_SHORT, 1, 3, 0, 1, 0, 0},
	{"{SYS}:SPE-INIT", (size_t)&SPE_INIT, "SPE_INIT", P_SHORT, 1, 4, 0, 0, 0, 0},
	{"{SYS}:SPE-W24-STS", (size_t)&SPE_W24_STS, "SPE_W24_STS", P_SHORT, 1, 5, 0, 1, 0, 0},
	{"{SYS}:SPE-W25-STS", (size_t)&SPE_W25_STS, "SPE_W25_STS", P_SHORT, 1, 6, 0, 1, 0, 0},
	{"{SYS}:SPE-FAIL-COND", (size_t)&SPE_FAIL_COND, "SPE_FAIL_COND", P_SHORT, 1, 7, 0, 1, 0, 0},
};

/* Event masks for state set "SPE_clearance_status" */
static const seqMask seqg_mask_SPE_clearance_status_0_init[] = {
	0x00000000,
};
static const seqMask seqg_mask_SPE_clearance_status_0_vault_cleared[] = {
	0x00000008,
};
static const seqMask seqg_mask_SPE_clearance_status_0_recover_faillure[] = {
	0x00000080,
};
static const seqMask seqg_mask_SPE_clearance_status_0_watchman_24_pressed[] = {
	0x000000a0,
};
static const seqMask seqg_mask_SPE_clearance_status_0_watchman_24_released[] = {
	0x000000a0,
};
static const seqMask seqg_mask_SPE_clearance_status_0_door_a9_closed[] = {
	0x000000c0,
};
static const seqMask seqg_mask_SPE_clearance_status_0_watchman_25_pressed[] = {
	0x000000c0,
};
static const seqMask seqg_mask_SPE_clearance_status_0_clearance_faillures[] = {
	0x00000000,
};
static const seqMask seqg_mask_SPE_clearance_status_0_vc_faillures[] = {
	0x00000000,
};

/* State table for state set "SPE_clearance_status" */
static seqState seqg_states_SPE_clearance_status[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_SPE_clearance_status_0_init,
	/* event function */    seqg_event_SPE_clearance_status_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPE_clearance_status_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "vault_cleared",
	/* action function */   seqg_action_SPE_clearance_status_0_vault_cleared,
	/* event function */    seqg_event_SPE_clearance_status_0_vault_cleared,
	/* entry function */    seqg_entry_SPE_clearance_status_0_vault_cleared,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPE_clearance_status_0_vault_cleared,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "recover_faillure",
	/* action function */   seqg_action_SPE_clearance_status_0_recover_faillure,
	/* event function */    seqg_event_SPE_clearance_status_0_recover_faillure,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPE_clearance_status_0_recover_faillure,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_24_pressed",
	/* action function */   seqg_action_SPE_clearance_status_0_watchman_24_pressed,
	/* event function */    seqg_event_SPE_clearance_status_0_watchman_24_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPE_clearance_status_0_watchman_24_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_24_released",
	/* action function */   seqg_action_SPE_clearance_status_0_watchman_24_released,
	/* event function */    seqg_event_SPE_clearance_status_0_watchman_24_released,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPE_clearance_status_0_watchman_24_released,
	/* state options */     (0)
	},
	{
	/* state name */        "door_a9_closed",
	/* action function */   seqg_action_SPE_clearance_status_0_door_a9_closed,
	/* event function */    seqg_event_SPE_clearance_status_0_door_a9_closed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPE_clearance_status_0_door_a9_closed,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_25_pressed",
	/* action function */   seqg_action_SPE_clearance_status_0_watchman_25_pressed,
	/* event function */    seqg_event_SPE_clearance_status_0_watchman_25_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPE_clearance_status_0_watchman_25_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "clearance_faillures",
	/* action function */   seqg_action_SPE_clearance_status_0_clearance_faillures,
	/* event function */    seqg_event_SPE_clearance_status_0_clearance_faillures,
	/* entry function */    seqg_entry_SPE_clearance_status_0_clearance_faillures,
	/* exit function */     seqg_exit_SPE_clearance_status_0_clearance_faillures,
	/* event mask array */  seqg_mask_SPE_clearance_status_0_clearance_faillures,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
	{
	/* state name */        "vc_faillures",
	/* action function */   seqg_action_SPE_clearance_status_0_vc_faillures,
	/* event function */    seqg_event_SPE_clearance_status_0_vc_faillures,
	/* entry function */    seqg_entry_SPE_clearance_status_0_vc_faillures,
	/* exit function */     seqg_exit_SPE_clearance_status_0_vc_faillures,
	/* event mask array */  seqg_mask_SPE_clearance_status_0_vc_faillures,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "SPE_clearance_status",
	/* states */            seqg_states_SPE_clearance_status,
	/* number of states */  9
	},
};

/* Program table (global) */
seqProgram speClearanceSNC = {
	/* magic number */      2002001,
	/* program name */      "speClearanceSNC",
	/* channels */          seqg_chans,
	/* num. channels */     7,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 166 "../speClearanceSNC.stt"
static void initVault(SS_ID seqg_env)
{
# line 167 "../speClearanceSNC.stt"
	SPE_INIT = TRUE;
# line 168 "../speClearanceSNC.stt"
	SPE_OLD_FAIL_COND = SPE_FAIL_COND;
# line 169 "../speClearanceSNC.stt"
	not_cleared(SPE_CLR_STATS);
# line 170 "../speClearanceSNC.stt"
	report_error(SPE_INTLCK_STATS, 0);
# line 171 "../speClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 3/*SPE_INIT*/, SYNC, DEFAULT_TIMEOUT);
# line 172 "../speClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*SPE_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 173 "../speClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SPE_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 176 "../speClearanceSNC.stt"
static void resetStatus(SS_ID seqg_env)
{
# line 178 "../speClearanceSNC.stt"
	not_cleared(SPE_CLR_STATS);
# line 179 "../speClearanceSNC.stt"
	report_error(SPE_INTLCK_STATS, 0);
# line 180 "../speClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*SPE_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 181 "../speClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SPE_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 184 "../speClearanceSNC.stt"
static void SPE_update_failed(SS_ID seqg_env, short report)
{
# line 186 "../speClearanceSNC.stt"
	clear_failed(SPE_CLR_STATS);
# line 187 "../speClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*SPE_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 188 "../speClearanceSNC.stt"
	report_error(SPE_INTLCK_STATS, report);
# line 189 "../speClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SPE_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 190 "../speClearanceSNC.stt"
	printf("%s%s%s\n", ERROR, SPE_INTLCK_STATS, DEF);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 193 "../speClearanceSNC.stt"
static void SPE_update_report(SS_ID seqg_env, short intlck)
{
# line 194 "../speClearanceSNC.stt"
	report_error(SPE_INTLCK_STATS, intlck);
# line 195 "../speClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SPE_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 198 "../speClearanceSNC.stt"
static void SPE_status(SS_ID seqg_env)
{
# line 200 "../speClearanceSNC.stt"
	cleared(SPE_CLR_STATS);
# line 201 "../speClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*SPE_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 202 "../speClearanceSNC.stt"
	report_error(SPE_INTLCK_STATS, 0);
# line 203 "../speClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SPE_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 206 "../speClearanceSNC.stt"
static void SPE_clear_underway(SS_ID seqg_env)
{
# line 208 "../speClearanceSNC.stt"
	clear_underway(SPE_CLR_STATS);
# line 209 "../speClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*SPE_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

/* Register sequencer commands and program */
#include "epicsExport.h"
static void speClearanceSNCRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&speClearanceSNC);
}
epicsExportRegistrar(speClearanceSNCRegistrar);
