/* C code for program sscgfa1ClearanceSNC, generated by snc from ../sscgfa1ClearanceSNC.stt */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 3 "../sscgfa1ClearanceSNC.stt"

/*******************************************************************/
#include "vcs_var_mes.h" // define this here so C functions are seen
/*******************************************************************/
#define	VCOK       	0
#define FAIL		-1
#define SSCPNK      20
#define B11ON 		147	  
#define B12OFF		48   	  
#define G3OFF		47	



/* Variable declarations */
# line 16 "../sscgfa1ClearanceSNC.stt"
static	short SSCA1_INIT;
# line 17 "../sscgfa1ClearanceSNC.stt"
static	short SSCA1_VC;
# line 18 "../sscgfa1ClearanceSNC.stt"
static	short SSC_W11_STS;
# line 19 "../sscgfa1ClearanceSNC.stt"
static	short SSC_W12_STS;
# line 20 "../sscgfa1ClearanceSNC.stt"
static	short SSCA1_FAIL_COND;
# line 21 "../sscgfa1ClearanceSNC.stt"
static	string SSCA1_CLR_STATS;
# line 22 "../sscgfa1ClearanceSNC.stt"
static	string SSCA1_INTLCK_STATS;
# line 24 "../sscgfa1ClearanceSNC.stt"
static	short SSCA1Update;
# line 25 "../sscgfa1ClearanceSNC.stt"
static	short SSCA1_OLD_FAIL_COND;


/* Function declarations */
# line 165 "../sscgfa1ClearanceSNC.stt"
static void initVault(SS_ID seqg_env);
# line 175 "../sscgfa1ClearanceSNC.stt"
static void SSCA1_update_failed(SS_ID seqg_env, short report);
# line 184 "../sscgfa1ClearanceSNC.stt"
static void SSCA1_update_report(SS_ID seqg_env, short intlck);
# line 189 "../sscgfa1ClearanceSNC.stt"
static void SSCA1_status(SS_ID seqg_env);
# line 197 "../sscgfa1ClearanceSNC.stt"
static void SSCA1_clear_underway(SS_ID seqg_env);

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "init" in state set "SSCA1_clearance_status" ******/

/* Event function for state "init" in state set "SSCA1_clearance_status" */
static seqBool seqg_event_SSCA1_clearance_status_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 44 "../sscgfa1ClearanceSNC.stt"
	if (seq_delay(seqg_env, 2))
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "SSCA1_clearance_status" */
static void seqg_action_SSCA1_clearance_status_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 45 "../sscgfa1ClearanceSNC.stt"
			initVault(seqg_env);
# line 46 "../sscgfa1ClearanceSNC.stt"
			printf("%sSSC GROUND FLOOR AREA 1 INITIALISATION COMPLETED%s\n", OK, DEF);
		}
		return;
	}
}

/****** Code for state "vault_cleared" in state set "SSCA1_clearance_status" ******/

/* Entry function for state "vault_cleared" in state set "SSCA1_clearance_status" */
static void seqg_entry_SSCA1_clearance_status_0_vault_cleared(SS_ID seqg_env)
{
# line 54 "../sscgfa1ClearanceSNC.stt"
	printf("%sSSC GROUND FLOOR AREA 1 IN CLEARED STATE%s\n", CLR, DEF);
}

/* Event function for state "vault_cleared" in state set "SSCA1_clearance_status" */
static seqBool seqg_event_SSCA1_clearance_status_0_vault_cleared(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 56 "../sscgfa1ClearanceSNC.stt"
	if (SSCA1_VC != VCOK)
	{
		*seqg_pnst = 8;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "vault_cleared" in state set "SSCA1_clearance_status" */
static void seqg_action_SSCA1_clearance_status_0_vault_cleared(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "recover_faillure" in state set "SSCA1_clearance_status" ******/

/* Event function for state "recover_faillure" in state set "SSCA1_clearance_status" */
static seqBool seqg_event_SSCA1_clearance_status_0_recover_faillure(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 63 "../sscgfa1ClearanceSNC.stt"
	if (!SSCA1_FAIL_COND)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 70 "../sscgfa1ClearanceSNC.stt"
	if (SSCA1_FAIL_COND != SSCA1_OLD_FAIL_COND)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "recover_faillure" in state set "SSCA1_clearance_status" */
static void seqg_action_SSCA1_clearance_status_0_recover_faillure(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 64 "../sscgfa1ClearanceSNC.stt"
			if (!SSCA1Update)
			{
# line 65 "../sscgfa1ClearanceSNC.stt"
				printf("%sRECOVERING FROM FAILLURE - ENTERING W11 STATE%s\n", OK, DEF);
# line 66 "../sscgfa1ClearanceSNC.stt"
				SSCA1Update = TRUE;
			}
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "watchman_11_pressed" in state set "SSCA1_clearance_status" ******/

/* Event function for state "watchman_11_pressed" in state set "SSCA1_clearance_status" */
static seqBool seqg_event_SSCA1_clearance_status_0_watchman_11_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 77 "../sscgfa1ClearanceSNC.stt"
	if (SSCA1_FAIL_COND != VCOK)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 81 "../sscgfa1ClearanceSNC.stt"
	if (SSC_W11_STS == B11ON)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_11_pressed" in state set "SSCA1_clearance_status" */
static void seqg_action_SSCA1_clearance_status_0_watchman_11_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 78 "../sscgfa1ClearanceSNC.stt"
			SSCA1_OLD_FAIL_COND = SSCA1_FAIL_COND;
		}
		return;
	case 1:
		{
# line 82 "../sscgfa1ClearanceSNC.stt"
			SSCA1_clear_underway(seqg_env);
# line 83 "../sscgfa1ClearanceSNC.stt"
			SSCA1_update_report(seqg_env, B11ON);
		}
		return;
	}
}

/****** Code for state "watchman_11_released" in state set "SSCA1_clearance_status" ******/

/* Event function for state "watchman_11_released" in state set "SSCA1_clearance_status" */
static seqBool seqg_event_SSCA1_clearance_status_0_watchman_11_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 89 "../sscgfa1ClearanceSNC.stt"
	if (SSC_W11_STS == FAIL)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 93 "../sscgfa1ClearanceSNC.stt"
	if (SSC_W11_STS != B11ON)
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_11_released" in state set "SSCA1_clearance_status" */
static void seqg_action_SSCA1_clearance_status_0_watchman_11_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "gate_g3_closed" in state set "SSCA1_clearance_status" ******/

/* Event function for state "gate_g3_closed" in state set "SSCA1_clearance_status" */
static seqBool seqg_event_SSCA1_clearance_status_0_gate_g3_closed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 99 "../sscgfa1ClearanceSNC.stt"
	if (SSCA1_FAIL_COND != VCOK)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 103 "../sscgfa1ClearanceSNC.stt"
	if (SSC_W12_STS == G3OFF)
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 1;
		return TRUE;
	}
	if (TRUE)
	{
		*seqg_pnst = 6;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "gate_g3_closed" in state set "SSCA1_clearance_status" */
static void seqg_action_SSCA1_clearance_status_0_gate_g3_closed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 104 "../sscgfa1ClearanceSNC.stt"
			SSCA1_update_report(seqg_env, G3OFF);
		}
		return;
	case 2:
		{
# line 109 "../sscgfa1ClearanceSNC.stt"
			SSCA1_update_report(seqg_env, B12OFF);
		}
		return;
	}
}

/****** Code for state "watchman_12_pressed" in state set "SSCA1_clearance_status" ******/

/* Event function for state "watchman_12_pressed" in state set "SSCA1_clearance_status" */
static seqBool seqg_event_SSCA1_clearance_status_0_watchman_12_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 116 "../sscgfa1ClearanceSNC.stt"
	if (SSC_W12_STS == FAIL)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 121 "../sscgfa1ClearanceSNC.stt"
	if (!SSC_W12_STS)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_12_pressed" in state set "SSCA1_clearance_status" */
static void seqg_action_SSCA1_clearance_status_0_watchman_12_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 123 "../sscgfa1ClearanceSNC.stt"
			SSCA1_status(seqg_env);
		}
		return;
	}
}

/****** Code for state "clearance_faillures" in state set "SSCA1_clearance_status" ******/

/* Entry function for state "clearance_faillures" in state set "SSCA1_clearance_status" */
static void seqg_entry_SSCA1_clearance_status_0_clearance_faillures(SS_ID seqg_env)
{
# line 132 "../sscgfa1ClearanceSNC.stt"
	printf("SSC GF A1 CLEARANCE FAILURE CONDITION: ");
# line 133 "../sscgfa1ClearanceSNC.stt"
	SSCA1Update = FALSE;
}

/* Exit function for state "clearance_faillures" in state set "SSCA1_clearance_status" */
static void seqg_exit_SSCA1_clearance_status_0_clearance_faillures(SS_ID seqg_env)
{
# line 142 "../sscgfa1ClearanceSNC.stt"
	SSCA1_OLD_FAIL_COND = SSCA1_FAIL_COND;
}

/* Event function for state "clearance_faillures" in state set "SSCA1_clearance_status" */
static seqBool seqg_event_SSCA1_clearance_status_0_clearance_faillures(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "clearance_faillures" in state set "SSCA1_clearance_status" */
static void seqg_action_SSCA1_clearance_status_0_clearance_faillures(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 137 "../sscgfa1ClearanceSNC.stt"
			SSCA1_update_failed(seqg_env, SSCA1_FAIL_COND);
# line 138 "../sscgfa1ClearanceSNC.stt"
			printf("PROBLEM: %d\n", SSCA1_FAIL_COND);
		}
		return;
	}
}

/****** Code for state "vc_faillures" in state set "SSCA1_clearance_status" ******/

/* Entry function for state "vc_faillures" in state set "SSCA1_clearance_status" */
static void seqg_entry_SSCA1_clearance_status_0_vc_faillures(SS_ID seqg_env)
{
# line 151 "../sscgfa1ClearanceSNC.stt"
	printf("SSC GF A1 CLEAR FAILURE CONDITION: ");
# line 152 "../sscgfa1ClearanceSNC.stt"
	SSCA1Update = FALSE;
}

/* Exit function for state "vc_faillures" in state set "SSCA1_clearance_status" */
static void seqg_exit_SSCA1_clearance_status_0_vc_faillures(SS_ID seqg_env)
{
# line 160 "../sscgfa1ClearanceSNC.stt"
	SSCA1_OLD_FAIL_COND = SSCA1_FAIL_COND;
}

/* Event function for state "vc_faillures" in state set "SSCA1_clearance_status" */
static seqBool seqg_event_SSCA1_clearance_status_0_vc_faillures(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "vc_faillures" in state set "SSCA1_clearance_status" */
static void seqg_action_SSCA1_clearance_status_0_vc_faillures(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 156 "../sscgfa1ClearanceSNC.stt"
			SSCA1_update_failed(seqg_env, SSCA1_VC);
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{SYS}:SSCA1-CLR-STATS", (size_t)&SSCA1_CLR_STATS, "SSCA1_CLR_STATS", P_STRING, 1, 1, 0, 0, 0, 0},
	{"{SYS}:SSCA1-INTLCK-STATS", (size_t)&SSCA1_INTLCK_STATS, "SSCA1_INTLCK_STATS", P_STRING, 1, 2, 0, 0, 0, 0},
	{"{SYS}:SSCA1-VC", (size_t)&SSCA1_VC, "SSCA1_VC", P_SHORT, 1, 3, 0, 1, 0, 0},
	{"{SYS}:SSCA1-INIT", (size_t)&SSCA1_INIT, "SSCA1_INIT", P_SHORT, 1, 4, 0, 0, 0, 0},
	{"{SYS}:SSC-W11-STS", (size_t)&SSC_W11_STS, "SSC_W11_STS", P_SHORT, 1, 5, 0, 1, 0, 0},
	{"{SYS}:SSC-W12-STS", (size_t)&SSC_W12_STS, "SSC_W12_STS", P_SHORT, 1, 6, 0, 1, 0, 0},
	{"{SYS}:SSCA1-FAIL-COND", (size_t)&SSCA1_FAIL_COND, "SSCA1_FAIL_COND", P_SHORT, 1, 7, 0, 1, 0, 0},
};

/* Event masks for state set "SSCA1_clearance_status" */
static const seqMask seqg_mask_SSCA1_clearance_status_0_init[] = {
	0x00000000,
};
static const seqMask seqg_mask_SSCA1_clearance_status_0_vault_cleared[] = {
	0x00000008,
};
static const seqMask seqg_mask_SSCA1_clearance_status_0_recover_faillure[] = {
	0x00000080,
};
static const seqMask seqg_mask_SSCA1_clearance_status_0_watchman_11_pressed[] = {
	0x000000a0,
};
static const seqMask seqg_mask_SSCA1_clearance_status_0_watchman_11_released[] = {
	0x00000020,
};
static const seqMask seqg_mask_SSCA1_clearance_status_0_gate_g3_closed[] = {
	0x000000c0,
};
static const seqMask seqg_mask_SSCA1_clearance_status_0_watchman_12_pressed[] = {
	0x00000040,
};
static const seqMask seqg_mask_SSCA1_clearance_status_0_clearance_faillures[] = {
	0x00000000,
};
static const seqMask seqg_mask_SSCA1_clearance_status_0_vc_faillures[] = {
	0x00000000,
};

/* State table for state set "SSCA1_clearance_status" */
static seqState seqg_states_SSCA1_clearance_status[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_SSCA1_clearance_status_0_init,
	/* event function */    seqg_event_SSCA1_clearance_status_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCA1_clearance_status_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "vault_cleared",
	/* action function */   seqg_action_SSCA1_clearance_status_0_vault_cleared,
	/* event function */    seqg_event_SSCA1_clearance_status_0_vault_cleared,
	/* entry function */    seqg_entry_SSCA1_clearance_status_0_vault_cleared,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCA1_clearance_status_0_vault_cleared,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "recover_faillure",
	/* action function */   seqg_action_SSCA1_clearance_status_0_recover_faillure,
	/* event function */    seqg_event_SSCA1_clearance_status_0_recover_faillure,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCA1_clearance_status_0_recover_faillure,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_11_pressed",
	/* action function */   seqg_action_SSCA1_clearance_status_0_watchman_11_pressed,
	/* event function */    seqg_event_SSCA1_clearance_status_0_watchman_11_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCA1_clearance_status_0_watchman_11_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_11_released",
	/* action function */   seqg_action_SSCA1_clearance_status_0_watchman_11_released,
	/* event function */    seqg_event_SSCA1_clearance_status_0_watchman_11_released,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCA1_clearance_status_0_watchman_11_released,
	/* state options */     (0)
	},
	{
	/* state name */        "gate_g3_closed",
	/* action function */   seqg_action_SSCA1_clearance_status_0_gate_g3_closed,
	/* event function */    seqg_event_SSCA1_clearance_status_0_gate_g3_closed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCA1_clearance_status_0_gate_g3_closed,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_12_pressed",
	/* action function */   seqg_action_SSCA1_clearance_status_0_watchman_12_pressed,
	/* event function */    seqg_event_SSCA1_clearance_status_0_watchman_12_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCA1_clearance_status_0_watchman_12_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "clearance_faillures",
	/* action function */   seqg_action_SSCA1_clearance_status_0_clearance_faillures,
	/* event function */    seqg_event_SSCA1_clearance_status_0_clearance_faillures,
	/* entry function */    seqg_entry_SSCA1_clearance_status_0_clearance_faillures,
	/* exit function */     seqg_exit_SSCA1_clearance_status_0_clearance_faillures,
	/* event mask array */  seqg_mask_SSCA1_clearance_status_0_clearance_faillures,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
	{
	/* state name */        "vc_faillures",
	/* action function */   seqg_action_SSCA1_clearance_status_0_vc_faillures,
	/* event function */    seqg_event_SSCA1_clearance_status_0_vc_faillures,
	/* entry function */    seqg_entry_SSCA1_clearance_status_0_vc_faillures,
	/* exit function */     seqg_exit_SSCA1_clearance_status_0_vc_faillures,
	/* event mask array */  seqg_mask_SSCA1_clearance_status_0_vc_faillures,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "SSCA1_clearance_status",
	/* states */            seqg_states_SSCA1_clearance_status,
	/* number of states */  9
	},
};

/* Program table (global) */
seqProgram sscgfa1ClearanceSNC = {
	/* magic number */      2002001,
	/* program name */      "sscgfa1ClearanceSNC",
	/* channels */          seqg_chans,
	/* num. channels */     7,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 165 "../sscgfa1ClearanceSNC.stt"
static void initVault(SS_ID seqg_env)
{
# line 166 "../sscgfa1ClearanceSNC.stt"
	SSCA1_INIT = TRUE;
# line 167 "../sscgfa1ClearanceSNC.stt"
	SSCA1_OLD_FAIL_COND = SSCA1_FAIL_COND;
# line 168 "../sscgfa1ClearanceSNC.stt"
	not_cleared(SSCA1_CLR_STATS);
# line 169 "../sscgfa1ClearanceSNC.stt"
	report_error(SSCA1_INTLCK_STATS, 0);
# line 170 "../sscgfa1ClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 3/*SSCA1_INIT*/, SYNC, DEFAULT_TIMEOUT);
# line 171 "../sscgfa1ClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*SSCA1_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 172 "../sscgfa1ClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SSCA1_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 175 "../sscgfa1ClearanceSNC.stt"
static void SSCA1_update_failed(SS_ID seqg_env, short report)
{
# line 177 "../sscgfa1ClearanceSNC.stt"
	clear_failed(SSCA1_CLR_STATS);
# line 178 "../sscgfa1ClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*SSCA1_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 179 "../sscgfa1ClearanceSNC.stt"
	report_error(SSCA1_INTLCK_STATS, report);
# line 180 "../sscgfa1ClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SSCA1_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 181 "../sscgfa1ClearanceSNC.stt"
	printf("%s%s%s\n", ERROR, SSCA1_INTLCK_STATS, DEF);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 184 "../sscgfa1ClearanceSNC.stt"
static void SSCA1_update_report(SS_ID seqg_env, short intlck)
{
# line 185 "../sscgfa1ClearanceSNC.stt"
	report_error(SSCA1_INTLCK_STATS, intlck);
# line 186 "../sscgfa1ClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SSCA1_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 189 "../sscgfa1ClearanceSNC.stt"
static void SSCA1_status(SS_ID seqg_env)
{
# line 191 "../sscgfa1ClearanceSNC.stt"
	cleared(SSCA1_CLR_STATS);
# line 192 "../sscgfa1ClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*SSCA1_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 193 "../sscgfa1ClearanceSNC.stt"
	report_error(SSCA1_INTLCK_STATS, 0);
# line 194 "../sscgfa1ClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SSCA1_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 197 "../sscgfa1ClearanceSNC.stt"
static void SSCA1_clear_underway(SS_ID seqg_env)
{
# line 199 "../sscgfa1ClearanceSNC.stt"
	clear_underway(SSCA1_CLR_STATS);
# line 200 "../sscgfa1ClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*SSCA1_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

/* Register sequencer commands and program */
#include "epicsExport.h"
static void sscgfa1ClearanceSNCRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&sscgfa1ClearanceSNC);
}
epicsExportRegistrar(sscgfa1ClearanceSNCRegistrar);
