/* C code for program sscbasClearanceSNC, generated by snc from ../sscbasClearanceSNC.stt */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 3 "../sscbasClearanceSNC.stt"

/*******************************************************************/
#include "vcs_var_mes.h" // define this here so C functions are seen
/*******************************************************************/
	
#define STOK   	0
#define FAIL		-1
#define WFVC		55
#define FAIL		-1
#define G2OFF  33
#define B1ON   38
#define B2OFF  22
#define B2ON   36
#define B3OFF  27  
#define B3ON   37 
#define B4OFF  28  
#define B4ON   32 
#define B5ON   31
#define B4_5ON 31
#define B5OFF  29  
#define B6OFF	35
#define SSCBASPNK	20


/* Variable declarations */
# line 28 "../sscbasClearanceSNC.stt"
static	short SSCBAS_VC;
# line 29 "../sscbasClearanceSNC.stt"
static	short SSC_W1_STS;
# line 30 "../sscbasClearanceSNC.stt"
static	short SSC_W2_STS;
# line 31 "../sscbasClearanceSNC.stt"
static	short SSC_W3_STS;
# line 32 "../sscbasClearanceSNC.stt"
static	short SSC_W4_STS;
# line 33 "../sscbasClearanceSNC.stt"
static	short SSC_W5_STS;
# line 34 "../sscbasClearanceSNC.stt"
static	short SSC_W6_STS;
# line 36 "../sscbasClearanceSNC.stt"
static	short SSCBAS_FAIL_COND;
# line 37 "../sscbasClearanceSNC.stt"
static	short SSCBAS_RST_OUTS;
# line 38 "../sscbasClearanceSNC.stt"
static	short SSCBAS_PNK;
# line 40 "../sscbasClearanceSNC.stt"
static	string SSCBAS_CLR_STATS;
# line 41 "../sscbasClearanceSNC.stt"
static	string SSCBAS_INTLCK_STATS;
# line 45 "../sscbasClearanceSNC.stt"
static	short SSCBAS_OLD_FAIL_COND;
# line 46 "../sscbasClearanceSNC.stt"
static	short SSCBAS_FAILED_RST;


/* Function declarations */
# line 351 "../sscbasClearanceSNC.stt"
static void initVault(SS_ID seqg_env);
# line 361 "../sscbasClearanceSNC.stt"
static void resetVault(SS_ID seqg_env);
# line 366 "../sscbasClearanceSNC.stt"
static void SSCBAS_update_failed(SS_ID seqg_env, short report);
# line 375 "../sscbasClearanceSNC.stt"
static void SSCBAS_update_report(SS_ID seqg_env, short intlck);
# line 380 "../sscbasClearanceSNC.stt"
static void SSCBAS_status(SS_ID seqg_env);
# line 388 "../sscbasClearanceSNC.stt"
static void SSCBAS_clear_underway(SS_ID seqg_env);

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "init" in state set "SSCBAS_clearance_status" ******/

/* Event function for state "init" in state set "SSCBAS_clearance_status" */
static seqBool seqg_event_SSCBAS_clearance_status_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 78 "../sscbasClearanceSNC.stt"
	if (seq_delay(seqg_env, 2))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "SSCBAS_clearance_status" */
static void seqg_action_SSCBAS_clearance_status_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 79 "../sscbasClearanceSNC.stt"
			initVault(seqg_env);
# line 80 "../sscbasClearanceSNC.stt"
			printf("\n%sSSC BASEMENT VAULT INITIALISATION COMPLETED%s\n", OK, DEF);
		}
		return;
	}
}

/****** Code for state "watchman_1_pressed" in state set "SSCBAS_clearance_status" ******/

/* Event function for state "watchman_1_pressed" in state set "SSCBAS_clearance_status" */
static seqBool seqg_event_SSCBAS_clearance_status_0_watchman_1_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 86 "../sscbasClearanceSNC.stt"
	if (SSCBAS_FAIL_COND != STOK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 91 "../sscbasClearanceSNC.stt"
	if (SSC_W1_STS == WFVC)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 95 "../sscbasClearanceSNC.stt"
	if (SSC_W1_STS == B2OFF)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_1_pressed" in state set "SSCBAS_clearance_status" */
static void seqg_action_SSCBAS_clearance_status_0_watchman_1_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 87 "../sscbasClearanceSNC.stt"
			SSCBAS_OLD_FAIL_COND = SSCBAS_FAIL_COND;
		}
		return;
	case 1:
		{
		}
		return;
	case 2:
		{
# line 96 "../sscbasClearanceSNC.stt"
			SSCBAS_update_report(seqg_env, B2OFF);
# line 97 "../sscbasClearanceSNC.stt"
			SSCBAS_clear_underway(seqg_env);
		}
		return;
	}
}

/****** Code for state "clearance_pending" in state set "SSCBAS_clearance_status" ******/

/* Entry function for state "clearance_pending" in state set "SSCBAS_clearance_status" */
static void seqg_entry_SSCBAS_clearance_status_0_clearance_pending(SS_ID seqg_env)
{
# line 106 "../sscbasClearanceSNC.stt"
	resetVault(seqg_env);
# line 107 "../sscbasClearanceSNC.stt"
	SSCBAS_update_report(seqg_env, WFVC);
}

/* Event function for state "clearance_pending" in state set "SSCBAS_clearance_status" */
static seqBool seqg_event_SSCBAS_clearance_status_0_clearance_pending(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 110 "../sscbasClearanceSNC.stt"
	if (SSC_W1_STS != WFVC)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "clearance_pending" in state set "SSCBAS_clearance_status" */
static void seqg_action_SSCBAS_clearance_status_0_clearance_pending(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "watchman_2_pressed" in state set "SSCBAS_clearance_status" ******/

/* Event function for state "watchman_2_pressed" in state set "SSCBAS_clearance_status" */
static seqBool seqg_event_SSCBAS_clearance_status_0_watchman_2_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 119 "../sscbasClearanceSNC.stt"
	if (SSCBAS_FAIL_COND != STOK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 123 "../sscbasClearanceSNC.stt"
	if (SSC_W2_STS == B2ON)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_2_pressed" in state set "SSCBAS_clearance_status" */
static void seqg_action_SSCBAS_clearance_status_0_watchman_2_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 124 "../sscbasClearanceSNC.stt"
			SSCBAS_update_report(seqg_env, B2ON);
		}
		return;
	}
}

/****** Code for state "watchman_2_released" in state set "SSCBAS_clearance_status" ******/

/* Event function for state "watchman_2_released" in state set "SSCBAS_clearance_status" */
static seqBool seqg_event_SSCBAS_clearance_status_0_watchman_2_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 130 "../sscbasClearanceSNC.stt"
	if (SSCBAS_FAIL_COND != STOK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 134 "../sscbasClearanceSNC.stt"
	if (SSC_W2_STS != B2ON)
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_2_released" in state set "SSCBAS_clearance_status" */
static void seqg_action_SSCBAS_clearance_status_0_watchman_2_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 135 "../sscbasClearanceSNC.stt"
			SSCBAS_update_report(seqg_env, B3OFF);
		}
		return;
	}
}

/****** Code for state "watchman_3_pressed" in state set "SSCBAS_clearance_status" ******/

/* Event function for state "watchman_3_pressed" in state set "SSCBAS_clearance_status" */
static seqBool seqg_event_SSCBAS_clearance_status_0_watchman_3_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 141 "../sscbasClearanceSNC.stt"
	if (SSCBAS_FAIL_COND != STOK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 145 "../sscbasClearanceSNC.stt"
	if (SSC_W3_STS == B3ON)
	{
		*seqg_pnst = 6;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_3_pressed" in state set "SSCBAS_clearance_status" */
static void seqg_action_SSCBAS_clearance_status_0_watchman_3_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 146 "../sscbasClearanceSNC.stt"
			SSCBAS_update_report(seqg_env, B3ON);
		}
		return;
	}
}

/****** Code for state "watchman_3_released" in state set "SSCBAS_clearance_status" ******/

/* Event function for state "watchman_3_released" in state set "SSCBAS_clearance_status" */
static seqBool seqg_event_SSCBAS_clearance_status_0_watchman_3_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 153 "../sscbasClearanceSNC.stt"
	if (SSCBAS_FAIL_COND != STOK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 157 "../sscbasClearanceSNC.stt"
	if (SSC_W3_STS != B3ON)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_3_released" in state set "SSCBAS_clearance_status" */
static void seqg_action_SSCBAS_clearance_status_0_watchman_3_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 158 "../sscbasClearanceSNC.stt"
			SSCBAS_update_report(seqg_env, B4OFF);
		}
		return;
	}
}

/****** Code for state "watchman_4_pressed" in state set "SSCBAS_clearance_status" ******/

/* Event function for state "watchman_4_pressed" in state set "SSCBAS_clearance_status" */
static seqBool seqg_event_SSCBAS_clearance_status_0_watchman_4_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 164 "../sscbasClearanceSNC.stt"
	if (SSCBAS_FAIL_COND != STOK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 168 "../sscbasClearanceSNC.stt"
	if (!SSC_W4_STS)
	{
		*seqg_pnst = 8;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_4_pressed" in state set "SSCBAS_clearance_status" */
static void seqg_action_SSCBAS_clearance_status_0_watchman_4_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 169 "../sscbasClearanceSNC.stt"
			SSCBAS_update_report(seqg_env, B1ON);
		}
		return;
	}
}

/****** Code for state "watchman_1_released" in state set "SSCBAS_clearance_status" ******/

/* Event function for state "watchman_1_released" in state set "SSCBAS_clearance_status" */
static seqBool seqg_event_SSCBAS_clearance_status_0_watchman_1_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 175 "../sscbasClearanceSNC.stt"
	if (SSCBAS_FAIL_COND != STOK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 179 "../sscbasClearanceSNC.stt"
	if (SSC_W1_STS == B1ON)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_1_released" in state set "SSCBAS_clearance_status" */
static void seqg_action_SSCBAS_clearance_status_0_watchman_1_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 181 "../sscbasClearanceSNC.stt"
			SSCBAS_update_report(seqg_env, B5OFF);
		}
		return;
	}
}

/****** Code for state "watchman_5_pressed" in state set "SSCBAS_clearance_status" ******/

/* Event function for state "watchman_5_pressed" in state set "SSCBAS_clearance_status" */
static seqBool seqg_event_SSCBAS_clearance_status_0_watchman_5_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 187 "../sscbasClearanceSNC.stt"
	if (SSCBAS_FAIL_COND != STOK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 192 "../sscbasClearanceSNC.stt"
	if (!SSC_W5_STS)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_5_pressed" in state set "SSCBAS_clearance_status" */
static void seqg_action_SSCBAS_clearance_status_0_watchman_5_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 194 "../sscbasClearanceSNC.stt"
			SSCBAS_update_report(seqg_env, B4_5ON);
		}
		return;
	}
}

/****** Code for state "watchman_4_5_pressed" in state set "SSCBAS_clearance_status" ******/

/* Event function for state "watchman_4_5_pressed" in state set "SSCBAS_clearance_status" */
static seqBool seqg_event_SSCBAS_clearance_status_0_watchman_4_5_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 201 "../sscbasClearanceSNC.stt"
	if (SSCBAS_FAIL_COND != STOK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 205 "../sscbasClearanceSNC.stt"
	if (SSC_W4_STS == B5ON)
	{
		*seqg_pnst = 12;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 210 "../sscbasClearanceSNC.stt"
	if (SSC_W5_STS == B4ON)
	{
		*seqg_pnst = 11;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_4_5_pressed" in state set "SSCBAS_clearance_status" */
static void seqg_action_SSCBAS_clearance_status_0_watchman_4_5_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	case 2:
		{
		}
		return;
	}
}

/****** Code for state "watchman_4_released" in state set "SSCBAS_clearance_status" ******/

/* Event function for state "watchman_4_released" in state set "SSCBAS_clearance_status" */
static seqBool seqg_event_SSCBAS_clearance_status_0_watchman_4_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 218 "../sscbasClearanceSNC.stt"
	if (SSCBAS_FAIL_COND != STOK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 222 "../sscbasClearanceSNC.stt"
	if (SSC_W4_STS == B5ON)
	{
		*seqg_pnst = 12;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_4_released" in state set "SSCBAS_clearance_status" */
static void seqg_action_SSCBAS_clearance_status_0_watchman_4_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "watchman_5_released" in state set "SSCBAS_clearance_status" ******/

/* Event function for state "watchman_5_released" in state set "SSCBAS_clearance_status" */
static seqBool seqg_event_SSCBAS_clearance_status_0_watchman_5_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 231 "../sscbasClearanceSNC.stt"
	if (SSCBAS_FAIL_COND != STOK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 235 "../sscbasClearanceSNC.stt"
	if (SSC_W4_STS == B4ON)
	{
		*seqg_pnst = 11;
		*seqg_ptrn = 1;
		return TRUE;
	}
	if (TRUE)
	{
		*seqg_pnst = 13;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_5_released" in state set "SSCBAS_clearance_status" */
static void seqg_action_SSCBAS_clearance_status_0_watchman_5_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	case 2:
		{
		}
		return;
	}
}

/****** Code for state "gate_g2_closed" in state set "SSCBAS_clearance_status" ******/

/* Entry function for state "gate_g2_closed" in state set "SSCBAS_clearance_status" */
static void seqg_entry_SSCBAS_clearance_status_0_gate_g2_closed(SS_ID seqg_env)
{
# line 249 "../sscbasClearanceSNC.stt"
	SSCBAS_update_report(seqg_env, G2OFF);
}

/* Event function for state "gate_g2_closed" in state set "SSCBAS_clearance_status" */
static seqBool seqg_event_SSCBAS_clearance_status_0_gate_g2_closed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 252 "../sscbasClearanceSNC.stt"
	if (SSCBAS_FAIL_COND != STOK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 256 "../sscbasClearanceSNC.stt"
	if (SSC_W6_STS != G2OFF)
	{
		*seqg_pnst = 14;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "gate_g2_closed" in state set "SSCBAS_clearance_status" */
static void seqg_action_SSCBAS_clearance_status_0_gate_g2_closed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "watchman_6_pressed" in state set "SSCBAS_clearance_status" ******/

/* Entry function for state "watchman_6_pressed" in state set "SSCBAS_clearance_status" */
static void seqg_entry_SSCBAS_clearance_status_0_watchman_6_pressed(SS_ID seqg_env)
{
# line 266 "../sscbasClearanceSNC.stt"
	SSCBAS_update_report(seqg_env, B6OFF);
}

/* Event function for state "watchman_6_pressed" in state set "SSCBAS_clearance_status" */
static seqBool seqg_event_SSCBAS_clearance_status_0_watchman_6_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 268 "../sscbasClearanceSNC.stt"
	if (SSCBAS_FAIL_COND != STOK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 272 "../sscbasClearanceSNC.stt"
	if (!SSC_W6_STS)
	{
		*seqg_pnst = 15;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 277 "../sscbasClearanceSNC.stt"
	if (SSC_W6_STS != B6OFF)
	{
		*seqg_pnst = 13;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_6_pressed" in state set "SSCBAS_clearance_status" */
static void seqg_action_SSCBAS_clearance_status_0_watchman_6_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 274 "../sscbasClearanceSNC.stt"
			SSCBAS_status(seqg_env);
		}
		return;
	case 2:
		{
		}
		return;
	}
}

/****** Code for state "vault_cleared" in state set "SSCBAS_clearance_status" ******/

/* Entry function for state "vault_cleared" in state set "SSCBAS_clearance_status" */
static void seqg_entry_SSCBAS_clearance_status_0_vault_cleared(SS_ID seqg_env)
{
# line 285 "../sscbasClearanceSNC.stt"
	printf("%sSSC BASEMENT VAULT IN CLEARED STATE%s\n", CLR, DEF);
}

/* Event function for state "vault_cleared" in state set "SSCBAS_clearance_status" */
static seqBool seqg_event_SSCBAS_clearance_status_0_vault_cleared(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 287 "../sscbasClearanceSNC.stt"
	if (SSCBAS_VC != STOK)
	{
		*seqg_pnst = 16;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "vault_cleared" in state set "SSCBAS_clearance_status" */
static void seqg_action_SSCBAS_clearance_status_0_vault_cleared(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "paniq_faillure" in state set "SSCBAS_clearance_status" ******/

/* Event function for state "paniq_faillure" in state set "SSCBAS_clearance_status" */
static seqBool seqg_event_SSCBAS_clearance_status_0_paniq_faillure(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 295 "../sscbasClearanceSNC.stt"
	if (SSCBAS_VC != SSCBASPNK)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
	if (TRUE)
	{
		*seqg_pnst = 17;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "paniq_faillure" in state set "SSCBAS_clearance_status" */
static void seqg_action_SSCBAS_clearance_status_0_paniq_faillure(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 300 "../sscbasClearanceSNC.stt"
			printf("SSC BASEMENT VAULT CLEARED FAILURE CONDITION: ");
# line 301 "../sscbasClearanceSNC.stt"
			SSCBAS_update_failed(seqg_env, SSCBASPNK);
		}
		return;
	}
}

/****** Code for state "recover_from_paniq" in state set "SSCBAS_clearance_status" ******/

/* Exit function for state "recover_from_paniq" in state set "SSCBAS_clearance_status" */
static void seqg_exit_SSCBAS_clearance_status_0_recover_from_paniq(SS_ID seqg_env)
{
# line 314 "../sscbasClearanceSNC.stt"
	SSCBAS_FAILED_RST = FALSE;
}

/* Event function for state "recover_from_paniq" in state set "SSCBAS_clearance_status" */
static seqBool seqg_event_SSCBAS_clearance_status_0_recover_from_paniq(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 310 "../sscbasClearanceSNC.stt"
	if (!SSCBAS_PNK)
	{
		*seqg_pnst = 19;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "recover_from_paniq" in state set "SSCBAS_clearance_status" */
static void seqg_action_SSCBAS_clearance_status_0_recover_from_paniq(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "clearance_faillures" in state set "SSCBAS_clearance_status" ******/

/* Entry function for state "clearance_faillures" in state set "SSCBAS_clearance_status" */
static void seqg_entry_SSCBAS_clearance_status_0_clearance_faillures(SS_ID seqg_env)
{
# line 323 "../sscbasClearanceSNC.stt"
	printf("SSC BASEMENT CLEARANCE FAILURE CONDITION: ");
# line 324 "../sscbasClearanceSNC.stt"
	SSCBAS_OLD_FAIL_COND = SSCBAS_FAIL_COND;
# line 325 "../sscbasClearanceSNC.stt"
	SSCBAS_FAILED_RST = FALSE;
}

/* Event function for state "clearance_faillures" in state set "SSCBAS_clearance_status" */
static seqBool seqg_event_SSCBAS_clearance_status_0_clearance_faillures(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 19;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "clearance_faillures" in state set "SSCBAS_clearance_status" */
static void seqg_action_SSCBAS_clearance_status_0_clearance_faillures(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 330 "../sscbasClearanceSNC.stt"
			SSCBAS_update_failed(seqg_env, SSCBAS_FAIL_COND == FAIL ? STOK : SSCBAS_FAIL_COND);
		}
		return;
	}
}

/****** Code for state "recover_from_faillure" in state set "SSCBAS_clearance_status" ******/

/* Event function for state "recover_from_faillure" in state set "SSCBAS_clearance_status" */
static seqBool seqg_event_SSCBAS_clearance_status_0_recover_from_faillure(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 336 "../sscbasClearanceSNC.stt"
	if (!SSCBAS_FAIL_COND)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 343 "../sscbasClearanceSNC.stt"
	if (SSCBAS_FAIL_COND != SSCBAS_OLD_FAIL_COND)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "recover_from_faillure" in state set "SSCBAS_clearance_status" */
static void seqg_action_SSCBAS_clearance_status_0_recover_from_faillure(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 338 "../sscbasClearanceSNC.stt"
			printf("%sSSC BASEMENT RECOVERING FROM FAILLURE : ENTERING W1 STATE%s\n", OK, DEF);
		}
		return;
	case 1:
		{
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{SYS}:RST-SSCBAS.PROC", (size_t)&SSCBAS_RST_OUTS, "SSCBAS_RST_OUTS", P_SHORT, 1, 1, 0, 0, 0, 0},
	{"{SYS}:SSCBAS-CLR-STATS", (size_t)&SSCBAS_CLR_STATS, "SSCBAS_CLR_STATS", P_STRING, 1, 2, 0, 0, 0, 0},
	{"{SYS}:SSCBAS-INTLCK-STATS", (size_t)&SSCBAS_INTLCK_STATS, "SSCBAS_INTLCK_STATS", P_STRING, 1, 3, 0, 0, 0, 0},
	{"{SYS}:SSCBAS-VC", (size_t)&SSCBAS_VC, "SSCBAS_VC", P_SHORT, 1, 4, 0, 1, 0, 0},
	{"{SYS}:SSC-W1-STS", (size_t)&SSC_W1_STS, "SSC_W1_STS", P_SHORT, 1, 5, 0, 1, 0, 0},
	{"{SYS}:SSC-W2-STS", (size_t)&SSC_W2_STS, "SSC_W2_STS", P_SHORT, 1, 6, 0, 1, 0, 0},
	{"{SYS}:SSC-W3-STS", (size_t)&SSC_W3_STS, "SSC_W3_STS", P_SHORT, 1, 7, 0, 1, 0, 0},
	{"{SYS}:SSC-W4-STS", (size_t)&SSC_W4_STS, "SSC_W4_STS", P_SHORT, 1, 8, 0, 1, 0, 0},
	{"{SYS}:SSC-W5-STS", (size_t)&SSC_W5_STS, "SSC_W5_STS", P_SHORT, 1, 9, 0, 1, 0, 0},
	{"{SYS}:SSC-W6-STS", (size_t)&SSC_W6_STS, "SSC_W6_STS", P_SHORT, 1, 10, 0, 1, 0, 0},
	{"{SYS}:SSCBAS-FAIL-COND", (size_t)&SSCBAS_FAIL_COND, "SSCBAS_FAIL_COND", P_SHORT, 1, 11, 0, 1, 0, 0},
	{"{SYS}:SSCBAS-PNK", (size_t)&SSCBAS_PNK, "SSCBAS_PNK", P_SHORT, 1, 12, 0, 1, 0, 0},
};

/* Event masks for state set "SSCBAS_clearance_status" */
static const seqMask seqg_mask_SSCBAS_clearance_status_0_init[] = {
	0x00000000,
};
static const seqMask seqg_mask_SSCBAS_clearance_status_0_watchman_1_pressed[] = {
	0x00000820,
};
static const seqMask seqg_mask_SSCBAS_clearance_status_0_clearance_pending[] = {
	0x00000020,
};
static const seqMask seqg_mask_SSCBAS_clearance_status_0_watchman_2_pressed[] = {
	0x00000840,
};
static const seqMask seqg_mask_SSCBAS_clearance_status_0_watchman_2_released[] = {
	0x00000840,
};
static const seqMask seqg_mask_SSCBAS_clearance_status_0_watchman_3_pressed[] = {
	0x00000880,
};
static const seqMask seqg_mask_SSCBAS_clearance_status_0_watchman_3_released[] = {
	0x00000880,
};
static const seqMask seqg_mask_SSCBAS_clearance_status_0_watchman_4_pressed[] = {
	0x00000900,
};
static const seqMask seqg_mask_SSCBAS_clearance_status_0_watchman_1_released[] = {
	0x00000820,
};
static const seqMask seqg_mask_SSCBAS_clearance_status_0_watchman_5_pressed[] = {
	0x00000a00,
};
static const seqMask seqg_mask_SSCBAS_clearance_status_0_watchman_4_5_pressed[] = {
	0x00000b00,
};
static const seqMask seqg_mask_SSCBAS_clearance_status_0_watchman_4_released[] = {
	0x00000900,
};
static const seqMask seqg_mask_SSCBAS_clearance_status_0_watchman_5_released[] = {
	0x00000900,
};
static const seqMask seqg_mask_SSCBAS_clearance_status_0_gate_g2_closed[] = {
	0x00000c00,
};
static const seqMask seqg_mask_SSCBAS_clearance_status_0_watchman_6_pressed[] = {
	0x00000c00,
};
static const seqMask seqg_mask_SSCBAS_clearance_status_0_vault_cleared[] = {
	0x00000010,
};
static const seqMask seqg_mask_SSCBAS_clearance_status_0_paniq_faillure[] = {
	0x00000010,
};
static const seqMask seqg_mask_SSCBAS_clearance_status_0_recover_from_paniq[] = {
	0x00001000,
};
static const seqMask seqg_mask_SSCBAS_clearance_status_0_clearance_faillures[] = {
	0x00000000,
};
static const seqMask seqg_mask_SSCBAS_clearance_status_0_recover_from_faillure[] = {
	0x00000800,
};

/* State table for state set "SSCBAS_clearance_status" */
static seqState seqg_states_SSCBAS_clearance_status[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_SSCBAS_clearance_status_0_init,
	/* event function */    seqg_event_SSCBAS_clearance_status_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCBAS_clearance_status_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_1_pressed",
	/* action function */   seqg_action_SSCBAS_clearance_status_0_watchman_1_pressed,
	/* event function */    seqg_event_SSCBAS_clearance_status_0_watchman_1_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCBAS_clearance_status_0_watchman_1_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "clearance_pending",
	/* action function */   seqg_action_SSCBAS_clearance_status_0_clearance_pending,
	/* event function */    seqg_event_SSCBAS_clearance_status_0_clearance_pending,
	/* entry function */    seqg_entry_SSCBAS_clearance_status_0_clearance_pending,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCBAS_clearance_status_0_clearance_pending,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "watchman_2_pressed",
	/* action function */   seqg_action_SSCBAS_clearance_status_0_watchman_2_pressed,
	/* event function */    seqg_event_SSCBAS_clearance_status_0_watchman_2_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCBAS_clearance_status_0_watchman_2_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_2_released",
	/* action function */   seqg_action_SSCBAS_clearance_status_0_watchman_2_released,
	/* event function */    seqg_event_SSCBAS_clearance_status_0_watchman_2_released,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCBAS_clearance_status_0_watchman_2_released,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_3_pressed",
	/* action function */   seqg_action_SSCBAS_clearance_status_0_watchman_3_pressed,
	/* event function */    seqg_event_SSCBAS_clearance_status_0_watchman_3_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCBAS_clearance_status_0_watchman_3_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_3_released",
	/* action function */   seqg_action_SSCBAS_clearance_status_0_watchman_3_released,
	/* event function */    seqg_event_SSCBAS_clearance_status_0_watchman_3_released,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCBAS_clearance_status_0_watchman_3_released,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_4_pressed",
	/* action function */   seqg_action_SSCBAS_clearance_status_0_watchman_4_pressed,
	/* event function */    seqg_event_SSCBAS_clearance_status_0_watchman_4_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCBAS_clearance_status_0_watchman_4_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_1_released",
	/* action function */   seqg_action_SSCBAS_clearance_status_0_watchman_1_released,
	/* event function */    seqg_event_SSCBAS_clearance_status_0_watchman_1_released,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCBAS_clearance_status_0_watchman_1_released,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_5_pressed",
	/* action function */   seqg_action_SSCBAS_clearance_status_0_watchman_5_pressed,
	/* event function */    seqg_event_SSCBAS_clearance_status_0_watchman_5_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCBAS_clearance_status_0_watchman_5_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_4_5_pressed",
	/* action function */   seqg_action_SSCBAS_clearance_status_0_watchman_4_5_pressed,
	/* event function */    seqg_event_SSCBAS_clearance_status_0_watchman_4_5_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCBAS_clearance_status_0_watchman_4_5_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_4_released",
	/* action function */   seqg_action_SSCBAS_clearance_status_0_watchman_4_released,
	/* event function */    seqg_event_SSCBAS_clearance_status_0_watchman_4_released,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCBAS_clearance_status_0_watchman_4_released,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_5_released",
	/* action function */   seqg_action_SSCBAS_clearance_status_0_watchman_5_released,
	/* event function */    seqg_event_SSCBAS_clearance_status_0_watchman_5_released,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCBAS_clearance_status_0_watchman_5_released,
	/* state options */     (0)
	},
	{
	/* state name */        "gate_g2_closed",
	/* action function */   seqg_action_SSCBAS_clearance_status_0_gate_g2_closed,
	/* event function */    seqg_event_SSCBAS_clearance_status_0_gate_g2_closed,
	/* entry function */    seqg_entry_SSCBAS_clearance_status_0_gate_g2_closed,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCBAS_clearance_status_0_gate_g2_closed,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "watchman_6_pressed",
	/* action function */   seqg_action_SSCBAS_clearance_status_0_watchman_6_pressed,
	/* event function */    seqg_event_SSCBAS_clearance_status_0_watchman_6_pressed,
	/* entry function */    seqg_entry_SSCBAS_clearance_status_0_watchman_6_pressed,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCBAS_clearance_status_0_watchman_6_pressed,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "vault_cleared",
	/* action function */   seqg_action_SSCBAS_clearance_status_0_vault_cleared,
	/* event function */    seqg_event_SSCBAS_clearance_status_0_vault_cleared,
	/* entry function */    seqg_entry_SSCBAS_clearance_status_0_vault_cleared,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCBAS_clearance_status_0_vault_cleared,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "paniq_faillure",
	/* action function */   seqg_action_SSCBAS_clearance_status_0_paniq_faillure,
	/* event function */    seqg_event_SSCBAS_clearance_status_0_paniq_faillure,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCBAS_clearance_status_0_paniq_faillure,
	/* state options */     (0)
	},
	{
	/* state name */        "recover_from_paniq",
	/* action function */   seqg_action_SSCBAS_clearance_status_0_recover_from_paniq,
	/* event function */    seqg_event_SSCBAS_clearance_status_0_recover_from_paniq,
	/* entry function */    0,
	/* exit function */     seqg_exit_SSCBAS_clearance_status_0_recover_from_paniq,
	/* event mask array */  seqg_mask_SSCBAS_clearance_status_0_recover_from_paniq,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
	{
	/* state name */        "clearance_faillures",
	/* action function */   seqg_action_SSCBAS_clearance_status_0_clearance_faillures,
	/* event function */    seqg_event_SSCBAS_clearance_status_0_clearance_faillures,
	/* entry function */    seqg_entry_SSCBAS_clearance_status_0_clearance_faillures,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCBAS_clearance_status_0_clearance_faillures,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
	{
	/* state name */        "recover_from_faillure",
	/* action function */   seqg_action_SSCBAS_clearance_status_0_recover_from_faillure,
	/* event function */    seqg_event_SSCBAS_clearance_status_0_recover_from_faillure,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCBAS_clearance_status_0_recover_from_faillure,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "SSCBAS_clearance_status",
	/* states */            seqg_states_SSCBAS_clearance_status,
	/* number of states */  20
	},
};

/* Program table (global) */
seqProgram sscbasClearanceSNC = {
	/* magic number */      2002001,
	/* program name */      "sscbasClearanceSNC",
	/* channels */          seqg_chans,
	/* num. channels */     12,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 351 "../sscbasClearanceSNC.stt"
static void initVault(SS_ID seqg_env)
{
# line 352 "../sscbasClearanceSNC.stt"
	SSCBAS_OLD_FAIL_COND = SSCBAS_FAIL_COND;
# line 353 "../sscbasClearanceSNC.stt"
	SSCBAS_RST_OUTS = TRUE;
# line 354 "../sscbasClearanceSNC.stt"
	not_cleared(SSCBAS_CLR_STATS);
# line 355 "../sscbasClearanceSNC.stt"
	report_error(SSCBAS_INTLCK_STATS, 0);
# line 356 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*SSCBAS_RST_OUTS*/, SYNC, DEFAULT_TIMEOUT);
# line 357 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SSCBAS_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 358 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*SSCBAS_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 361 "../sscbasClearanceSNC.stt"
static void resetVault(SS_ID seqg_env)
{
# line 362 "../sscbasClearanceSNC.stt"
	not_cleared(SSCBAS_CLR_STATS);
# line 363 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SSCBAS_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 366 "../sscbasClearanceSNC.stt"
static void SSCBAS_update_failed(SS_ID seqg_env, short report)
{
# line 368 "../sscbasClearanceSNC.stt"
	clear_failed(SSCBAS_CLR_STATS);
# line 369 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SSCBAS_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 370 "../sscbasClearanceSNC.stt"
	report_error(SSCBAS_INTLCK_STATS, report);
# line 371 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*SSCBAS_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 372 "../sscbasClearanceSNC.stt"
	printf("%s%s%s\n", ERROR, SSCBAS_INTLCK_STATS, DEF);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 375 "../sscbasClearanceSNC.stt"
static void SSCBAS_update_report(SS_ID seqg_env, short intlck)
{
# line 376 "../sscbasClearanceSNC.stt"
	report_error(SSCBAS_INTLCK_STATS, intlck);
# line 377 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*SSCBAS_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 380 "../sscbasClearanceSNC.stt"
static void SSCBAS_status(SS_ID seqg_env)
{
# line 382 "../sscbasClearanceSNC.stt"
	cleared(SSCBAS_CLR_STATS);
# line 383 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SSCBAS_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 384 "../sscbasClearanceSNC.stt"
	report_error(SSCBAS_INTLCK_STATS, 0);
# line 385 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*SSCBAS_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 388 "../sscbasClearanceSNC.stt"
static void SSCBAS_clear_underway(SS_ID seqg_env)
{
# line 390 "../sscbasClearanceSNC.stt"
	clear_underway(SSCBAS_CLR_STATS);
# line 391 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SSCBAS_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var
# line 395 "../sscbasClearanceSNC.stt"


inline void cleared(string vault_status) {   
    strcpy(vault_status, mes_array[1]); // Area cleared  
}
////////////////////////////////////////////////
inline void not_cleared(string vault_status) {  
   strcpy(vault_status, mes_array[2]); // Area not cleared    
}
///////////////////////////////////////////////
inline void clear_underway(string vault_status) { 
   strcpy(vault_status, mes_array[3]);  // Area clearance underway    
}
//////////////////////////////////////////////
inline void clear_failed(string vault_status) { 
   strcpy(vault_status, mes_array[5]); // Area clearance fail   
}
////////////////////////////////////////////////
inline void report_error(string vault_interlock, short intlock)
{
   strcpy(vault_interlock, mes_array[intlock]);
}
	


/* Register sequencer commands and program */
#include "epicsExport.h"
static void sscbasClearanceSNCRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&sscbasClearanceSNC);
}
epicsExportRegistrar(sscbasClearanceSNCRegistrar);
