/* C code for program a13aClearanceSNC, generated by snc from ../a13aClearanceSNC.stt */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 3 "../a13aClearanceSNC.stt"

/*******************************************************************/
#include "vcs_var_mes.h" // define this here so C functions are seen
/*******************************************************************/
#define	VCOK       	0
#define FAIL		-1
#define	G5AS1OFF	144
#define	G5AS2OFF	143
#define	B9bOFF      142
#define	B9aON       141


/* Variable declarations */
# line 15 "../a13aClearanceSNC.stt"
static	short A13A_INIT;
# line 16 "../a13aClearanceSNC.stt"
static	short A13A_VC;
# line 17 "../a13aClearanceSNC.stt"
static	short A13A_W9a_STS;
# line 18 "../a13aClearanceSNC.stt"
static	short A13A_W9b_STS;
# line 19 "../a13aClearanceSNC.stt"
static	short A13A_FAIL_COND;
# line 20 "../a13aClearanceSNC.stt"
static	string A13A_CLR_STATS;
# line 21 "../a13aClearanceSNC.stt"
static	string A13A_INTLCK_STATS;
# line 23 "../a13aClearanceSNC.stt"
static	short A13AUpdate;
# line 24 "../a13aClearanceSNC.stt"
static	short A13A_OLD_FAIL_COND;


/* Function declarations */
# line 166 "../a13aClearanceSNC.stt"
static void initVault(SS_ID seqg_env);
# line 176 "../a13aClearanceSNC.stt"
static void A13A_update_failed(SS_ID seqg_env, short report);
# line 185 "../a13aClearanceSNC.stt"
static void A13A_update_report(SS_ID seqg_env, short intlck);
# line 190 "../a13aClearanceSNC.stt"
static void A13A_status(SS_ID seqg_env);
# line 198 "../a13aClearanceSNC.stt"
static void A13A_clear_underway(SS_ID seqg_env);

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "init" in state set "A13A_clearance_status" ******/

/* Event function for state "init" in state set "A13A_clearance_status" */
static seqBool seqg_event_A13A_clearance_status_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 43 "../a13aClearanceSNC.stt"
	if (seq_delay(seqg_env, 3))
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "A13A_clearance_status" */
static void seqg_action_A13A_clearance_status_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 44 "../a13aClearanceSNC.stt"
			initVault(seqg_env);
# line 45 "../a13aClearanceSNC.stt"
			printf("\n%sI-LINE AREA INITIALISATION COMPLETED%s\n", OK, DEF);
		}
		return;
	}
}

/****** Code for state "vault_cleared" in state set "A13A_clearance_status" ******/

/* Entry function for state "vault_cleared" in state set "A13A_clearance_status" */
static void seqg_entry_A13A_clearance_status_0_vault_cleared(SS_ID seqg_env)
{
# line 53 "../a13aClearanceSNC.stt"
	printf("%sI-LINE AREA IN CLEARED STATE%s\n", CLR, DEF);
}

/* Event function for state "vault_cleared" in state set "A13A_clearance_status" */
static seqBool seqg_event_A13A_clearance_status_0_vault_cleared(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 55 "../a13aClearanceSNC.stt"
	if (A13A_VC != VCOK)
	{
		*seqg_pnst = 8;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "vault_cleared" in state set "A13A_clearance_status" */
static void seqg_action_A13A_clearance_status_0_vault_cleared(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "recover_faillure" in state set "A13A_clearance_status" ******/

/* Event function for state "recover_faillure" in state set "A13A_clearance_status" */
static seqBool seqg_event_A13A_clearance_status_0_recover_faillure(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 62 "../a13aClearanceSNC.stt"
	if (!A13A_FAIL_COND)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 69 "../a13aClearanceSNC.stt"
	if (A13A_FAIL_COND != A13A_OLD_FAIL_COND)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "recover_faillure" in state set "A13A_clearance_status" */
static void seqg_action_A13A_clearance_status_0_recover_faillure(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 63 "../a13aClearanceSNC.stt"
			if (!A13AUpdate)
			{
# line 64 "../a13aClearanceSNC.stt"
				printf("%sRECOVERING FROM FAILLURE - ENTERING W9a STATE%s\n", OK, DEF);
# line 65 "../a13aClearanceSNC.stt"
				A13AUpdate = TRUE;
			}
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "watchman_9a_pressed" in state set "A13A_clearance_status" ******/

/* Event function for state "watchman_9a_pressed" in state set "A13A_clearance_status" */
static seqBool seqg_event_A13A_clearance_status_0_watchman_9a_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 76 "../a13aClearanceSNC.stt"
	if (A13A_FAIL_COND != VCOK)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 80 "../a13aClearanceSNC.stt"
	if (A13A_W9a_STS == B9aON)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_9a_pressed" in state set "A13A_clearance_status" */
static void seqg_action_A13A_clearance_status_0_watchman_9a_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 77 "../a13aClearanceSNC.stt"
			A13A_OLD_FAIL_COND = A13A_FAIL_COND;
		}
		return;
	case 1:
		{
# line 81 "../a13aClearanceSNC.stt"
			A13A_clear_underway(seqg_env);
# line 82 "../a13aClearanceSNC.stt"
			A13A_update_report(seqg_env, B9aON);
		}
		return;
	}
}

/****** Code for state "watchman_9a_released" in state set "A13A_clearance_status" ******/

/* Event function for state "watchman_9a_released" in state set "A13A_clearance_status" */
static seqBool seqg_event_A13A_clearance_status_0_watchman_9a_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 88 "../a13aClearanceSNC.stt"
	if (A13A_W9a_STS == FAIL)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 92 "../a13aClearanceSNC.stt"
	if (A13A_W9a_STS != B9aON)
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_9a_released" in state set "A13A_clearance_status" */
static void seqg_action_A13A_clearance_status_0_watchman_9a_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "gate_g5a_closed" in state set "A13A_clearance_status" ******/

/* Event function for state "gate_g5a_closed" in state set "A13A_clearance_status" */
static seqBool seqg_event_A13A_clearance_status_0_gate_g5a_closed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 98 "../a13aClearanceSNC.stt"
	if (A13A_FAIL_COND != VCOK)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 102 "../a13aClearanceSNC.stt"
	if (A13A_W9b_STS == G5AS1OFF)
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 106 "../a13aClearanceSNC.stt"
	if (A13A_W9b_STS == G5AS2OFF)
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 2;
		return TRUE;
	}
	if (TRUE)
	{
		*seqg_pnst = 6;
		*seqg_ptrn = 3;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "gate_g5a_closed" in state set "A13A_clearance_status" */
static void seqg_action_A13A_clearance_status_0_gate_g5a_closed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 103 "../a13aClearanceSNC.stt"
			A13A_update_report(seqg_env, G5AS1OFF);
		}
		return;
	case 2:
		{
# line 107 "../a13aClearanceSNC.stt"
			A13A_update_report(seqg_env, G5AS2OFF);
		}
		return;
	case 3:
		{
# line 111 "../a13aClearanceSNC.stt"
			A13A_update_report(seqg_env, B9bOFF);
		}
		return;
	}
}

/****** Code for state "watchman_9b_pressed" in state set "A13A_clearance_status" ******/

/* Event function for state "watchman_9b_pressed" in state set "A13A_clearance_status" */
static seqBool seqg_event_A13A_clearance_status_0_watchman_9b_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 118 "../a13aClearanceSNC.stt"
	if (A13A_W9b_STS == FAIL)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 123 "../a13aClearanceSNC.stt"
	if (!A13A_W9b_STS)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_9b_pressed" in state set "A13A_clearance_status" */
static void seqg_action_A13A_clearance_status_0_watchman_9b_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 125 "../a13aClearanceSNC.stt"
			A13A_status(seqg_env);
		}
		return;
	}
}

/****** Code for state "clearance_faillures" in state set "A13A_clearance_status" ******/

/* Entry function for state "clearance_faillures" in state set "A13A_clearance_status" */
static void seqg_entry_A13A_clearance_status_0_clearance_faillures(SS_ID seqg_env)
{
# line 134 "../a13aClearanceSNC.stt"
	printf("A13A CLEARANCE FAILURE CONDITION: ");
# line 135 "../a13aClearanceSNC.stt"
	A13AUpdate = FALSE;
}

/* Exit function for state "clearance_faillures" in state set "A13A_clearance_status" */
static void seqg_exit_A13A_clearance_status_0_clearance_faillures(SS_ID seqg_env)
{
# line 143 "../a13aClearanceSNC.stt"
	A13A_OLD_FAIL_COND = A13A_FAIL_COND;
}

/* Event function for state "clearance_faillures" in state set "A13A_clearance_status" */
static seqBool seqg_event_A13A_clearance_status_0_clearance_faillures(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "clearance_faillures" in state set "A13A_clearance_status" */
static void seqg_action_A13A_clearance_status_0_clearance_faillures(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 139 "../a13aClearanceSNC.stt"
			A13A_update_failed(seqg_env, A13A_FAIL_COND);
		}
		return;
	}
}

/****** Code for state "vc_faillures" in state set "A13A_clearance_status" ******/

/* Entry function for state "vc_faillures" in state set "A13A_clearance_status" */
static void seqg_entry_A13A_clearance_status_0_vc_faillures(SS_ID seqg_env)
{
# line 152 "../a13aClearanceSNC.stt"
	printf("A13A CLEAR FAILURE CONDITION: ");
# line 153 "../a13aClearanceSNC.stt"
	A13AUpdate = FALSE;
}

/* Exit function for state "vc_faillures" in state set "A13A_clearance_status" */
static void seqg_exit_A13A_clearance_status_0_vc_faillures(SS_ID seqg_env)
{
# line 161 "../a13aClearanceSNC.stt"
	A13A_OLD_FAIL_COND = A13A_FAIL_COND;
}

/* Event function for state "vc_faillures" in state set "A13A_clearance_status" */
static seqBool seqg_event_A13A_clearance_status_0_vc_faillures(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "vc_faillures" in state set "A13A_clearance_status" */
static void seqg_action_A13A_clearance_status_0_vc_faillures(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 157 "../a13aClearanceSNC.stt"
			A13A_update_failed(seqg_env, A13A_VC);
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{SYS}:A13A-CLR-STATS", (size_t)&A13A_CLR_STATS, "A13A_CLR_STATS", P_STRING, 1, 1, 0, 0, 0, 0},
	{"{SYS}:A13A-INTLCK-STATS", (size_t)&A13A_INTLCK_STATS, "A13A_INTLCK_STATS", P_STRING, 1, 2, 0, 0, 0, 0},
	{"{SYS}:A13A-VC", (size_t)&A13A_VC, "A13A_VC", P_SHORT, 1, 3, 0, 1, 0, 0},
	{"{SYS}:A13A-INIT", (size_t)&A13A_INIT, "A13A_INIT", P_SHORT, 1, 4, 0, 0, 0, 0},
	{"{SYS}:A13A-W9a-STS", (size_t)&A13A_W9a_STS, "A13A_W9a_STS", P_SHORT, 1, 5, 0, 1, 0, 0},
	{"{SYS}:A13A-W9b-STS", (size_t)&A13A_W9b_STS, "A13A_W9b_STS", P_SHORT, 1, 6, 0, 1, 0, 0},
	{"{SYS}:A13A-FAIL-COND", (size_t)&A13A_FAIL_COND, "A13A_FAIL_COND", P_SHORT, 1, 7, 0, 1, 0, 0},
};

/* Event masks for state set "A13A_clearance_status" */
static const seqMask seqg_mask_A13A_clearance_status_0_init[] = {
	0x00000000,
};
static const seqMask seqg_mask_A13A_clearance_status_0_vault_cleared[] = {
	0x00000008,
};
static const seqMask seqg_mask_A13A_clearance_status_0_recover_faillure[] = {
	0x00000080,
};
static const seqMask seqg_mask_A13A_clearance_status_0_watchman_9a_pressed[] = {
	0x000000a0,
};
static const seqMask seqg_mask_A13A_clearance_status_0_watchman_9a_released[] = {
	0x00000020,
};
static const seqMask seqg_mask_A13A_clearance_status_0_gate_g5a_closed[] = {
	0x000000c0,
};
static const seqMask seqg_mask_A13A_clearance_status_0_watchman_9b_pressed[] = {
	0x00000040,
};
static const seqMask seqg_mask_A13A_clearance_status_0_clearance_faillures[] = {
	0x00000000,
};
static const seqMask seqg_mask_A13A_clearance_status_0_vc_faillures[] = {
	0x00000000,
};

/* State table for state set "A13A_clearance_status" */
static seqState seqg_states_A13A_clearance_status[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_A13A_clearance_status_0_init,
	/* event function */    seqg_event_A13A_clearance_status_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_A13A_clearance_status_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "vault_cleared",
	/* action function */   seqg_action_A13A_clearance_status_0_vault_cleared,
	/* event function */    seqg_event_A13A_clearance_status_0_vault_cleared,
	/* entry function */    seqg_entry_A13A_clearance_status_0_vault_cleared,
	/* exit function */     0,
	/* event mask array */  seqg_mask_A13A_clearance_status_0_vault_cleared,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "recover_faillure",
	/* action function */   seqg_action_A13A_clearance_status_0_recover_faillure,
	/* event function */    seqg_event_A13A_clearance_status_0_recover_faillure,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_A13A_clearance_status_0_recover_faillure,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_9a_pressed",
	/* action function */   seqg_action_A13A_clearance_status_0_watchman_9a_pressed,
	/* event function */    seqg_event_A13A_clearance_status_0_watchman_9a_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_A13A_clearance_status_0_watchman_9a_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_9a_released",
	/* action function */   seqg_action_A13A_clearance_status_0_watchman_9a_released,
	/* event function */    seqg_event_A13A_clearance_status_0_watchman_9a_released,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_A13A_clearance_status_0_watchman_9a_released,
	/* state options */     (0)
	},
	{
	/* state name */        "gate_g5a_closed",
	/* action function */   seqg_action_A13A_clearance_status_0_gate_g5a_closed,
	/* event function */    seqg_event_A13A_clearance_status_0_gate_g5a_closed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_A13A_clearance_status_0_gate_g5a_closed,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_9b_pressed",
	/* action function */   seqg_action_A13A_clearance_status_0_watchman_9b_pressed,
	/* event function */    seqg_event_A13A_clearance_status_0_watchman_9b_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_A13A_clearance_status_0_watchman_9b_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "clearance_faillures",
	/* action function */   seqg_action_A13A_clearance_status_0_clearance_faillures,
	/* event function */    seqg_event_A13A_clearance_status_0_clearance_faillures,
	/* entry function */    seqg_entry_A13A_clearance_status_0_clearance_faillures,
	/* exit function */     seqg_exit_A13A_clearance_status_0_clearance_faillures,
	/* event mask array */  seqg_mask_A13A_clearance_status_0_clearance_faillures,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
	{
	/* state name */        "vc_faillures",
	/* action function */   seqg_action_A13A_clearance_status_0_vc_faillures,
	/* event function */    seqg_event_A13A_clearance_status_0_vc_faillures,
	/* entry function */    seqg_entry_A13A_clearance_status_0_vc_faillures,
	/* exit function */     seqg_exit_A13A_clearance_status_0_vc_faillures,
	/* event mask array */  seqg_mask_A13A_clearance_status_0_vc_faillures,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "A13A_clearance_status",
	/* states */            seqg_states_A13A_clearance_status,
	/* number of states */  9
	},
};

/* Program table (global) */
seqProgram a13aClearanceSNC = {
	/* magic number */      2002001,
	/* program name */      "a13aClearanceSNC",
	/* channels */          seqg_chans,
	/* num. channels */     7,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 166 "../a13aClearanceSNC.stt"
static void initVault(SS_ID seqg_env)
{
# line 167 "../a13aClearanceSNC.stt"
	A13A_INIT = TRUE;
# line 168 "../a13aClearanceSNC.stt"
	A13A_OLD_FAIL_COND = A13A_FAIL_COND;
# line 169 "../a13aClearanceSNC.stt"
	not_cleared(A13A_CLR_STATS);
# line 170 "../a13aClearanceSNC.stt"
	report_error(A13A_INTLCK_STATS, 54);
# line 171 "../a13aClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 3/*A13A_INIT*/, SYNC, DEFAULT_TIMEOUT);
# line 172 "../a13aClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*A13A_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 173 "../a13aClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*A13A_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 176 "../a13aClearanceSNC.stt"
static void A13A_update_failed(SS_ID seqg_env, short report)
{
# line 178 "../a13aClearanceSNC.stt"
	clear_failed(A13A_CLR_STATS);
# line 179 "../a13aClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*A13A_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 180 "../a13aClearanceSNC.stt"
	report_error(A13A_INTLCK_STATS, report);
# line 181 "../a13aClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*A13A_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 182 "../a13aClearanceSNC.stt"
	printf("%s%s%s\n", ERROR, A13A_INTLCK_STATS, DEF);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 185 "../a13aClearanceSNC.stt"
static void A13A_update_report(SS_ID seqg_env, short intlck)
{
# line 186 "../a13aClearanceSNC.stt"
	report_error(A13A_INTLCK_STATS, intlck);
# line 187 "../a13aClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*A13A_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 190 "../a13aClearanceSNC.stt"
static void A13A_status(SS_ID seqg_env)
{
# line 192 "../a13aClearanceSNC.stt"
	cleared(A13A_CLR_STATS);
# line 193 "../a13aClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*A13A_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 194 "../a13aClearanceSNC.stt"
	report_error(A13A_INTLCK_STATS, 54);
# line 195 "../a13aClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*A13A_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 198 "../a13aClearanceSNC.stt"
static void A13A_clear_underway(SS_ID seqg_env)
{
# line 200 "../a13aClearanceSNC.stt"
	clear_underway(A13A_CLR_STATS);
# line 201 "../a13aClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*A13A_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

/* Register sequencer commands and program */
#include "epicsExport.h"
static void a13aClearanceSNCRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&a13aClearanceSNC);
}
epicsExportRegistrar(a13aClearanceSNCRegistrar);
