/* C code for program iblClearanceSNC, generated by snc from ../iblClearanceSNC.stt */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 3 "../iblClearanceSNC.stt"

#include "vcs_var_mes.h" // define this here so C functions are seen
	
#define	VCOK       	0
#define FAIL		-1 	
#define	DA13S1OFF	66	
#define	DA13S2OFF	67	
#define B9ON        59
#define B8OFF       65
#define B8ON  		64
#define B7OFF		68  


/* Variable declarations */
# line 16 "../iblClearanceSNC.stt"
static	short IBL_INIT;
# line 17 "../iblClearanceSNC.stt"
static	short IBL_VC;
# line 18 "../iblClearanceSNC.stt"
static	short IBL_W9_STS;
# line 19 "../iblClearanceSNC.stt"
static	short IBL_W8_STS;
# line 20 "../iblClearanceSNC.stt"
static	short IBL_W7_STS;
# line 22 "../iblClearanceSNC.stt"
static	short IBL_FAIL_COND;
# line 23 "../iblClearanceSNC.stt"
static	short IBL_OLD_FAIL_COND;
# line 24 "../iblClearanceSNC.stt"
static	string IBL_CLR_STATS;
# line 25 "../iblClearanceSNC.stt"
static	string IBL_INTLCK_STATS;
# line 26 "../iblClearanceSNC.stt"
static	short released;


/* Function declarations */
# line 203 "../iblClearanceSNC.stt"
static void initVault(SS_ID seqg_env);
# line 213 "../iblClearanceSNC.stt"
static void IBL_update_failed(SS_ID seqg_env, short report);
# line 222 "../iblClearanceSNC.stt"
static void IBL_update_report(SS_ID seqg_env, short intlck);
# line 227 "../iblClearanceSNC.stt"
static void IBL_status(SS_ID seqg_env);
# line 235 "../iblClearanceSNC.stt"
static void IBL_clear_underway(SS_ID seqg_env);

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 26 "../iblClearanceSNC.stt"
	static short seqg_initvar_released = FALSE;
	memcpy(&released, &seqg_initvar_released, sizeof(seqg_initvar_released));
	}
}

/****** Code for state "init" in state set "IBL_clearance_status" ******/

/* Event function for state "init" in state set "IBL_clearance_status" */
static seqBool seqg_event_IBL_clearance_status_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 47 "../iblClearanceSNC.stt"
	if (seq_delay(seqg_env, 3.5))
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "IBL_clearance_status" */
static void seqg_action_IBL_clearance_status_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 48 "../iblClearanceSNC.stt"
			initVault(seqg_env);
# line 49 "../iblClearanceSNC.stt"
			printf("%sISOTOPE BEAM LINE INITIALISATION COMPLETED%s\n", OK, DEF);
		}
		return;
	}
}

/****** Code for state "vault_cleared" in state set "IBL_clearance_status" ******/

/* Entry function for state "vault_cleared" in state set "IBL_clearance_status" */
static void seqg_entry_IBL_clearance_status_0_vault_cleared(SS_ID seqg_env)
{
# line 57 "../iblClearanceSNC.stt"
	printf("%sISOTOPE BEAM LINE IN CLEARED STATE%s\n", CLR, DEF);
}

/* Event function for state "vault_cleared" in state set "IBL_clearance_status" */
static seqBool seqg_event_IBL_clearance_status_0_vault_cleared(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 59 "../iblClearanceSNC.stt"
	if (IBL_VC != VCOK)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "vault_cleared" in state set "IBL_clearance_status" */
static void seqg_action_IBL_clearance_status_0_vault_cleared(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "recover_faillure" in state set "IBL_clearance_status" ******/

/* Event function for state "recover_faillure" in state set "IBL_clearance_status" */
static seqBool seqg_event_IBL_clearance_status_0_recover_faillure(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 66 "../iblClearanceSNC.stt"
	if (!IBL_FAIL_COND)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 73 "../iblClearanceSNC.stt"
	if (IBL_FAIL_COND != IBL_OLD_FAIL_COND)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "recover_faillure" in state set "IBL_clearance_status" */
static void seqg_action_IBL_clearance_status_0_recover_faillure(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 67 "../iblClearanceSNC.stt"
			if (!released)
			{
# line 68 "../iblClearanceSNC.stt"
				printf("%sRECOVERING FROM FAILLURE - ENTERING W9 STATE%s\n", OK, DEF);
# line 69 "../iblClearanceSNC.stt"
				released = TRUE;
			}
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "watchman_9_pressed" in state set "IBL_clearance_status" ******/

/* Event function for state "watchman_9_pressed" in state set "IBL_clearance_status" */
static seqBool seqg_event_IBL_clearance_status_0_watchman_9_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 81 "../iblClearanceSNC.stt"
	if (IBL_W9_STS == FAIL)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 85 "../iblClearanceSNC.stt"
	if (IBL_W9_STS == B9ON)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_9_pressed" in state set "IBL_clearance_status" */
static void seqg_action_IBL_clearance_status_0_watchman_9_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 82 "../iblClearanceSNC.stt"
			IBL_OLD_FAIL_COND = IBL_FAIL_COND;
		}
		return;
	case 1:
		{
# line 86 "../iblClearanceSNC.stt"
			IBL_clear_underway(seqg_env);
# line 87 "../iblClearanceSNC.stt"
			IBL_update_report(seqg_env, B9ON);
		}
		return;
	}
}

/****** Code for state "watchman_9_released" in state set "IBL_clearance_status" ******/

/* Event function for state "watchman_9_released" in state set "IBL_clearance_status" */
static seqBool seqg_event_IBL_clearance_status_0_watchman_9_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 93 "../iblClearanceSNC.stt"
	if (IBL_W9_STS == FAIL)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 97 "../iblClearanceSNC.stt"
	if (IBL_W9_STS != B9ON)
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_9_released" in state set "IBL_clearance_status" */
static void seqg_action_IBL_clearance_status_0_watchman_9_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 98 "../iblClearanceSNC.stt"
			IBL_update_report(seqg_env, B8OFF);
		}
		return;
	}
}

/****** Code for state "watchman_8_pressed" in state set "IBL_clearance_status" ******/

/* Event function for state "watchman_8_pressed" in state set "IBL_clearance_status" */
static seqBool seqg_event_IBL_clearance_status_0_watchman_8_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 104 "../iblClearanceSNC.stt"
	if (IBL_W9_STS == FAIL)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 109 "../iblClearanceSNC.stt"
	if (IBL_W8_STS == B8ON)
	{
		*seqg_pnst = 6;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_8_pressed" in state set "IBL_clearance_status" */
static void seqg_action_IBL_clearance_status_0_watchman_8_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 110 "../iblClearanceSNC.stt"
			IBL_update_report(seqg_env, B8ON);
		}
		return;
	}
}

/****** Code for state "watchman_8_released" in state set "IBL_clearance_status" ******/

/* Event function for state "watchman_8_released" in state set "IBL_clearance_status" */
static seqBool seqg_event_IBL_clearance_status_0_watchman_8_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 116 "../iblClearanceSNC.stt"
	if (IBL_W9_STS == FAIL)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 120 "../iblClearanceSNC.stt"
	if (IBL_W8_STS != B8ON)
	{
		*seqg_pnst = 8;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_8_released" in state set "IBL_clearance_status" */
static void seqg_action_IBL_clearance_status_0_watchman_8_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "watchman_7_pressed" in state set "IBL_clearance_status" ******/

/* Event function for state "watchman_7_pressed" in state set "IBL_clearance_status" */
static seqBool seqg_event_IBL_clearance_status_0_watchman_7_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 128 "../iblClearanceSNC.stt"
	if (IBL_W9_STS == FAIL)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 137 "../iblClearanceSNC.stt"
	if (!IBL_W7_STS)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_7_pressed" in state set "IBL_clearance_status" */
static void seqg_action_IBL_clearance_status_0_watchman_7_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 139 "../iblClearanceSNC.stt"
			IBL_status(seqg_env);
		}
		return;
	}
}

/****** Code for state "door_a13_closed" in state set "IBL_clearance_status" ******/

/* Event function for state "door_a13_closed" in state set "IBL_clearance_status" */
static seqBool seqg_event_IBL_clearance_status_0_door_a13_closed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 145 "../iblClearanceSNC.stt"
	if (IBL_W9_STS == FAIL)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 149 "../iblClearanceSNC.stt"
	if (IBL_W7_STS == DA13S1OFF)
	{
		*seqg_pnst = 8;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 153 "../iblClearanceSNC.stt"
	if (IBL_W7_STS == DA13S2OFF)
	{
		*seqg_pnst = 8;
		*seqg_ptrn = 2;
		return TRUE;
	}
	if (TRUE)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 3;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "door_a13_closed" in state set "IBL_clearance_status" */
static void seqg_action_IBL_clearance_status_0_door_a13_closed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 150 "../iblClearanceSNC.stt"
			IBL_update_report(seqg_env, DA13S1OFF);
		}
		return;
	case 2:
		{
# line 154 "../iblClearanceSNC.stt"
			IBL_update_report(seqg_env, DA13S2OFF);
		}
		return;
	case 3:
		{
# line 158 "../iblClearanceSNC.stt"
			IBL_update_report(seqg_env, B7OFF);
		}
		return;
	}
}

/****** Code for state "clearance_faillures" in state set "IBL_clearance_status" ******/

/* Entry function for state "clearance_faillures" in state set "IBL_clearance_status" */
static void seqg_entry_IBL_clearance_status_0_clearance_faillures(SS_ID seqg_env)
{
# line 167 "../iblClearanceSNC.stt"
	printf("IBL CLEARANCE FAILURE CONDITION: ");
# line 168 "../iblClearanceSNC.stt"
	released = FALSE;
# line 169 "../iblClearanceSNC.stt"
	IBL_OLD_FAIL_COND = IBL_FAIL_COND;
}

/* Exit function for state "clearance_faillures" in state set "IBL_clearance_status" */
static void seqg_exit_IBL_clearance_status_0_clearance_faillures(SS_ID seqg_env)
{
# line 178 "../iblClearanceSNC.stt"
	IBL_OLD_FAIL_COND = IBL_FAIL_COND;
}

/* Event function for state "clearance_faillures" in state set "IBL_clearance_status" */
static seqBool seqg_event_IBL_clearance_status_0_clearance_faillures(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "clearance_faillures" in state set "IBL_clearance_status" */
static void seqg_action_IBL_clearance_status_0_clearance_faillures(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 174 "../iblClearanceSNC.stt"
			IBL_update_failed(seqg_env, IBL_FAIL_COND);
		}
		return;
	}
}

/****** Code for state "vc_faillures" in state set "IBL_clearance_status" ******/

/* Entry function for state "vc_faillures" in state set "IBL_clearance_status" */
static void seqg_entry_IBL_clearance_status_0_vc_faillures(SS_ID seqg_env)
{
# line 187 "../iblClearanceSNC.stt"
	printf("IBL LOW CLEAR FAILURE CONDITION: ");
# line 188 "../iblClearanceSNC.stt"
	released = FALSE;
}

/* Exit function for state "vc_faillures" in state set "IBL_clearance_status" */
static void seqg_exit_IBL_clearance_status_0_vc_faillures(SS_ID seqg_env)
{
# line 198 "../iblClearanceSNC.stt"
	IBL_OLD_FAIL_COND = IBL_FAIL_COND;
}

/* Event function for state "vc_faillures" in state set "IBL_clearance_status" */
static seqBool seqg_event_IBL_clearance_status_0_vc_faillures(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "vc_faillures" in state set "IBL_clearance_status" */
static void seqg_action_IBL_clearance_status_0_vc_faillures(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 194 "../iblClearanceSNC.stt"
			IBL_update_failed(seqg_env, IBL_VC);
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{SYS}:IBL-CLR-STATS", (size_t)&IBL_CLR_STATS, "IBL_CLR_STATS", P_STRING, 1, 1, 0, 0, 0, 0},
	{"{SYS}:IBL-INTLCK-STATS", (size_t)&IBL_INTLCK_STATS, "IBL_INTLCK_STATS", P_STRING, 1, 2, 0, 0, 0, 0},
	{"{SYS}:IBL-VC", (size_t)&IBL_VC, "IBL_VC", P_SHORT, 1, 3, 0, 1, 0, 0},
	{"{SYS}:IBL-INIT", (size_t)&IBL_INIT, "IBL_INIT", P_SHORT, 1, 4, 0, 0, 0, 0},
	{"{SYS}:IBL-W9-STS", (size_t)&IBL_W9_STS, "IBL_W9_STS", P_SHORT, 1, 5, 0, 1, 0, 0},
	{"{SYS}:IBL-W8-STS", (size_t)&IBL_W8_STS, "IBL_W8_STS", P_SHORT, 1, 6, 0, 1, 0, 0},
	{"{SYS}:IBL-W7-STS", (size_t)&IBL_W7_STS, "IBL_W7_STS", P_SHORT, 1, 7, 0, 1, 0, 0},
	{"{SYS}:IBL-FAIL-COND", (size_t)&IBL_FAIL_COND, "IBL_FAIL_COND", P_SHORT, 1, 8, 0, 1, 0, 0},
};

/* Event masks for state set "IBL_clearance_status" */
static const seqMask seqg_mask_IBL_clearance_status_0_init[] = {
	0x00000000,
};
static const seqMask seqg_mask_IBL_clearance_status_0_vault_cleared[] = {
	0x00000008,
};
static const seqMask seqg_mask_IBL_clearance_status_0_recover_faillure[] = {
	0x00000100,
};
static const seqMask seqg_mask_IBL_clearance_status_0_watchman_9_pressed[] = {
	0x00000020,
};
static const seqMask seqg_mask_IBL_clearance_status_0_watchman_9_released[] = {
	0x00000020,
};
static const seqMask seqg_mask_IBL_clearance_status_0_watchman_8_pressed[] = {
	0x00000060,
};
static const seqMask seqg_mask_IBL_clearance_status_0_watchman_8_released[] = {
	0x00000060,
};
static const seqMask seqg_mask_IBL_clearance_status_0_watchman_7_pressed[] = {
	0x000000a0,
};
static const seqMask seqg_mask_IBL_clearance_status_0_door_a13_closed[] = {
	0x000000a0,
};
static const seqMask seqg_mask_IBL_clearance_status_0_clearance_faillures[] = {
	0x00000000,
};
static const seqMask seqg_mask_IBL_clearance_status_0_vc_faillures[] = {
	0x00000000,
};

/* State table for state set "IBL_clearance_status" */
static seqState seqg_states_IBL_clearance_status[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_IBL_clearance_status_0_init,
	/* event function */    seqg_event_IBL_clearance_status_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_IBL_clearance_status_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "vault_cleared",
	/* action function */   seqg_action_IBL_clearance_status_0_vault_cleared,
	/* event function */    seqg_event_IBL_clearance_status_0_vault_cleared,
	/* entry function */    seqg_entry_IBL_clearance_status_0_vault_cleared,
	/* exit function */     0,
	/* event mask array */  seqg_mask_IBL_clearance_status_0_vault_cleared,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "recover_faillure",
	/* action function */   seqg_action_IBL_clearance_status_0_recover_faillure,
	/* event function */    seqg_event_IBL_clearance_status_0_recover_faillure,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_IBL_clearance_status_0_recover_faillure,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_9_pressed",
	/* action function */   seqg_action_IBL_clearance_status_0_watchman_9_pressed,
	/* event function */    seqg_event_IBL_clearance_status_0_watchman_9_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_IBL_clearance_status_0_watchman_9_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_9_released",
	/* action function */   seqg_action_IBL_clearance_status_0_watchman_9_released,
	/* event function */    seqg_event_IBL_clearance_status_0_watchman_9_released,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_IBL_clearance_status_0_watchman_9_released,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_8_pressed",
	/* action function */   seqg_action_IBL_clearance_status_0_watchman_8_pressed,
	/* event function */    seqg_event_IBL_clearance_status_0_watchman_8_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_IBL_clearance_status_0_watchman_8_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_8_released",
	/* action function */   seqg_action_IBL_clearance_status_0_watchman_8_released,
	/* event function */    seqg_event_IBL_clearance_status_0_watchman_8_released,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_IBL_clearance_status_0_watchman_8_released,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_7_pressed",
	/* action function */   seqg_action_IBL_clearance_status_0_watchman_7_pressed,
	/* event function */    seqg_event_IBL_clearance_status_0_watchman_7_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_IBL_clearance_status_0_watchman_7_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "door_a13_closed",
	/* action function */   seqg_action_IBL_clearance_status_0_door_a13_closed,
	/* event function */    seqg_event_IBL_clearance_status_0_door_a13_closed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_IBL_clearance_status_0_door_a13_closed,
	/* state options */     (0)
	},
	{
	/* state name */        "clearance_faillures",
	/* action function */   seqg_action_IBL_clearance_status_0_clearance_faillures,
	/* event function */    seqg_event_IBL_clearance_status_0_clearance_faillures,
	/* entry function */    seqg_entry_IBL_clearance_status_0_clearance_faillures,
	/* exit function */     seqg_exit_IBL_clearance_status_0_clearance_faillures,
	/* event mask array */  seqg_mask_IBL_clearance_status_0_clearance_faillures,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
	{
	/* state name */        "vc_faillures",
	/* action function */   seqg_action_IBL_clearance_status_0_vc_faillures,
	/* event function */    seqg_event_IBL_clearance_status_0_vc_faillures,
	/* entry function */    seqg_entry_IBL_clearance_status_0_vc_faillures,
	/* exit function */     seqg_exit_IBL_clearance_status_0_vc_faillures,
	/* event mask array */  seqg_mask_IBL_clearance_status_0_vc_faillures,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "IBL_clearance_status",
	/* states */            seqg_states_IBL_clearance_status,
	/* number of states */  11
	},
};

/* Program table (global) */
seqProgram iblClearanceSNC = {
	/* magic number */      2002001,
	/* program name */      "iblClearanceSNC",
	/* channels */          seqg_chans,
	/* num. channels */     8,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 203 "../iblClearanceSNC.stt"
static void initVault(SS_ID seqg_env)
{
# line 204 "../iblClearanceSNC.stt"
	IBL_INIT = TRUE;
# line 205 "../iblClearanceSNC.stt"
	IBL_OLD_FAIL_COND = IBL_FAIL_COND;
# line 206 "../iblClearanceSNC.stt"
	not_cleared(IBL_CLR_STATS);
# line 207 "../iblClearanceSNC.stt"
	report_error(IBL_INTLCK_STATS, 0);
# line 208 "../iblClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 3/*IBL_INIT*/, SYNC, DEFAULT_TIMEOUT);
# line 209 "../iblClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*IBL_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 210 "../iblClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*IBL_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 213 "../iblClearanceSNC.stt"
static void IBL_update_failed(SS_ID seqg_env, short report)
{
# line 215 "../iblClearanceSNC.stt"
	clear_failed(IBL_CLR_STATS);
# line 216 "../iblClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*IBL_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 217 "../iblClearanceSNC.stt"
	report_error(IBL_INTLCK_STATS, report);
# line 218 "../iblClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*IBL_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 219 "../iblClearanceSNC.stt"
	printf("%s%s%s\n", ERROR, IBL_INTLCK_STATS, DEF);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 222 "../iblClearanceSNC.stt"
static void IBL_update_report(SS_ID seqg_env, short intlck)
{
# line 223 "../iblClearanceSNC.stt"
	report_error(IBL_INTLCK_STATS, intlck);
# line 224 "../iblClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*IBL_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 227 "../iblClearanceSNC.stt"
static void IBL_status(SS_ID seqg_env)
{
# line 229 "../iblClearanceSNC.stt"
	cleared(IBL_CLR_STATS);
# line 230 "../iblClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*IBL_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 231 "../iblClearanceSNC.stt"
	report_error(IBL_INTLCK_STATS, 0);
# line 232 "../iblClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*IBL_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 235 "../iblClearanceSNC.stt"
static void IBL_clear_underway(SS_ID seqg_env)
{
# line 237 "../iblClearanceSNC.stt"
	clear_underway(IBL_CLR_STATS);
# line 238 "../iblClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*IBL_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

/* Register sequencer commands and program */
#include "epicsExport.h"
static void iblClearanceSNCRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&iblClearanceSNC);
}
epicsExportRegistrar(iblClearanceSNCRegistrar);
