/* C code for program sscbasClearanceSNC, generated by snc from ../sscbasClearanceSNC.stt */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 3 "../sscbasClearanceSNC.stt"

/*******************************************************************/
#include "vcs_var_mes.h" // define this here so C functions are seen
/*******************************************************************/	
#define	VCOK       	0
#define FAIL		-1
#define	G2OFF       33
#define B1ON        38
#define W1ON        21
#define B2OFF       22
#define B2ON  		36
#define B3OFF		27  
#define B3ON 		37 
#define B4OFF		28  
#define B4ON 		32 
#define W4ON		30  
#define B4_5ON      31
#define B5OFF		29  
#define B5ON 		34
#define B6OFF		35


/* Variable declarations */
# line 25 "../sscbasClearanceSNC.stt"
static	short SSCL_INIT;
# line 26 "../sscbasClearanceSNC.stt"
static	short SSCL_VC;
# line 27 "../sscbasClearanceSNC.stt"
static	short SSC_W1_STS;
# line 28 "../sscbasClearanceSNC.stt"
static	short SSC_W2_STS;
# line 29 "../sscbasClearanceSNC.stt"
static	short SSC_W3_STS;
# line 30 "../sscbasClearanceSNC.stt"
static	short SSC_W4_STS;
# line 31 "../sscbasClearanceSNC.stt"
static	short SSC_W5_STS;
# line 32 "../sscbasClearanceSNC.stt"
static	short SSC_W6_STS;
# line 33 "../sscbasClearanceSNC.stt"
static	short SSCL_FAIL_COND;
# line 34 "../sscbasClearanceSNC.stt"
static	short SSCL_OLD_FAIL_COND;
# line 35 "../sscbasClearanceSNC.stt"
static	string SSCL_CLR_STATS;
# line 36 "../sscbasClearanceSNC.stt"
static	string SSCL_INTLCK_STATS;
# line 37 "../sscbasClearanceSNC.stt"
static	short ssclUpdate;


/* Function declarations */
# line 295 "../sscbasClearanceSNC.stt"
static void initVault(SS_ID seqg_env);
# line 304 "../sscbasClearanceSNC.stt"
static void SSCL_update_failed(SS_ID seqg_env, short report);
# line 313 "../sscbasClearanceSNC.stt"
static void SSCL_update_report(SS_ID seqg_env, short intlck);
# line 318 "../sscbasClearanceSNC.stt"
static void SSCL_status(SS_ID seqg_env);
# line 326 "../sscbasClearanceSNC.stt"
static void SSCL_clear_underway(SS_ID seqg_env);

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 37 "../sscbasClearanceSNC.stt"
	static short seqg_initvar_ssclUpdate = FALSE;
	memcpy(&ssclUpdate, &seqg_initvar_ssclUpdate, sizeof(seqg_initvar_ssclUpdate));
	}
}

/****** Code for state "init" in state set "SSCL_clearance_status" ******/

/* Event function for state "init" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 64 "../sscbasClearanceSNC.stt"
	if (seq_delay(seqg_env, 1.5))
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 65 "../sscbasClearanceSNC.stt"
			initVault(seqg_env);
# line 66 "../sscbasClearanceSNC.stt"
			printf("%sSSC LOW INITIALISATION COMPLETED%s\n", OK, DEF);
		}
		return;
	}
}

/****** Code for state "vault_cleared" in state set "SSCL_clearance_status" ******/

/* Entry function for state "vault_cleared" in state set "SSCL_clearance_status" */
static void seqg_entry_SSCL_clearance_status_0_vault_cleared(SS_ID seqg_env)
{
# line 74 "../sscbasClearanceSNC.stt"
	printf("%sSSC LOW IN CLEARED STATE%s\n", CLR, DEF);
}

/* Event function for state "vault_cleared" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_vault_cleared(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 76 "../sscbasClearanceSNC.stt"
	if (SSCL_VC != VCOK)
	{
		*seqg_pnst = 15;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "vault_cleared" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_vault_cleared(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "recover_faillure" in state set "SSCL_clearance_status" ******/

/* Event function for state "recover_faillure" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_recover_faillure(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 83 "../sscbasClearanceSNC.stt"
	if (!SSCL_FAIL_COND)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 90 "../sscbasClearanceSNC.stt"
	if (SSCL_FAIL_COND != SSCL_OLD_FAIL_COND)
	{
		*seqg_pnst = 14;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "recover_faillure" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_recover_faillure(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 84 "../sscbasClearanceSNC.stt"
			if (!ssclUpdate)
			{
# line 85 "../sscbasClearanceSNC.stt"
				printf("%sRECOVERING FROM FAILLURE: ENTERING W1 STATE%s\n", OK, DEF);
# line 86 "../sscbasClearanceSNC.stt"
				ssclUpdate = TRUE;
			}
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "watchman_1_pressed" in state set "SSCL_clearance_status" ******/

/* Event function for state "watchman_1_pressed" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_watchman_1_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 98 "../sscbasClearanceSNC.stt"
	if (SSCL_FAIL_COND != VCOK)
	{
		*seqg_pnst = 14;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 102 "../sscbasClearanceSNC.stt"
	if (!SSC_W1_STS)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_1_pressed" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_watchman_1_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 99 "../sscbasClearanceSNC.stt"
			SSCL_OLD_FAIL_COND = SSCL_FAIL_COND;
		}
		return;
	case 1:
		{
# line 103 "../sscbasClearanceSNC.stt"
			SSCL_update_report(seqg_env, B2OFF);
# line 104 "../sscbasClearanceSNC.stt"
			SSCL_clear_underway(seqg_env);
		}
		return;
	}
}

/****** Code for state "watchman_2_pressed" in state set "SSCL_clearance_status" ******/

/* Event function for state "watchman_2_pressed" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_watchman_2_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 110 "../sscbasClearanceSNC.stt"
	if (SSC_W1_STS == FAIL)
	{
		*seqg_pnst = 14;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 115 "../sscbasClearanceSNC.stt"
	if (SSC_W2_STS == B2ON)
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_2_pressed" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_watchman_2_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 116 "../sscbasClearanceSNC.stt"
			SSCL_update_report(seqg_env, B2ON);
		}
		return;
	}
}

/****** Code for state "watchman_2_released" in state set "SSCL_clearance_status" ******/

/* Event function for state "watchman_2_released" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_watchman_2_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 122 "../sscbasClearanceSNC.stt"
	if (SSC_W1_STS == FAIL)
	{
		*seqg_pnst = 14;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 126 "../sscbasClearanceSNC.stt"
	if (SSC_W2_STS == B3OFF)
	{
		*seqg_pnst = 6;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_2_released" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_watchman_2_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 127 "../sscbasClearanceSNC.stt"
			SSCL_update_report(seqg_env, B3OFF);
		}
		return;
	}
}

/****** Code for state "watchman_3_pressed" in state set "SSCL_clearance_status" ******/

/* Event function for state "watchman_3_pressed" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_watchman_3_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 133 "../sscbasClearanceSNC.stt"
	if (SSC_W1_STS == FAIL)
	{
		*seqg_pnst = 14;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 138 "../sscbasClearanceSNC.stt"
	if (SSC_W3_STS == B3ON)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_3_pressed" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_watchman_3_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 139 "../sscbasClearanceSNC.stt"
			SSCL_update_report(seqg_env, B3ON);
		}
		return;
	}
}

/****** Code for state "watchman_3_released" in state set "SSCL_clearance_status" ******/

/* Event function for state "watchman_3_released" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_watchman_3_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 145 "../sscbasClearanceSNC.stt"
	if (SSC_W1_STS == FAIL)
	{
		*seqg_pnst = 14;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 150 "../sscbasClearanceSNC.stt"
	if (SSC_W3_STS == B4OFF)
	{
		*seqg_pnst = 8;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_3_released" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_watchman_3_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 151 "../sscbasClearanceSNC.stt"
			SSCL_update_report(seqg_env, B4OFF);
		}
		return;
	}
}

/****** Code for state "watchman_4_pressed" in state set "SSCL_clearance_status" ******/

/* Event function for state "watchman_4_pressed" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_watchman_4_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 157 "../sscbasClearanceSNC.stt"
	if (SSC_W1_STS == FAIL)
	{
		*seqg_pnst = 14;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 162 "../sscbasClearanceSNC.stt"
	if (!SSC_W4_STS)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_4_pressed" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_watchman_4_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 164 "../sscbasClearanceSNC.stt"
			SSCL_update_report(seqg_env, B1ON);
		}
		return;
	}
}

/****** Code for state "watchman_1_released" in state set "SSCL_clearance_status" ******/

/* Event function for state "watchman_1_released" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_watchman_1_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 170 "../sscbasClearanceSNC.stt"
	if (SSC_W1_STS == FAIL)
	{
		*seqg_pnst = 14;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 174 "../sscbasClearanceSNC.stt"
	if (SSC_W1_STS == B1ON)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_1_released" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_watchman_1_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 176 "../sscbasClearanceSNC.stt"
			SSCL_update_report(seqg_env, B5OFF);
		}
		return;
	}
}

/****** Code for state "watchman_5_pressed" in state set "SSCL_clearance_status" ******/

/* Event function for state "watchman_5_pressed" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_watchman_5_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 182 "../sscbasClearanceSNC.stt"
	if (SSC_W1_STS == FAIL)
	{
		*seqg_pnst = 14;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 187 "../sscbasClearanceSNC.stt"
	if (!SSC_W5_STS)
	{
		*seqg_pnst = 12;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_5_pressed" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_watchman_5_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 189 "../sscbasClearanceSNC.stt"
			SSCL_update_report(seqg_env, B4_5ON);
		}
		return;
	}
}

/****** Code for state "watchman_5_released" in state set "SSCL_clearance_status" ******/

/* Event function for state "watchman_5_released" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_watchman_5_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 195 "../sscbasClearanceSNC.stt"
	if (SSC_W1_STS == FAIL)
	{
		*seqg_pnst = 14;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 199 "../sscbasClearanceSNC.stt"
	if (SSC_W5_STS != B5ON)
	{
		*seqg_pnst = 12;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_5_released" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_watchman_5_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "watchman_4_released" in state set "SSCL_clearance_status" ******/

/* Event function for state "watchman_4_released" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_watchman_4_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 207 "../sscbasClearanceSNC.stt"
	if (SSC_W1_STS == FAIL)
	{
		*seqg_pnst = 14;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 212 "../sscbasClearanceSNC.stt"
	if (!SSC_W5_STS)
	{
		*seqg_pnst = 12;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 216 "../sscbasClearanceSNC.stt"
	if (SSC_W5_STS == B5ON)
	{
		*seqg_pnst = 11;
		*seqg_ptrn = 2;
		return TRUE;
	}
# line 221 "../sscbasClearanceSNC.stt"
	if (SSC_W5_STS == B4ON)
	{
		*seqg_pnst = 12;
		*seqg_ptrn = 3;
		return TRUE;
	}
	if (TRUE)
	{
		*seqg_pnst = 13;
		*seqg_ptrn = 4;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_4_released" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_watchman_4_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	case 2:
		{
# line 217 "../sscbasClearanceSNC.stt"
			SSCL_update_report(seqg_env, B5ON);
		}
		return;
	case 3:
		{
# line 222 "../sscbasClearanceSNC.stt"
			SSCL_update_report(seqg_env, B4ON);
		}
		return;
	case 4:
		{
		}
		return;
	}
}

/****** Code for state "watchman_6_pressed" in state set "SSCL_clearance_status" ******/

/* Event function for state "watchman_6_pressed" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_watchman_6_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 233 "../sscbasClearanceSNC.stt"
	if (SSC_W1_STS == FAIL)
	{
		*seqg_pnst = 14;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 238 "../sscbasClearanceSNC.stt"
	if (SSC_W6_STS == G2OFF)
	{
		*seqg_pnst = 13;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 244 "../sscbasClearanceSNC.stt"
	if (SSC_W6_STS == B6OFF)
	{
		*seqg_pnst = 13;
		*seqg_ptrn = 2;
		return TRUE;
	}
# line 249 "../sscbasClearanceSNC.stt"
	if (!SSC_W6_STS)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 3;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_6_pressed" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_watchman_6_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 240 "../sscbasClearanceSNC.stt"
			SSCL_update_report(seqg_env, G2OFF);
		}
		return;
	case 2:
		{
# line 245 "../sscbasClearanceSNC.stt"
			SSCL_update_report(seqg_env, B6OFF);
		}
		return;
	case 3:
		{
# line 251 "../sscbasClearanceSNC.stt"
			SSCL_status(seqg_env);
		}
		return;
	}
}

/****** Code for state "clearance_faillures" in state set "SSCL_clearance_status" ******/

/* Entry function for state "clearance_faillures" in state set "SSCL_clearance_status" */
static void seqg_entry_SSCL_clearance_status_0_clearance_faillures(SS_ID seqg_env)
{
# line 260 "../sscbasClearanceSNC.stt"
	printf("SSC LOW CLEARANCE FAILURE CONDITION: ");
# line 261 "../sscbasClearanceSNC.stt"
	ssclUpdate = FALSE;
}

/* Exit function for state "clearance_faillures" in state set "SSCL_clearance_status" */
static void seqg_exit_SSCL_clearance_status_0_clearance_faillures(SS_ID seqg_env)
{
# line 270 "../sscbasClearanceSNC.stt"
	SSCL_OLD_FAIL_COND = SSCL_FAIL_COND;
}

/* Event function for state "clearance_faillures" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_clearance_faillures(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "clearance_faillures" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_clearance_faillures(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 266 "../sscbasClearanceSNC.stt"
			SSCL_update_failed(seqg_env, SSCL_FAIL_COND);
		}
		return;
	}
}

/****** Code for state "vc_faillures" in state set "SSCL_clearance_status" ******/

/* Entry function for state "vc_faillures" in state set "SSCL_clearance_status" */
static void seqg_entry_SSCL_clearance_status_0_vc_faillures(SS_ID seqg_env)
{
# line 280 "../sscbasClearanceSNC.stt"
	printf("SSC LOW CLEAR FAILURE CONDITION: ");
# line 281 "../sscbasClearanceSNC.stt"
	ssclUpdate = FALSE;
}

/* Exit function for state "vc_faillures" in state set "SSCL_clearance_status" */
static void seqg_exit_SSCL_clearance_status_0_vc_faillures(SS_ID seqg_env)
{
# line 290 "../sscbasClearanceSNC.stt"
	SSCL_OLD_FAIL_COND = SSCL_FAIL_COND;
}

/* Event function for state "vc_faillures" in state set "SSCL_clearance_status" */
static seqBool seqg_event_SSCL_clearance_status_0_vc_faillures(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "vc_faillures" in state set "SSCL_clearance_status" */
static void seqg_action_SSCL_clearance_status_0_vc_faillures(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 286 "../sscbasClearanceSNC.stt"
			SSCL_update_failed(seqg_env, SSCL_VC);
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{SYS}:SSCL-CLR-STATS", (size_t)&SSCL_CLR_STATS, "SSCL_CLR_STATS", P_STRING, 1, 1, 0, 0, 0, 0},
	{"{SYS}:SSCL-INTLCK-STATS", (size_t)&SSCL_INTLCK_STATS, "SSCL_INTLCK_STATS", P_STRING, 1, 2, 0, 0, 0, 0},
	{"{SYS}:SSCL-VC", (size_t)&SSCL_VC, "SSCL_VC", P_SHORT, 1, 3, 0, 1, 0, 0},
	{"{SYS}:SSCL-INIT", (size_t)&SSCL_INIT, "SSCL_INIT", P_SHORT, 1, 4, 0, 0, 0, 0},
	{"{SYS}:SSC-W1-STS", (size_t)&SSC_W1_STS, "SSC_W1_STS", P_SHORT, 1, 5, 0, 1, 0, 0},
	{"{SYS}:SSC-W2-STS", (size_t)&SSC_W2_STS, "SSC_W2_STS", P_SHORT, 1, 6, 0, 1, 0, 0},
	{"{SYS}:SSC-W3-STS", (size_t)&SSC_W3_STS, "SSC_W3_STS", P_SHORT, 1, 7, 0, 1, 0, 0},
	{"{SYS}:SSC-W4-STS", (size_t)&SSC_W4_STS, "SSC_W4_STS", P_SHORT, 1, 8, 0, 1, 0, 0},
	{"{SYS}:SSC-W5-STS", (size_t)&SSC_W5_STS, "SSC_W5_STS", P_SHORT, 1, 9, 0, 1, 0, 0},
	{"{SYS}:SSC-W6-STS", (size_t)&SSC_W6_STS, "SSC_W6_STS", P_SHORT, 1, 10, 0, 1, 0, 0},
	{"{SYS}:SSCL-FAIL-COND", (size_t)&SSCL_FAIL_COND, "SSCL_FAIL_COND", P_SHORT, 1, 11, 0, 1, 0, 0},
};

/* Event masks for state set "SSCL_clearance_status" */
static const seqMask seqg_mask_SSCL_clearance_status_0_init[] = {
	0x00000000,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_vault_cleared[] = {
	0x00000008,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_recover_faillure[] = {
	0x00000800,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_watchman_1_pressed[] = {
	0x00000820,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_watchman_2_pressed[] = {
	0x00000060,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_watchman_2_released[] = {
	0x00000060,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_watchman_3_pressed[] = {
	0x000000a0,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_watchman_3_released[] = {
	0x000000a0,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_watchman_4_pressed[] = {
	0x00000120,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_watchman_1_released[] = {
	0x00000020,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_watchman_5_pressed[] = {
	0x00000220,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_watchman_5_released[] = {
	0x00000220,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_watchman_4_released[] = {
	0x00000220,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_watchman_6_pressed[] = {
	0x00000420,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_clearance_faillures[] = {
	0x00000000,
};
static const seqMask seqg_mask_SSCL_clearance_status_0_vc_faillures[] = {
	0x00000000,
};

/* State table for state set "SSCL_clearance_status" */
static seqState seqg_states_SSCL_clearance_status[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_SSCL_clearance_status_0_init,
	/* event function */    seqg_event_SSCL_clearance_status_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "vault_cleared",
	/* action function */   seqg_action_SSCL_clearance_status_0_vault_cleared,
	/* event function */    seqg_event_SSCL_clearance_status_0_vault_cleared,
	/* entry function */    seqg_entry_SSCL_clearance_status_0_vault_cleared,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_vault_cleared,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "recover_faillure",
	/* action function */   seqg_action_SSCL_clearance_status_0_recover_faillure,
	/* event function */    seqg_event_SSCL_clearance_status_0_recover_faillure,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_recover_faillure,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_1_pressed",
	/* action function */   seqg_action_SSCL_clearance_status_0_watchman_1_pressed,
	/* event function */    seqg_event_SSCL_clearance_status_0_watchman_1_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_watchman_1_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_2_pressed",
	/* action function */   seqg_action_SSCL_clearance_status_0_watchman_2_pressed,
	/* event function */    seqg_event_SSCL_clearance_status_0_watchman_2_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_watchman_2_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_2_released",
	/* action function */   seqg_action_SSCL_clearance_status_0_watchman_2_released,
	/* event function */    seqg_event_SSCL_clearance_status_0_watchman_2_released,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_watchman_2_released,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_3_pressed",
	/* action function */   seqg_action_SSCL_clearance_status_0_watchman_3_pressed,
	/* event function */    seqg_event_SSCL_clearance_status_0_watchman_3_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_watchman_3_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_3_released",
	/* action function */   seqg_action_SSCL_clearance_status_0_watchman_3_released,
	/* event function */    seqg_event_SSCL_clearance_status_0_watchman_3_released,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_watchman_3_released,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_4_pressed",
	/* action function */   seqg_action_SSCL_clearance_status_0_watchman_4_pressed,
	/* event function */    seqg_event_SSCL_clearance_status_0_watchman_4_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_watchman_4_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_1_released",
	/* action function */   seqg_action_SSCL_clearance_status_0_watchman_1_released,
	/* event function */    seqg_event_SSCL_clearance_status_0_watchman_1_released,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_watchman_1_released,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_5_pressed",
	/* action function */   seqg_action_SSCL_clearance_status_0_watchman_5_pressed,
	/* event function */    seqg_event_SSCL_clearance_status_0_watchman_5_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_watchman_5_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_5_released",
	/* action function */   seqg_action_SSCL_clearance_status_0_watchman_5_released,
	/* event function */    seqg_event_SSCL_clearance_status_0_watchman_5_released,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_watchman_5_released,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_4_released",
	/* action function */   seqg_action_SSCL_clearance_status_0_watchman_4_released,
	/* event function */    seqg_event_SSCL_clearance_status_0_watchman_4_released,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_watchman_4_released,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_6_pressed",
	/* action function */   seqg_action_SSCL_clearance_status_0_watchman_6_pressed,
	/* event function */    seqg_event_SSCL_clearance_status_0_watchman_6_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_watchman_6_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "clearance_faillures",
	/* action function */   seqg_action_SSCL_clearance_status_0_clearance_faillures,
	/* event function */    seqg_event_SSCL_clearance_status_0_clearance_faillures,
	/* entry function */    seqg_entry_SSCL_clearance_status_0_clearance_faillures,
	/* exit function */     seqg_exit_SSCL_clearance_status_0_clearance_faillures,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_clearance_faillures,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
	{
	/* state name */        "vc_faillures",
	/* action function */   seqg_action_SSCL_clearance_status_0_vc_faillures,
	/* event function */    seqg_event_SSCL_clearance_status_0_vc_faillures,
	/* entry function */    seqg_entry_SSCL_clearance_status_0_vc_faillures,
	/* exit function */     seqg_exit_SSCL_clearance_status_0_vc_faillures,
	/* event mask array */  seqg_mask_SSCL_clearance_status_0_vc_faillures,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "SSCL_clearance_status",
	/* states */            seqg_states_SSCL_clearance_status,
	/* number of states */  16
	},
};

/* Program table (global) */
seqProgram sscbasClearanceSNC = {
	/* magic number */      2002001,
	/* program name */      "sscbasClearanceSNC",
	/* channels */          seqg_chans,
	/* num. channels */     11,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 295 "../sscbasClearanceSNC.stt"
static void initVault(SS_ID seqg_env)
{
# line 296 "../sscbasClearanceSNC.stt"
	SSCL_INIT = TRUE;
# line 297 "../sscbasClearanceSNC.stt"
	not_cleared(SSCL_CLR_STATS);
# line 298 "../sscbasClearanceSNC.stt"
	report_error(SSCL_INTLCK_STATS, 0);
# line 299 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 3/*SSCL_INIT*/, SYNC, DEFAULT_TIMEOUT);
# line 300 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*SSCL_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 301 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SSCL_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 304 "../sscbasClearanceSNC.stt"
static void SSCL_update_failed(SS_ID seqg_env, short report)
{
# line 306 "../sscbasClearanceSNC.stt"
	clear_failed(SSCL_CLR_STATS);
# line 307 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*SSCL_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 308 "../sscbasClearanceSNC.stt"
	report_error(SSCL_INTLCK_STATS, report);
# line 309 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SSCL_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 310 "../sscbasClearanceSNC.stt"
	printf("%s%s%s\n", ERROR, SSCL_INTLCK_STATS, DEF);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 313 "../sscbasClearanceSNC.stt"
static void SSCL_update_report(SS_ID seqg_env, short intlck)
{
# line 314 "../sscbasClearanceSNC.stt"
	report_error(SSCL_INTLCK_STATS, intlck);
# line 315 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SSCL_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 318 "../sscbasClearanceSNC.stt"
static void SSCL_status(SS_ID seqg_env)
{
# line 320 "../sscbasClearanceSNC.stt"
	cleared(SSCL_CLR_STATS);
# line 321 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*SSCL_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 322 "../sscbasClearanceSNC.stt"
	report_error(SSCL_INTLCK_STATS, 0);
# line 323 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SSCL_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 326 "../sscbasClearanceSNC.stt"
static void SSCL_clear_underway(SS_ID seqg_env)
{
# line 328 "../sscbasClearanceSNC.stt"
	clear_underway(SSCL_CLR_STATS);
# line 329 "../sscbasClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*SSCL_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

/* Register sequencer commands and program */
#include "epicsExport.h"
static void sscbasClearanceSNCRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&sscbasClearanceSNC);
}
epicsExportRegistrar(sscbasClearanceSNCRegistrar);
