/* C code for program spc1gfClearanceSNC, generated by snc from ../spc1gfClearanceSNC.stt */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 3 "../spc1gfClearanceSNC.stt"

#include "vcs_var_mes.h" // define this here so C functions are seen
	
#define	STOK       	0
#define FAIL		-1
#define WFVC		55
#define B40ON		173
#define B41OFF		175
#define G7OFF 		180
#define SPC1GFPNK	183 


/* Variable declarations */
# line 15 "../spc1gfClearanceSNC.stt"
static	short SPC1GF_VC;
# line 16 "../spc1gfClearanceSNC.stt"
static	short SPC1GF_W40_STS;
# line 17 "../spc1gfClearanceSNC.stt"
static	short SPC1GF_W41_STS;
# line 18 "../spc1gfClearanceSNC.stt"
static	short SPC1GF_RST_OUTS;
# line 19 "../spc1gfClearanceSNC.stt"
static	short SPC1GF_FAIL_COND;
# line 20 "../spc1gfClearanceSNC.stt"
static	short SPC1GF_PNK;
# line 21 "../spc1gfClearanceSNC.stt"
static	string SPC1GF_CLR_STATS;
# line 22 "../spc1gfClearanceSNC.stt"
static	string SPC1GF_INTLCK_STATS;
# line 25 "../spc1gfClearanceSNC.stt"
static	short SPC1GF_OLD_FAIL_COND;
# line 26 "../spc1gfClearanceSNC.stt"
static	short SPC1GF_FAILED_RST;


/* Function declarations */
# line 198 "../spc1gfClearanceSNC.stt"
static void initVault(SS_ID seqg_env);
# line 211 "../spc1gfClearanceSNC.stt"
static void resetVault(SS_ID seqg_env);
# line 216 "../spc1gfClearanceSNC.stt"
static void SPC1GF_update_failed(SS_ID seqg_env, short report);
# line 225 "../spc1gfClearanceSNC.stt"
static void SPC1GF_update_report(SS_ID seqg_env, short intlck);
# line 230 "../spc1gfClearanceSNC.stt"
static void SPC1GF_status(SS_ID seqg_env);
# line 238 "../spc1gfClearanceSNC.stt"
static void SPC1GF_clear_underway(SS_ID seqg_env);

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 26 "../spc1gfClearanceSNC.stt"
	static short seqg_initvar_SPC1GF_FAILED_RST = FALSE;
	memcpy(&SPC1GF_FAILED_RST, &seqg_initvar_SPC1GF_FAILED_RST, sizeof(seqg_initvar_SPC1GF_FAILED_RST));
	}
}

/****** Code for state "init" in state set "SPC1GF_clearance_status" ******/

/* Event function for state "init" in state set "SPC1GF_clearance_status" */
static seqBool seqg_event_SPC1GF_clearance_status_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 48 "../spc1gfClearanceSNC.stt"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "SPC1GF_clearance_status" */
static void seqg_action_SPC1GF_clearance_status_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 49 "../spc1gfClearanceSNC.stt"
			initVault(seqg_env);
# line 50 "../spc1gfClearanceSNC.stt"
			printf("\n%sSPC1 GROUND-FLOOR VAULT INITIALISATION COMPLETED%s\n", OK, DEF);
		}
		return;
	}
}

/****** Code for state "watchman_40_pressed" in state set "SPC1GF_clearance_status" ******/

/* Event function for state "watchman_40_pressed" in state set "SPC1GF_clearance_status" */
static seqBool seqg_event_SPC1GF_clearance_status_0_watchman_40_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 57 "../spc1gfClearanceSNC.stt"
	if (SPC1GF_FAIL_COND != STOK)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 61 "../spc1gfClearanceSNC.stt"
	if (SPC1GF_W40_STS == WFVC)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 65 "../spc1gfClearanceSNC.stt"
	if (SPC1GF_W40_STS == B40ON)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_40_pressed" in state set "SPC1GF_clearance_status" */
static void seqg_action_SPC1GF_clearance_status_0_watchman_40_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 58 "../spc1gfClearanceSNC.stt"
			SPC1GF_OLD_FAIL_COND = SPC1GF_FAIL_COND;
		}
		return;
	case 1:
		{
		}
		return;
	case 2:
		{
# line 66 "../spc1gfClearanceSNC.stt"
			SPC1GF_clear_underway(seqg_env);
# line 67 "../spc1gfClearanceSNC.stt"
			SPC1GF_update_report(seqg_env, B40ON);
		}
		return;
	}
}

/****** Code for state "clearance_pending" in state set "SPC1GF_clearance_status" ******/

/* Entry function for state "clearance_pending" in state set "SPC1GF_clearance_status" */
static void seqg_entry_SPC1GF_clearance_status_0_clearance_pending(SS_ID seqg_env)
{
# line 76 "../spc1gfClearanceSNC.stt"
	resetVault(seqg_env);
# line 77 "../spc1gfClearanceSNC.stt"
	SPC1GF_update_report(seqg_env, WFVC);
}

/* Event function for state "clearance_pending" in state set "SPC1GF_clearance_status" */
static seqBool seqg_event_SPC1GF_clearance_status_0_clearance_pending(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 80 "../spc1gfClearanceSNC.stt"
	if (SPC1GF_W40_STS != WFVC)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "clearance_pending" in state set "SPC1GF_clearance_status" */
static void seqg_action_SPC1GF_clearance_status_0_clearance_pending(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "watchman_40_released" in state set "SPC1GF_clearance_status" ******/

/* Event function for state "watchman_40_released" in state set "SPC1GF_clearance_status" */
static seqBool seqg_event_SPC1GF_clearance_status_0_watchman_40_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 88 "../spc1gfClearanceSNC.stt"
	if (SPC1GF_FAIL_COND != STOK)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 92 "../spc1gfClearanceSNC.stt"
	if (SPC1GF_W40_STS != B40ON)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_40_released" in state set "SPC1GF_clearance_status" */
static void seqg_action_SPC1GF_clearance_status_0_watchman_40_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "gate_g7_closed" in state set "SPC1GF_clearance_status" ******/

/* Entry function for state "gate_g7_closed" in state set "SPC1GF_clearance_status" */
static void seqg_entry_SPC1GF_clearance_status_0_gate_g7_closed(SS_ID seqg_env)
{
# line 102 "../spc1gfClearanceSNC.stt"
	SPC1GF_update_report(seqg_env, G7OFF);
}

/* Event function for state "gate_g7_closed" in state set "SPC1GF_clearance_status" */
static seqBool seqg_event_SPC1GF_clearance_status_0_gate_g7_closed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 105 "../spc1gfClearanceSNC.stt"
	if (SPC1GF_FAIL_COND != STOK)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 109 "../spc1gfClearanceSNC.stt"
	if (SPC1GF_W41_STS != G7OFF)
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "gate_g7_closed" in state set "SPC1GF_clearance_status" */
static void seqg_action_SPC1GF_clearance_status_0_gate_g7_closed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "watchman_41_pressed" in state set "SPC1GF_clearance_status" ******/

/* Entry function for state "watchman_41_pressed" in state set "SPC1GF_clearance_status" */
static void seqg_entry_SPC1GF_clearance_status_0_watchman_41_pressed(SS_ID seqg_env)
{
# line 118 "../spc1gfClearanceSNC.stt"
	SPC1GF_update_report(seqg_env, B41OFF);
}

/* Event function for state "watchman_41_pressed" in state set "SPC1GF_clearance_status" */
static seqBool seqg_event_SPC1GF_clearance_status_0_watchman_41_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 121 "../spc1gfClearanceSNC.stt"
	if (SPC1GF_FAIL_COND != STOK)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 125 "../spc1gfClearanceSNC.stt"
	if (!SPC1GF_W41_STS)
	{
		*seqg_pnst = 6;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 130 "../spc1gfClearanceSNC.stt"
	if (SPC1GF_W41_STS != B41OFF)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_41_pressed" in state set "SPC1GF_clearance_status" */
static void seqg_action_SPC1GF_clearance_status_0_watchman_41_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 127 "../spc1gfClearanceSNC.stt"
			SPC1GF_status(seqg_env);
		}
		return;
	case 2:
		{
		}
		return;
	}
}

/****** Code for state "vault_cleared" in state set "SPC1GF_clearance_status" ******/

/* Entry function for state "vault_cleared" in state set "SPC1GF_clearance_status" */
static void seqg_entry_SPC1GF_clearance_status_0_vault_cleared(SS_ID seqg_env)
{
# line 138 "../spc1gfClearanceSNC.stt"
	printf("%sSPC1 GROUND-FLOOR VAULT IN CLEARED STATE%s\n", CLR, DEF);
}

/* Event function for state "vault_cleared" in state set "SPC1GF_clearance_status" */
static seqBool seqg_event_SPC1GF_clearance_status_0_vault_cleared(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 140 "../spc1gfClearanceSNC.stt"
	if (SPC1GF_VC != STOK)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "vault_cleared" in state set "SPC1GF_clearance_status" */
static void seqg_action_SPC1GF_clearance_status_0_vault_cleared(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "paniq_faillure" in state set "SPC1GF_clearance_status" ******/

/* Event function for state "paniq_faillure" in state set "SPC1GF_clearance_status" */
static seqBool seqg_event_SPC1GF_clearance_status_0_paniq_faillure(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 147 "../spc1gfClearanceSNC.stt"
	if (SPC1GF_VC != SPC1GFPNK)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 0;
		return TRUE;
	}
	if (TRUE)
	{
		*seqg_pnst = 8;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "paniq_faillure" in state set "SPC1GF_clearance_status" */
static void seqg_action_SPC1GF_clearance_status_0_paniq_faillure(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 152 "../spc1gfClearanceSNC.stt"
			printf("SPC1GF VAULT CLEARED FAILURE CONDITION: ");
# line 153 "../spc1gfClearanceSNC.stt"
			SPC1GF_update_failed(seqg_env, SPC1GFPNK);
		}
		return;
	}
}

/****** Code for state "recover_from_paniq" in state set "SPC1GF_clearance_status" ******/

/* Exit function for state "recover_from_paniq" in state set "SPC1GF_clearance_status" */
static void seqg_exit_SPC1GF_clearance_status_0_recover_from_paniq(SS_ID seqg_env)
{
# line 166 "../spc1gfClearanceSNC.stt"
	SPC1GF_FAILED_RST = FALSE;
}

/* Event function for state "recover_from_paniq" in state set "SPC1GF_clearance_status" */
static seqBool seqg_event_SPC1GF_clearance_status_0_recover_from_paniq(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 161 "../spc1gfClearanceSNC.stt"
	if (!SPC1GF_PNK)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "recover_from_paniq" in state set "SPC1GF_clearance_status" */
static void seqg_action_SPC1GF_clearance_status_0_recover_from_paniq(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "clearance_faillures" in state set "SPC1GF_clearance_status" ******/

/* Entry function for state "clearance_faillures" in state set "SPC1GF_clearance_status" */
static void seqg_entry_SPC1GF_clearance_status_0_clearance_faillures(SS_ID seqg_env)
{
# line 175 "../spc1gfClearanceSNC.stt"
	printf("SPC1 GROUND-FLOOR CLEARANCE FAILURE CONDITION: ");
# line 176 "../spc1gfClearanceSNC.stt"
	SPC1GF_FAILED_RST = FALSE;
# line 177 "../spc1gfClearanceSNC.stt"
	SPC1GF_OLD_FAIL_COND = SPC1GF_FAIL_COND;
# line 178 "../spc1gfClearanceSNC.stt"
	SPC1GF_update_failed(seqg_env, SPC1GF_FAIL_COND == FAIL ? STOK : SPC1GF_FAIL_COND);
}

/* Event function for state "clearance_faillures" in state set "SPC1GF_clearance_status" */
static seqBool seqg_event_SPC1GF_clearance_status_0_clearance_faillures(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "clearance_faillures" in state set "SPC1GF_clearance_status" */
static void seqg_action_SPC1GF_clearance_status_0_clearance_faillures(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "recover_from_faillure" in state set "SPC1GF_clearance_status" ******/

/* Event function for state "recover_from_faillure" in state set "SPC1GF_clearance_status" */
static seqBool seqg_event_SPC1GF_clearance_status_0_recover_from_faillure(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 188 "../spc1gfClearanceSNC.stt"
	if (!SPC1GF_FAIL_COND)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 192 "../spc1gfClearanceSNC.stt"
	if (SPC1GF_FAIL_COND != SPC1GF_OLD_FAIL_COND)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "recover_from_faillure" in state set "SPC1GF_clearance_status" */
static void seqg_action_SPC1GF_clearance_status_0_recover_from_faillure(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 189 "../spc1gfClearanceSNC.stt"
			printf("%sSPC1 GROUND-FLOOR RECOVERING FROM FAILLURE : ENTERING W9 STATE%s\n", OK, DEF);
		}
		return;
	case 1:
		{
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{SYS}:RST-SPC1GF.PROC", (size_t)&SPC1GF_RST_OUTS, "SPC1GF_RST_OUTS", P_SHORT, 1, 1, 0, 0, 0, 0},
	{"{SYS}:SPC1GF-CLR-STATS", (size_t)&SPC1GF_CLR_STATS, "SPC1GF_CLR_STATS", P_STRING, 1, 2, 0, 0, 0, 0},
	{"{SYS}:SPC1GF-INTLCK-STATS", (size_t)&SPC1GF_INTLCK_STATS, "SPC1GF_INTLCK_STATS", P_STRING, 1, 3, 0, 0, 0, 0},
	{"{SYS}:SPC1GF-VC", (size_t)&SPC1GF_VC, "SPC1GF_VC", P_SHORT, 1, 4, 0, 1, 0, 0},
	{"{SYS}:SPC1-W40-STS", (size_t)&SPC1GF_W40_STS, "SPC1GF_W40_STS", P_SHORT, 1, 5, 0, 1, 0, 0},
	{"{SYS}:SPC1-W41-STS", (size_t)&SPC1GF_W41_STS, "SPC1GF_W41_STS", P_SHORT, 1, 6, 0, 1, 0, 0},
	{"{SYS}:SPC1GF-FAIL-COND", (size_t)&SPC1GF_FAIL_COND, "SPC1GF_FAIL_COND", P_SHORT, 1, 7, 0, 1, 0, 0},
	{"{SYS}:SPC1GF-PNK", (size_t)&SPC1GF_PNK, "SPC1GF_PNK", P_SHORT, 1, 8, 0, 1, 0, 0},
};

/* Event masks for state set "SPC1GF_clearance_status" */
static const seqMask seqg_mask_SPC1GF_clearance_status_0_init[] = {
	0x00000000,
};
static const seqMask seqg_mask_SPC1GF_clearance_status_0_watchman_40_pressed[] = {
	0x000000a0,
};
static const seqMask seqg_mask_SPC1GF_clearance_status_0_clearance_pending[] = {
	0x00000020,
};
static const seqMask seqg_mask_SPC1GF_clearance_status_0_watchman_40_released[] = {
	0x000000a0,
};
static const seqMask seqg_mask_SPC1GF_clearance_status_0_gate_g7_closed[] = {
	0x000000c0,
};
static const seqMask seqg_mask_SPC1GF_clearance_status_0_watchman_41_pressed[] = {
	0x000000c0,
};
static const seqMask seqg_mask_SPC1GF_clearance_status_0_vault_cleared[] = {
	0x00000010,
};
static const seqMask seqg_mask_SPC1GF_clearance_status_0_paniq_faillure[] = {
	0x00000010,
};
static const seqMask seqg_mask_SPC1GF_clearance_status_0_recover_from_paniq[] = {
	0x00000100,
};
static const seqMask seqg_mask_SPC1GF_clearance_status_0_clearance_faillures[] = {
	0x00000000,
};
static const seqMask seqg_mask_SPC1GF_clearance_status_0_recover_from_faillure[] = {
	0x00000080,
};

/* State table for state set "SPC1GF_clearance_status" */
static seqState seqg_states_SPC1GF_clearance_status[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_SPC1GF_clearance_status_0_init,
	/* event function */    seqg_event_SPC1GF_clearance_status_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPC1GF_clearance_status_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_40_pressed",
	/* action function */   seqg_action_SPC1GF_clearance_status_0_watchman_40_pressed,
	/* event function */    seqg_event_SPC1GF_clearance_status_0_watchman_40_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPC1GF_clearance_status_0_watchman_40_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "clearance_pending",
	/* action function */   seqg_action_SPC1GF_clearance_status_0_clearance_pending,
	/* event function */    seqg_event_SPC1GF_clearance_status_0_clearance_pending,
	/* entry function */    seqg_entry_SPC1GF_clearance_status_0_clearance_pending,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPC1GF_clearance_status_0_clearance_pending,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
	{
	/* state name */        "watchman_40_released",
	/* action function */   seqg_action_SPC1GF_clearance_status_0_watchman_40_released,
	/* event function */    seqg_event_SPC1GF_clearance_status_0_watchman_40_released,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPC1GF_clearance_status_0_watchman_40_released,
	/* state options */     (0)
	},
	{
	/* state name */        "gate_g7_closed",
	/* action function */   seqg_action_SPC1GF_clearance_status_0_gate_g7_closed,
	/* event function */    seqg_event_SPC1GF_clearance_status_0_gate_g7_closed,
	/* entry function */    seqg_entry_SPC1GF_clearance_status_0_gate_g7_closed,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPC1GF_clearance_status_0_gate_g7_closed,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "watchman_41_pressed",
	/* action function */   seqg_action_SPC1GF_clearance_status_0_watchman_41_pressed,
	/* event function */    seqg_event_SPC1GF_clearance_status_0_watchman_41_pressed,
	/* entry function */    seqg_entry_SPC1GF_clearance_status_0_watchman_41_pressed,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPC1GF_clearance_status_0_watchman_41_pressed,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "vault_cleared",
	/* action function */   seqg_action_SPC1GF_clearance_status_0_vault_cleared,
	/* event function */    seqg_event_SPC1GF_clearance_status_0_vault_cleared,
	/* entry function */    seqg_entry_SPC1GF_clearance_status_0_vault_cleared,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPC1GF_clearance_status_0_vault_cleared,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "paniq_faillure",
	/* action function */   seqg_action_SPC1GF_clearance_status_0_paniq_faillure,
	/* event function */    seqg_event_SPC1GF_clearance_status_0_paniq_faillure,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPC1GF_clearance_status_0_paniq_faillure,
	/* state options */     (0)
	},
	{
	/* state name */        "recover_from_paniq",
	/* action function */   seqg_action_SPC1GF_clearance_status_0_recover_from_paniq,
	/* event function */    seqg_event_SPC1GF_clearance_status_0_recover_from_paniq,
	/* entry function */    0,
	/* exit function */     seqg_exit_SPC1GF_clearance_status_0_recover_from_paniq,
	/* event mask array */  seqg_mask_SPC1GF_clearance_status_0_recover_from_paniq,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
	{
	/* state name */        "clearance_faillures",
	/* action function */   seqg_action_SPC1GF_clearance_status_0_clearance_faillures,
	/* event function */    seqg_event_SPC1GF_clearance_status_0_clearance_faillures,
	/* entry function */    seqg_entry_SPC1GF_clearance_status_0_clearance_faillures,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPC1GF_clearance_status_0_clearance_faillures,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
	{
	/* state name */        "recover_from_faillure",
	/* action function */   seqg_action_SPC1GF_clearance_status_0_recover_from_faillure,
	/* event function */    seqg_event_SPC1GF_clearance_status_0_recover_from_faillure,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPC1GF_clearance_status_0_recover_from_faillure,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "SPC1GF_clearance_status",
	/* states */            seqg_states_SPC1GF_clearance_status,
	/* number of states */  11
	},
};

/* Program table (global) */
seqProgram spc1gfClearanceSNC = {
	/* magic number */      2002001,
	/* program name */      "spc1gfClearanceSNC",
	/* channels */          seqg_chans,
	/* num. channels */     8,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 198 "../spc1gfClearanceSNC.stt"
static void initVault(SS_ID seqg_env)
{
# line 200 "../spc1gfClearanceSNC.stt"
	SPC1GF_RST_OUTS = TRUE;
# line 201 "../spc1gfClearanceSNC.stt"
	SPC1GF_OLD_FAIL_COND = SPC1GF_FAIL_COND;
# line 202 "../spc1gfClearanceSNC.stt"
	not_cleared(SPC1GF_CLR_STATS);
# line 203 "../spc1gfClearanceSNC.stt"
	report_error(SPC1GF_INTLCK_STATS, 0);
# line 204 "../spc1gfClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*SPC1GF_RST_OUTS*/, SYNC, DEFAULT_TIMEOUT);
# line 206 "../spc1gfClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SPC1GF_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 207 "../spc1gfClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*SPC1GF_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 211 "../spc1gfClearanceSNC.stt"
static void resetVault(SS_ID seqg_env)
{
# line 212 "../spc1gfClearanceSNC.stt"
	not_cleared(SPC1GF_CLR_STATS);
# line 213 "../spc1gfClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SPC1GF_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 216 "../spc1gfClearanceSNC.stt"
static void SPC1GF_update_failed(SS_ID seqg_env, short report)
{
# line 218 "../spc1gfClearanceSNC.stt"
	clear_failed(SPC1GF_CLR_STATS);
# line 219 "../spc1gfClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SPC1GF_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 220 "../spc1gfClearanceSNC.stt"
	report_error(SPC1GF_INTLCK_STATS, report);
# line 221 "../spc1gfClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*SPC1GF_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 222 "../spc1gfClearanceSNC.stt"
	printf("%s%s%s\n", ERROR, SPC1GF_INTLCK_STATS, DEF);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 225 "../spc1gfClearanceSNC.stt"
static void SPC1GF_update_report(SS_ID seqg_env, short intlck)
{
# line 226 "../spc1gfClearanceSNC.stt"
	report_error(SPC1GF_INTLCK_STATS, intlck);
# line 227 "../spc1gfClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*SPC1GF_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 230 "../spc1gfClearanceSNC.stt"
static void SPC1GF_status(SS_ID seqg_env)
{
# line 232 "../spc1gfClearanceSNC.stt"
	cleared(SPC1GF_CLR_STATS);
# line 233 "../spc1gfClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SPC1GF_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 234 "../spc1gfClearanceSNC.stt"
	report_error(SPC1GF_INTLCK_STATS, 0);
# line 235 "../spc1gfClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*SPC1GF_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 238 "../spc1gfClearanceSNC.stt"
static void SPC1GF_clear_underway(SS_ID seqg_env)
{
# line 240 "../spc1gfClearanceSNC.stt"
	clear_underway(SPC1GF_CLR_STATS);
# line 241 "../spc1gfClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SPC1GF_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

/* Register sequencer commands and program */
#include "epicsExport.h"
static void spc1gfClearanceSNCRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&spc1gfClearanceSNC);
}
epicsExportRegistrar(spc1gfClearanceSNCRegistrar);
