/* C code for program hliClearanceSNC, generated by snc from ../hliClearanceSNC.stt */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 3 "../hliClearanceSNC.stt"

#include "vcs_var_mes.h" // define this here so C functions are seen
#define STOK        0
#define WFVC        55
#define	B31OFF      92
#define	B30ON       89
#define DA14S1OFF   90
#define DA14S2OFF   91
#define HLIPNK      134


/* Variable declarations */
struct seqg_vars {
# line 16 "../hliClearanceSNC.stt"
	short HLI_INIT;
# line 17 "../hliClearanceSNC.stt"
	short HLI_VC;
# line 18 "../hliClearanceSNC.stt"
	short HLI_W30_STS;
# line 19 "../hliClearanceSNC.stt"
	short HLI_W31_STS;
# line 20 "../hliClearanceSNC.stt"
	short HLI_FAIL_COND;
# line 21 "../hliClearanceSNC.stt"
	short HLI_PNK;
# line 22 "../hliClearanceSNC.stt"
	short HLI_RST_OUTS;
# line 23 "../hliClearanceSNC.stt"
	string HLI_CLR_STATS;
# line 24 "../hliClearanceSNC.stt"
	string HLI_INTLCK_STATS;
# line 26 "../hliClearanceSNC.stt"
	short HLI_failed_rst;
# line 27 "../hliClearanceSNC.stt"
	short HLI_OLD_FAIL_COND;
# line 28 "../hliClearanceSNC.stt"
	short HLI_not_cleared;
};


/* Function declarations */
# line 225 "../hliClearanceSNC.stt"
static void initVault(SS_ID seqg_env);
# line 235 "../hliClearanceSNC.stt"
static void resetVault(SS_ID seqg_env);
# line 240 "../hliClearanceSNC.stt"
static void HLI_update_failed(SS_ID seqg_env, short report);
# line 249 "../hliClearanceSNC.stt"
static void HLI_update_report(SS_ID seqg_env, short intlck);
# line 254 "../hliClearanceSNC.stt"
static void HLI_status(SS_ID seqg_env);
# line 262 "../hliClearanceSNC.stt"
static void HLI_clear_underway(SS_ID seqg_env);

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 28 "../hliClearanceSNC.stt"
	static short seqg_initvar_HLI_not_cleared = FALSE;
	memcpy(&seqg_var->HLI_not_cleared, &seqg_initvar_HLI_not_cleared, sizeof(seqg_initvar_HLI_not_cleared));
	}
}

/****** Code for state "init" in state set "HLI_clearance_status" ******/

/* Event function for state "init" in state set "HLI_clearance_status" */
static seqBool seqg_event_HLI_clearance_status_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 51 "../hliClearanceSNC.stt"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "HLI_clearance_status" */
static void seqg_action_HLI_clearance_status_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 52 "../hliClearanceSNC.stt"
			initVault(seqg_env);
# line 53 "../hliClearanceSNC.stt"
			printf("\n%sHLI VAULT INITIALISATION COMPLETED%s\n", OK, DEF);
		}
		return;
	}
}

/****** Code for state "watchman_30_pressed" in state set "HLI_clearance_status" ******/

/* Event function for state "watchman_30_pressed" in state set "HLI_clearance_status" */
static seqBool seqg_event_HLI_clearance_status_0_watchman_30_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 59 "../hliClearanceSNC.stt"
	if (seqg_var->HLI_FAIL_COND != STOK)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 64 "../hliClearanceSNC.stt"
	if (seqg_var->HLI_W30_STS == WFVC)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 68 "../hliClearanceSNC.stt"
	if (seqg_var->HLI_W30_STS == B30ON)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_30_pressed" in state set "HLI_clearance_status" */
static void seqg_action_HLI_clearance_status_0_watchman_30_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 60 "../hliClearanceSNC.stt"
			seqg_var->HLI_OLD_FAIL_COND = seqg_var->HLI_FAIL_COND;
		}
		return;
	case 1:
		{
		}
		return;
	case 2:
		{
# line 69 "../hliClearanceSNC.stt"
			HLI_clear_underway(seqg_env);
# line 70 "../hliClearanceSNC.stt"
			HLI_update_report(seqg_env, B30ON);
		}
		return;
	}
}

/****** Code for state "clearance_pending" in state set "HLI_clearance_status" ******/

/* Entry function for state "clearance_pending" in state set "HLI_clearance_status" */
static void seqg_entry_HLI_clearance_status_0_clearance_pending(SS_ID seqg_env)
{
# line 78 "../hliClearanceSNC.stt"
	resetVault(seqg_env);
# line 79 "../hliClearanceSNC.stt"
	HLI_update_report(seqg_env, WFVC);
# line 80 "../hliClearanceSNC.stt"
	seqg_var->HLI_not_cleared = TRUE;
}

/* Event function for state "clearance_pending" in state set "HLI_clearance_status" */
static seqBool seqg_event_HLI_clearance_status_0_clearance_pending(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 82 "../hliClearanceSNC.stt"
	if (seqg_var->HLI_W30_STS != WFVC)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "clearance_pending" in state set "HLI_clearance_status" */
static void seqg_action_HLI_clearance_status_0_clearance_pending(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "watchman_30_released" in state set "HLI_clearance_status" ******/

/* Event function for state "watchman_30_released" in state set "HLI_clearance_status" */
static seqBool seqg_event_HLI_clearance_status_0_watchman_30_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 89 "../hliClearanceSNC.stt"
	if (seqg_var->HLI_FAIL_COND != STOK)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 93 "../hliClearanceSNC.stt"
	if (seqg_var->HLI_W30_STS != B30ON)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_30_released" in state set "HLI_clearance_status" */
static void seqg_action_HLI_clearance_status_0_watchman_30_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "A14_switch_I_closed" in state set "HLI_clearance_status" ******/

/* Entry function for state "A14_switch_I_closed" in state set "HLI_clearance_status" */
static void seqg_entry_HLI_clearance_status_0_A14_switch_I_closed(SS_ID seqg_env)
{
# line 103 "../hliClearanceSNC.stt"
	HLI_update_report(seqg_env, DA14S1OFF);
}

/* Event function for state "A14_switch_I_closed" in state set "HLI_clearance_status" */
static seqBool seqg_event_HLI_clearance_status_0_A14_switch_I_closed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 106 "../hliClearanceSNC.stt"
	if (seqg_var->HLI_FAIL_COND != STOK)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 110 "../hliClearanceSNC.stt"
	if (seqg_var->HLI_W31_STS != DA14S1OFF)
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "A14_switch_I_closed" in state set "HLI_clearance_status" */
static void seqg_action_HLI_clearance_status_0_A14_switch_I_closed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "A14_switch_II_closed" in state set "HLI_clearance_status" ******/

/* Entry function for state "A14_switch_II_closed" in state set "HLI_clearance_status" */
static void seqg_entry_HLI_clearance_status_0_A14_switch_II_closed(SS_ID seqg_env)
{
# line 121 "../hliClearanceSNC.stt"
	HLI_update_report(seqg_env, DA14S2OFF);
}

/* Event function for state "A14_switch_II_closed" in state set "HLI_clearance_status" */
static seqBool seqg_event_HLI_clearance_status_0_A14_switch_II_closed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 124 "../hliClearanceSNC.stt"
	if (seqg_var->HLI_FAIL_COND != STOK)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 129 "../hliClearanceSNC.stt"
	if (seqg_var->HLI_W31_STS == DA14S1OFF)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 133 "../hliClearanceSNC.stt"
	if (seqg_var->HLI_W31_STS != DA14S2OFF)
	{
		*seqg_pnst = 6;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "A14_switch_II_closed" in state set "HLI_clearance_status" */
static void seqg_action_HLI_clearance_status_0_A14_switch_II_closed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	case 2:
		{
		}
		return;
	}
}

/****** Code for state "watchman_31_pressed" in state set "HLI_clearance_status" ******/

/* Entry function for state "watchman_31_pressed" in state set "HLI_clearance_status" */
static void seqg_entry_HLI_clearance_status_0_watchman_31_pressed(SS_ID seqg_env)
{
# line 143 "../hliClearanceSNC.stt"
	HLI_update_report(seqg_env, B31OFF);
}

/* Event function for state "watchman_31_pressed" in state set "HLI_clearance_status" */
static seqBool seqg_event_HLI_clearance_status_0_watchman_31_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 146 "../hliClearanceSNC.stt"
	if (seqg_var->HLI_FAIL_COND != STOK)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 151 "../hliClearanceSNC.stt"
	if (seqg_var->HLI_W31_STS == STOK)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 155 "../hliClearanceSNC.stt"
	if (seqg_var->HLI_W31_STS != B31OFF)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_31_pressed" in state set "HLI_clearance_status" */
static void seqg_action_HLI_clearance_status_0_watchman_31_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	case 2:
		{
		}
		return;
	}
}

/****** Code for state "vault_cleared" in state set "HLI_clearance_status" ******/

/* Entry function for state "vault_cleared" in state set "HLI_clearance_status" */
static void seqg_entry_HLI_clearance_status_0_vault_cleared(SS_ID seqg_env)
{
# line 163 "../hliClearanceSNC.stt"
	HLI_status(seqg_env);
# line 164 "../hliClearanceSNC.stt"
	printf("%sHLI VAULT IN CLEARED STATE%s\n", CLR, DEF);
}

/* Event function for state "vault_cleared" in state set "HLI_clearance_status" */
static seqBool seqg_event_HLI_clearance_status_0_vault_cleared(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 166 "../hliClearanceSNC.stt"
	if (seqg_var->HLI_VC != STOK)
	{
		*seqg_pnst = 8;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "vault_cleared" in state set "HLI_clearance_status" */
static void seqg_action_HLI_clearance_status_0_vault_cleared(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "paniq_faillure" in state set "HLI_clearance_status" ******/

/* Event function for state "paniq_faillure" in state set "HLI_clearance_status" */
static seqBool seqg_event_HLI_clearance_status_0_paniq_faillure(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 174 "../hliClearanceSNC.stt"
	if (seqg_var->HLI_VC != HLIPNK)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
	if (TRUE)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "paniq_faillure" in state set "HLI_clearance_status" */
static void seqg_action_HLI_clearance_status_0_paniq_faillure(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 179 "../hliClearanceSNC.stt"
			printf("HLI VAULT CLEARED FAILURE CONDITION: ");
# line 180 "../hliClearanceSNC.stt"
			HLI_update_failed(seqg_env, HLIPNK);
		}
		return;
	}
}

/****** Code for state "recover_from_paniq" in state set "HLI_clearance_status" ******/

/* Exit function for state "recover_from_paniq" in state set "HLI_clearance_status" */
static void seqg_exit_HLI_clearance_status_0_recover_from_paniq(SS_ID seqg_env)
{
# line 192 "../hliClearanceSNC.stt"
	seqg_var->HLI_failed_rst = FALSE;
# line 193 "../hliClearanceSNC.stt"
	seqg_var->HLI_not_cleared = FALSE;
}

/* Event function for state "recover_from_paniq" in state set "HLI_clearance_status" */
static seqBool seqg_event_HLI_clearance_status_0_recover_from_paniq(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 187 "../hliClearanceSNC.stt"
	if (!seqg_var->HLI_PNK)
	{
		*seqg_pnst = 11;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "recover_from_paniq" in state set "HLI_clearance_status" */
static void seqg_action_HLI_clearance_status_0_recover_from_paniq(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "clearance_faillures" in state set "HLI_clearance_status" ******/

/* Entry function for state "clearance_faillures" in state set "HLI_clearance_status" */
static void seqg_entry_HLI_clearance_status_0_clearance_faillures(SS_ID seqg_env)
{
# line 202 "../hliClearanceSNC.stt"
	printf("HLI CLEARANCE FAILURE CONDITION: ");
# line 203 "../hliClearanceSNC.stt"
	seqg_var->HLI_failed_rst = FALSE;
# line 204 "../hliClearanceSNC.stt"
	seqg_var->HLI_not_cleared = FALSE;
# line 205 "../hliClearanceSNC.stt"
	seqg_var->HLI_OLD_FAIL_COND = seqg_var->HLI_FAIL_COND;
# line 206 "../hliClearanceSNC.stt"
	HLI_update_failed(seqg_env, seqg_var->HLI_FAIL_COND);
}

/* Event function for state "clearance_faillures" in state set "HLI_clearance_status" */
static seqBool seqg_event_HLI_clearance_status_0_clearance_faillures(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 11;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "clearance_faillures" in state set "HLI_clearance_status" */
static void seqg_action_HLI_clearance_status_0_clearance_faillures(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "recover_from_faillure" in state set "HLI_clearance_status" ******/

/* Event function for state "recover_from_faillure" in state set "HLI_clearance_status" */
static seqBool seqg_event_HLI_clearance_status_0_recover_from_faillure(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 215 "../hliClearanceSNC.stt"
	if (seqg_var->HLI_FAIL_COND == STOK)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 219 "../hliClearanceSNC.stt"
	if (seqg_var->HLI_FAIL_COND != seqg_var->HLI_OLD_FAIL_COND)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "recover_from_faillure" in state set "HLI_clearance_status" */
static void seqg_action_HLI_clearance_status_0_recover_from_faillure(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 216 "../hliClearanceSNC.stt"
			printf("%sHLI RECOVERING FROM CLEARANCE  FAILLURE : ENTERING W30 STATE%s\n", OK, DEF);
		}
		return;
	case 1:
		{
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{SYS}:RST-HLI.PROC", offsetof(struct seqg_vars, HLI_RST_OUTS), "HLI_RST_OUTS", P_SHORT, 1, 1, 0, 0, 0, 0},
	{"{SYS}:HLI-CLR-STATS", offsetof(struct seqg_vars, HLI_CLR_STATS), "HLI_CLR_STATS", P_STRING, 1, 2, 0, 0, 0, 0},
	{"{SYS}:HLI-INTLCK-STATS", offsetof(struct seqg_vars, HLI_INTLCK_STATS), "HLI_INTLCK_STATS", P_STRING, 1, 3, 0, 0, 0, 0},
	{"{SYS}:HLI-VC", offsetof(struct seqg_vars, HLI_VC), "HLI_VC", P_SHORT, 1, 4, 0, 1, 0, 0},
	{"{SYS}:HLI-W30-STS", offsetof(struct seqg_vars, HLI_W30_STS), "HLI_W30_STS", P_SHORT, 1, 5, 0, 1, 0, 0},
	{"{SYS}:HLI-W31-STS", offsetof(struct seqg_vars, HLI_W31_STS), "HLI_W31_STS", P_SHORT, 1, 6, 0, 1, 0, 0},
	{"{SYS}:HLI-FAIL-COND", offsetof(struct seqg_vars, HLI_FAIL_COND), "HLI_FAIL_COND", P_SHORT, 1, 7, 0, 1, 0, 0},
	{"{SYS}:HLI-PNK", offsetof(struct seqg_vars, HLI_PNK), "HLI_PNK", P_SHORT, 1, 8, 0, 1, 0, 0},
};

/* Event masks for state set "HLI_clearance_status" */
static const seqMask seqg_mask_HLI_clearance_status_0_init[] = {
	0x00000000,
};
static const seqMask seqg_mask_HLI_clearance_status_0_watchman_30_pressed[] = {
	0x000000a0,
};
static const seqMask seqg_mask_HLI_clearance_status_0_clearance_pending[] = {
	0x00000020,
};
static const seqMask seqg_mask_HLI_clearance_status_0_watchman_30_released[] = {
	0x000000a0,
};
static const seqMask seqg_mask_HLI_clearance_status_0_A14_switch_I_closed[] = {
	0x000000c0,
};
static const seqMask seqg_mask_HLI_clearance_status_0_A14_switch_II_closed[] = {
	0x000000c0,
};
static const seqMask seqg_mask_HLI_clearance_status_0_watchman_31_pressed[] = {
	0x000000c0,
};
static const seqMask seqg_mask_HLI_clearance_status_0_vault_cleared[] = {
	0x00000010,
};
static const seqMask seqg_mask_HLI_clearance_status_0_paniq_faillure[] = {
	0x00000010,
};
static const seqMask seqg_mask_HLI_clearance_status_0_recover_from_paniq[] = {
	0x00000100,
};
static const seqMask seqg_mask_HLI_clearance_status_0_clearance_faillures[] = {
	0x00000000,
};
static const seqMask seqg_mask_HLI_clearance_status_0_recover_from_faillure[] = {
	0x00000080,
};

/* State table for state set "HLI_clearance_status" */
static seqState seqg_states_HLI_clearance_status[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_HLI_clearance_status_0_init,
	/* event function */    seqg_event_HLI_clearance_status_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_HLI_clearance_status_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_30_pressed",
	/* action function */   seqg_action_HLI_clearance_status_0_watchman_30_pressed,
	/* event function */    seqg_event_HLI_clearance_status_0_watchman_30_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_HLI_clearance_status_0_watchman_30_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "clearance_pending",
	/* action function */   seqg_action_HLI_clearance_status_0_clearance_pending,
	/* event function */    seqg_event_HLI_clearance_status_0_clearance_pending,
	/* entry function */    seqg_entry_HLI_clearance_status_0_clearance_pending,
	/* exit function */     0,
	/* event mask array */  seqg_mask_HLI_clearance_status_0_clearance_pending,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
	{
	/* state name */        "watchman_30_released",
	/* action function */   seqg_action_HLI_clearance_status_0_watchman_30_released,
	/* event function */    seqg_event_HLI_clearance_status_0_watchman_30_released,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_HLI_clearance_status_0_watchman_30_released,
	/* state options */     (0)
	},
	{
	/* state name */        "A14_switch_I_closed",
	/* action function */   seqg_action_HLI_clearance_status_0_A14_switch_I_closed,
	/* event function */    seqg_event_HLI_clearance_status_0_A14_switch_I_closed,
	/* entry function */    seqg_entry_HLI_clearance_status_0_A14_switch_I_closed,
	/* exit function */     0,
	/* event mask array */  seqg_mask_HLI_clearance_status_0_A14_switch_I_closed,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "A14_switch_II_closed",
	/* action function */   seqg_action_HLI_clearance_status_0_A14_switch_II_closed,
	/* event function */    seqg_event_HLI_clearance_status_0_A14_switch_II_closed,
	/* entry function */    seqg_entry_HLI_clearance_status_0_A14_switch_II_closed,
	/* exit function */     0,
	/* event mask array */  seqg_mask_HLI_clearance_status_0_A14_switch_II_closed,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "watchman_31_pressed",
	/* action function */   seqg_action_HLI_clearance_status_0_watchman_31_pressed,
	/* event function */    seqg_event_HLI_clearance_status_0_watchman_31_pressed,
	/* entry function */    seqg_entry_HLI_clearance_status_0_watchman_31_pressed,
	/* exit function */     0,
	/* event mask array */  seqg_mask_HLI_clearance_status_0_watchman_31_pressed,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "vault_cleared",
	/* action function */   seqg_action_HLI_clearance_status_0_vault_cleared,
	/* event function */    seqg_event_HLI_clearance_status_0_vault_cleared,
	/* entry function */    seqg_entry_HLI_clearance_status_0_vault_cleared,
	/* exit function */     0,
	/* event mask array */  seqg_mask_HLI_clearance_status_0_vault_cleared,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "paniq_faillure",
	/* action function */   seqg_action_HLI_clearance_status_0_paniq_faillure,
	/* event function */    seqg_event_HLI_clearance_status_0_paniq_faillure,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_HLI_clearance_status_0_paniq_faillure,
	/* state options */     (0)
	},
	{
	/* state name */        "recover_from_paniq",
	/* action function */   seqg_action_HLI_clearance_status_0_recover_from_paniq,
	/* event function */    seqg_event_HLI_clearance_status_0_recover_from_paniq,
	/* entry function */    0,
	/* exit function */     seqg_exit_HLI_clearance_status_0_recover_from_paniq,
	/* event mask array */  seqg_mask_HLI_clearance_status_0_recover_from_paniq,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
	{
	/* state name */        "clearance_faillures",
	/* action function */   seqg_action_HLI_clearance_status_0_clearance_faillures,
	/* event function */    seqg_event_HLI_clearance_status_0_clearance_faillures,
	/* entry function */    seqg_entry_HLI_clearance_status_0_clearance_faillures,
	/* exit function */     0,
	/* event mask array */  seqg_mask_HLI_clearance_status_0_clearance_faillures,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
	{
	/* state name */        "recover_from_faillure",
	/* action function */   seqg_action_HLI_clearance_status_0_recover_from_faillure,
	/* event function */    seqg_event_HLI_clearance_status_0_recover_from_faillure,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_HLI_clearance_status_0_recover_from_faillure,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "HLI_clearance_status",
	/* states */            seqg_states_HLI_clearance_status,
	/* number of states */  12
	},
};

/* Program table (global) */
seqProgram hliClearanceSNC = {
	/* magic number */      2002001,
	/* program name */      "hliClearanceSNC",
	/* channels */          seqg_chans,
	/* num. channels */     8,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 225 "../hliClearanceSNC.stt"
static void initVault(SS_ID seqg_env)
{
# line 226 "../hliClearanceSNC.stt"
	seqg_var->HLI_OLD_FAIL_COND = seqg_var->HLI_FAIL_COND;
# line 227 "../hliClearanceSNC.stt"
	seqg_var->HLI_RST_OUTS = TRUE;
# line 228 "../hliClearanceSNC.stt"
	not_cleared(seqg_var->HLI_CLR_STATS);
# line 229 "../hliClearanceSNC.stt"
	report_error(seqg_var->HLI_INTLCK_STATS, 0);
# line 230 "../hliClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*HLI_RST_OUTS*/, SYNC, DEFAULT_TIMEOUT);
# line 231 "../hliClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*HLI_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 232 "../hliClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*HLI_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 235 "../hliClearanceSNC.stt"
static void resetVault(SS_ID seqg_env)
{
# line 236 "../hliClearanceSNC.stt"
	not_cleared(seqg_var->HLI_CLR_STATS);
# line 237 "../hliClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*HLI_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 240 "../hliClearanceSNC.stt"
static void HLI_update_failed(SS_ID seqg_env, short report)
{
# line 242 "../hliClearanceSNC.stt"
	clear_failed(seqg_var->HLI_CLR_STATS);
# line 243 "../hliClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*HLI_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 244 "../hliClearanceSNC.stt"
	report_error(seqg_var->HLI_INTLCK_STATS, report);
# line 245 "../hliClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*HLI_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 246 "../hliClearanceSNC.stt"
	printf("%s%s%s\n", ERROR, seqg_var->HLI_INTLCK_STATS, DEF);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 249 "../hliClearanceSNC.stt"
static void HLI_update_report(SS_ID seqg_env, short intlck)
{
# line 250 "../hliClearanceSNC.stt"
	report_error(seqg_var->HLI_INTLCK_STATS, intlck);
# line 251 "../hliClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*HLI_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 254 "../hliClearanceSNC.stt"
static void HLI_status(SS_ID seqg_env)
{
# line 256 "../hliClearanceSNC.stt"
	cleared(seqg_var->HLI_CLR_STATS);
# line 257 "../hliClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*HLI_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 258 "../hliClearanceSNC.stt"
	report_error(seqg_var->HLI_INTLCK_STATS, 0);
# line 259 "../hliClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*HLI_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 262 "../hliClearanceSNC.stt"
static void HLI_clear_underway(SS_ID seqg_env)
{
# line 264 "../hliClearanceSNC.stt"
	clear_underway(seqg_var->HLI_CLR_STATS);
# line 265 "../hliClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*HLI_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var
# line 269 "../hliClearanceSNC.stt"


inline void cleared(string vault_status) {   
    strcpy(vault_status, mes_array[1]); // Area cleared  
}
////////////////////////////////////////////////
inline void not_cleared(string vault_status) {  
   strcpy(vault_status, mes_array[2]); // Area not cleared    
}
///////////////////////////////////////////////
inline void clear_underway(string vault_status) { 
   strcpy(vault_status, mes_array[3]);  // Area clearance underway    
}
//////////////////////////////////////////////
inline void clear_failed(string vault_status) { 
   strcpy(vault_status, mes_array[5]); // Area clearance fail   
}
////////////////////////////////////////////////
inline void report_error(string vault_interlock, short intlock)
{
   strcpy(vault_interlock, mes_array[intlock]);
}
	


/* Register sequencer commands and program */
#include "epicsExport.h"
static void hliClearanceSNCRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&hliClearanceSNC);
}
epicsExportRegistrar(hliClearanceSNCRegistrar);
