/* C code for program iblClearanceSNC, generated by snc from ../iblClearanceSNC.stt */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 3 "../iblClearanceSNC.stt"

#include "vcs_var_mes.h" // define this here so C functions are seen
	
#define	STOK       	0
#define FAIL		    -1 	
#define	DA13S1OFF	  62	
#define	DA13S2OFF	  63	
#define B9ON        59
#define B8OFF       61
#define B8ON  		  60
#define B7OFF		    64  
#define WFVC		    55 
#define IBLPNK		  20 


/* Variable declarations */
# line 18 "../iblClearanceSNC.stt"
static	short IBL_INIT;
# line 19 "../iblClearanceSNC.stt"
static	short IBL_VC;
# line 20 "../iblClearanceSNC.stt"
static	short IBL_W9_STS;
# line 21 "../iblClearanceSNC.stt"
static	short IBL_W8_STS;
# line 22 "../iblClearanceSNC.stt"
static	short IBL_W7_STS;
# line 23 "../iblClearanceSNC.stt"
static	short IBL_RST_OUTS;
# line 24 "../iblClearanceSNC.stt"
static	short IBL_FAIL_COND;
# line 25 "../iblClearanceSNC.stt"
static	short IBL_OLD_FAIL_COND;
# line 26 "../iblClearanceSNC.stt"
static	short IBL_PNK;
# line 27 "../iblClearanceSNC.stt"
static	string IBL_CLR_STATS;
# line 28 "../iblClearanceSNC.stt"
static	string IBL_INTLCK_STATS;
# line 29 "../iblClearanceSNC.stt"
static	short ibl_failed_rst;
# line 30 "../iblClearanceSNC.stt"
static	short ibl_not_cleared;


/* Function declarations */
# line 246 "../iblClearanceSNC.stt"
static void initVault(SS_ID seqg_env);
# line 259 "../iblClearanceSNC.stt"
static void resetVault(SS_ID seqg_env);
# line 264 "../iblClearanceSNC.stt"
static void IBL_update_failed(SS_ID seqg_env, short report);
# line 273 "../iblClearanceSNC.stt"
static void IBL_update_report(SS_ID seqg_env, short intlck);
# line 278 "../iblClearanceSNC.stt"
static void IBL_status(SS_ID seqg_env);
# line 286 "../iblClearanceSNC.stt"
static void IBL_clear_underway(SS_ID seqg_env);

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 29 "../iblClearanceSNC.stt"
	static short seqg_initvar_ibl_failed_rst = FALSE;
	memcpy(&ibl_failed_rst, &seqg_initvar_ibl_failed_rst, sizeof(seqg_initvar_ibl_failed_rst));
	}
	{
# line 30 "../iblClearanceSNC.stt"
	static short seqg_initvar_ibl_not_cleared = FALSE;
	memcpy(&ibl_not_cleared, &seqg_initvar_ibl_not_cleared, sizeof(seqg_initvar_ibl_not_cleared));
	}
}

/****** Code for state "init" in state set "IBL_clearance_status" ******/

/* Event function for state "init" in state set "IBL_clearance_status" */
static seqBool seqg_event_IBL_clearance_status_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 53 "../iblClearanceSNC.stt"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "IBL_clearance_status" */
static void seqg_action_IBL_clearance_status_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 54 "../iblClearanceSNC.stt"
			initVault(seqg_env);
# line 55 "../iblClearanceSNC.stt"
			printf("%sISOTOPE BEAM LINE INITIALISATION COMPLETED%s\n", OK, DEF);
		}
		return;
	}
}

/****** Code for state "watchman_9_pressed" in state set "IBL_clearance_status" ******/

/* Event function for state "watchman_9_pressed" in state set "IBL_clearance_status" */
static seqBool seqg_event_IBL_clearance_status_0_watchman_9_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 62 "../iblClearanceSNC.stt"
	if (IBL_FAIL_COND != STOK)
	{
		*seqg_pnst = 12;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 66 "../iblClearanceSNC.stt"
	if (IBL_W9_STS == WFVC)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 70 "../iblClearanceSNC.stt"
	if (IBL_W9_STS == B9ON)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_9_pressed" in state set "IBL_clearance_status" */
static void seqg_action_IBL_clearance_status_0_watchman_9_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 63 "../iblClearanceSNC.stt"
			IBL_OLD_FAIL_COND = IBL_FAIL_COND;
		}
		return;
	case 1:
		{
		}
		return;
	case 2:
		{
# line 71 "../iblClearanceSNC.stt"
			IBL_clear_underway(seqg_env);
# line 72 "../iblClearanceSNC.stt"
			IBL_update_report(seqg_env, B9ON);
		}
		return;
	}
}

/****** Code for state "clearance_pending" in state set "IBL_clearance_status" ******/

/* Entry function for state "clearance_pending" in state set "IBL_clearance_status" */
static void seqg_entry_IBL_clearance_status_0_clearance_pending(SS_ID seqg_env)
{
# line 81 "../iblClearanceSNC.stt"
	resetVault(seqg_env);
# line 82 "../iblClearanceSNC.stt"
	IBL_update_report(seqg_env, WFVC);
# line 83 "../iblClearanceSNC.stt"
	ibl_not_cleared = TRUE;
}

/* Event function for state "clearance_pending" in state set "IBL_clearance_status" */
static seqBool seqg_event_IBL_clearance_status_0_clearance_pending(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 86 "../iblClearanceSNC.stt"
	if (IBL_W9_STS != WFVC)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "clearance_pending" in state set "IBL_clearance_status" */
static void seqg_action_IBL_clearance_status_0_clearance_pending(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "watchman_9_released" in state set "IBL_clearance_status" ******/

/* Event function for state "watchman_9_released" in state set "IBL_clearance_status" */
static seqBool seqg_event_IBL_clearance_status_0_watchman_9_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 94 "../iblClearanceSNC.stt"
	if (IBL_FAIL_COND != STOK)
	{
		*seqg_pnst = 12;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 98 "../iblClearanceSNC.stt"
	if (IBL_W9_STS != B9ON)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_9_released" in state set "IBL_clearance_status" */
static void seqg_action_IBL_clearance_status_0_watchman_9_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 99 "../iblClearanceSNC.stt"
			IBL_update_report(seqg_env, B8OFF);
		}
		return;
	}
}

/****** Code for state "watchman_8_pressed" in state set "IBL_clearance_status" ******/

/* Event function for state "watchman_8_pressed" in state set "IBL_clearance_status" */
static seqBool seqg_event_IBL_clearance_status_0_watchman_8_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 105 "../iblClearanceSNC.stt"
	if (IBL_W9_STS == FAIL)
	{
		*seqg_pnst = 12;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 110 "../iblClearanceSNC.stt"
	if (IBL_W8_STS == B8ON)
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_8_pressed" in state set "IBL_clearance_status" */
static void seqg_action_IBL_clearance_status_0_watchman_8_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 111 "../iblClearanceSNC.stt"
			IBL_update_report(seqg_env, B8ON);
		}
		return;
	}
}

/****** Code for state "watchman_8_released" in state set "IBL_clearance_status" ******/

/* Event function for state "watchman_8_released" in state set "IBL_clearance_status" */
static seqBool seqg_event_IBL_clearance_status_0_watchman_8_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 117 "../iblClearanceSNC.stt"
	if (IBL_FAIL_COND != STOK)
	{
		*seqg_pnst = 12;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 121 "../iblClearanceSNC.stt"
	if (IBL_W8_STS != B8ON)
	{
		*seqg_pnst = 6;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_8_released" in state set "IBL_clearance_status" */
static void seqg_action_IBL_clearance_status_0_watchman_8_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 122 "../iblClearanceSNC.stt"
			;
		}
		return;
	}
}

/****** Code for state "a13_switch_I_closed" in state set "IBL_clearance_status" ******/

/* Entry function for state "a13_switch_I_closed" in state set "IBL_clearance_status" */
static void seqg_entry_IBL_clearance_status_0_a13_switch_I_closed(SS_ID seqg_env)
{
# line 132 "../iblClearanceSNC.stt"
	IBL_update_report(seqg_env, DA13S1OFF);
}

/* Event function for state "a13_switch_I_closed" in state set "IBL_clearance_status" */
static seqBool seqg_event_IBL_clearance_status_0_a13_switch_I_closed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 135 "../iblClearanceSNC.stt"
	if (IBL_FAIL_COND != STOK)
	{
		*seqg_pnst = 12;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 139 "../iblClearanceSNC.stt"
	if (IBL_W7_STS != DA13S1OFF)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "a13_switch_I_closed" in state set "IBL_clearance_status" */
static void seqg_action_IBL_clearance_status_0_a13_switch_I_closed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "a13_switch_II_closed" in state set "IBL_clearance_status" ******/

/* Entry function for state "a13_switch_II_closed" in state set "IBL_clearance_status" */
static void seqg_entry_IBL_clearance_status_0_a13_switch_II_closed(SS_ID seqg_env)
{
# line 148 "../iblClearanceSNC.stt"
	IBL_update_report(seqg_env, DA13S2OFF);
}

/* Event function for state "a13_switch_II_closed" in state set "IBL_clearance_status" */
static seqBool seqg_event_IBL_clearance_status_0_a13_switch_II_closed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 151 "../iblClearanceSNC.stt"
	if (IBL_FAIL_COND != STOK)
	{
		*seqg_pnst = 12;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 155 "../iblClearanceSNC.stt"
	if (IBL_W7_STS != DA13S2OFF)
	{
		*seqg_pnst = 8;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "a13_switch_II_closed" in state set "IBL_clearance_status" */
static void seqg_action_IBL_clearance_status_0_a13_switch_II_closed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "watchman_7_pressed" in state set "IBL_clearance_status" ******/

/* Entry function for state "watchman_7_pressed" in state set "IBL_clearance_status" */
static void seqg_entry_IBL_clearance_status_0_watchman_7_pressed(SS_ID seqg_env)
{
# line 164 "../iblClearanceSNC.stt"
	IBL_update_report(seqg_env, B7OFF);
}

/* Event function for state "watchman_7_pressed" in state set "IBL_clearance_status" */
static seqBool seqg_event_IBL_clearance_status_0_watchman_7_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 167 "../iblClearanceSNC.stt"
	if (IBL_FAIL_COND != STOK)
	{
		*seqg_pnst = 12;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 171 "../iblClearanceSNC.stt"
	if (!IBL_W7_STS)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 176 "../iblClearanceSNC.stt"
	if (IBL_W7_STS != B7OFF)
	{
		*seqg_pnst = 6;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_7_pressed" in state set "IBL_clearance_status" */
static void seqg_action_IBL_clearance_status_0_watchman_7_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 173 "../iblClearanceSNC.stt"
			IBL_status(seqg_env);
		}
		return;
	case 2:
		{
		}
		return;
	}
}

/****** Code for state "vault_cleared" in state set "IBL_clearance_status" ******/

/* Entry function for state "vault_cleared" in state set "IBL_clearance_status" */
static void seqg_entry_IBL_clearance_status_0_vault_cleared(SS_ID seqg_env)
{
# line 184 "../iblClearanceSNC.stt"
	printf("%sISOTOPE BEAM LINE IN CLEARED STATE%s\n", CLR, DEF);
}

/* Event function for state "vault_cleared" in state set "IBL_clearance_status" */
static seqBool seqg_event_IBL_clearance_status_0_vault_cleared(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 186 "../iblClearanceSNC.stt"
	if (IBL_VC != STOK)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "vault_cleared" in state set "IBL_clearance_status" */
static void seqg_action_IBL_clearance_status_0_vault_cleared(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "paniq_faillure" in state set "IBL_clearance_status" ******/

/* Event function for state "paniq_faillure" in state set "IBL_clearance_status" */
static seqBool seqg_event_IBL_clearance_status_0_paniq_faillure(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 193 "../iblClearanceSNC.stt"
	if (IBL_VC != IBLPNK)
	{
		*seqg_pnst = 12;
		*seqg_ptrn = 0;
		return TRUE;
	}
	if (TRUE)
	{
		*seqg_pnst = 11;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "paniq_faillure" in state set "IBL_clearance_status" */
static void seqg_action_IBL_clearance_status_0_paniq_faillure(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 198 "../iblClearanceSNC.stt"
			printf("IBL VAULT CLEARED FAILURE CONDITION: ");
# line 199 "../iblClearanceSNC.stt"
			IBL_update_failed(seqg_env, IBLPNK);
		}
		return;
	}
}

/****** Code for state "recover_from_paniq" in state set "IBL_clearance_status" ******/

/* Exit function for state "recover_from_paniq" in state set "IBL_clearance_status" */
static void seqg_exit_IBL_clearance_status_0_recover_from_paniq(SS_ID seqg_env)
{
# line 212 "../iblClearanceSNC.stt"
	ibl_failed_rst = FALSE;
# line 213 "../iblClearanceSNC.stt"
	ibl_not_cleared = FALSE;
}

/* Event function for state "recover_from_paniq" in state set "IBL_clearance_status" */
static seqBool seqg_event_IBL_clearance_status_0_recover_from_paniq(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 207 "../iblClearanceSNC.stt"
	if (!IBL_PNK)
	{
		*seqg_pnst = 13;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "recover_from_paniq" in state set "IBL_clearance_status" */
static void seqg_action_IBL_clearance_status_0_recover_from_paniq(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "clearance_faillures" in state set "IBL_clearance_status" ******/

/* Entry function for state "clearance_faillures" in state set "IBL_clearance_status" */
static void seqg_entry_IBL_clearance_status_0_clearance_faillures(SS_ID seqg_env)
{
# line 222 "../iblClearanceSNC.stt"
	printf("IBL CLEARANCE FAILURE CONDITION: ");
# line 223 "../iblClearanceSNC.stt"
	ibl_failed_rst = FALSE;
# line 224 "../iblClearanceSNC.stt"
	ibl_not_cleared = FALSE;
# line 225 "../iblClearanceSNC.stt"
	IBL_OLD_FAIL_COND = IBL_FAIL_COND;
# line 226 "../iblClearanceSNC.stt"
	IBL_update_failed(seqg_env, IBL_FAIL_COND == FAIL ? STOK : IBL_FAIL_COND);
}

/* Event function for state "clearance_faillures" in state set "IBL_clearance_status" */
static seqBool seqg_event_IBL_clearance_status_0_clearance_faillures(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 13;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "clearance_faillures" in state set "IBL_clearance_status" */
static void seqg_action_IBL_clearance_status_0_clearance_faillures(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "recover_from_faillure" in state set "IBL_clearance_status" ******/

/* Event function for state "recover_from_faillure" in state set "IBL_clearance_status" */
static seqBool seqg_event_IBL_clearance_status_0_recover_from_faillure(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 236 "../iblClearanceSNC.stt"
	if (!IBL_FAIL_COND)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 240 "../iblClearanceSNC.stt"
	if (IBL_FAIL_COND != IBL_OLD_FAIL_COND)
	{
		*seqg_pnst = 12;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "recover_from_faillure" in state set "IBL_clearance_status" */
static void seqg_action_IBL_clearance_status_0_recover_from_faillure(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 237 "../iblClearanceSNC.stt"
			printf("%sIBL RECOVERING FROM FAILLURE : ENTERING W9 STATE%s\n", OK, DEF);
		}
		return;
	case 1:
		{
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{SYS}:RST-IBL.PROC", (size_t)&IBL_RST_OUTS, "IBL_RST_OUTS", P_SHORT, 1, 1, 0, 0, 0, 0},
	{"{SYS}:IBL-CLR-STATS", (size_t)&IBL_CLR_STATS, "IBL_CLR_STATS", P_STRING, 1, 2, 0, 0, 0, 0},
	{"{SYS}:IBL-INTLCK-STATS", (size_t)&IBL_INTLCK_STATS, "IBL_INTLCK_STATS", P_STRING, 1, 3, 0, 0, 0, 0},
	{"{SYS}:IBL-VC", (size_t)&IBL_VC, "IBL_VC", P_SHORT, 1, 4, 0, 1, 0, 0},
	{"{SYS}:IBL-W9-STS", (size_t)&IBL_W9_STS, "IBL_W9_STS", P_SHORT, 1, 5, 0, 1, 0, 0},
	{"{SYS}:IBL-W8-STS", (size_t)&IBL_W8_STS, "IBL_W8_STS", P_SHORT, 1, 6, 0, 1, 0, 0},
	{"{SYS}:IBL-W7-STS", (size_t)&IBL_W7_STS, "IBL_W7_STS", P_SHORT, 1, 7, 0, 1, 0, 0},
	{"{SYS}:IBL-FAIL-COND", (size_t)&IBL_FAIL_COND, "IBL_FAIL_COND", P_SHORT, 1, 8, 0, 1, 0, 0},
	{"{SYS}:IBL-PNK", (size_t)&IBL_PNK, "IBL_PNK", P_SHORT, 1, 9, 0, 1, 0, 0},
};

/* Event masks for state set "IBL_clearance_status" */
static const seqMask seqg_mask_IBL_clearance_status_0_init[] = {
	0x00000000,
};
static const seqMask seqg_mask_IBL_clearance_status_0_watchman_9_pressed[] = {
	0x00000120,
};
static const seqMask seqg_mask_IBL_clearance_status_0_clearance_pending[] = {
	0x00000020,
};
static const seqMask seqg_mask_IBL_clearance_status_0_watchman_9_released[] = {
	0x00000120,
};
static const seqMask seqg_mask_IBL_clearance_status_0_watchman_8_pressed[] = {
	0x00000060,
};
static const seqMask seqg_mask_IBL_clearance_status_0_watchman_8_released[] = {
	0x00000140,
};
static const seqMask seqg_mask_IBL_clearance_status_0_a13_switch_I_closed[] = {
	0x00000180,
};
static const seqMask seqg_mask_IBL_clearance_status_0_a13_switch_II_closed[] = {
	0x00000180,
};
static const seqMask seqg_mask_IBL_clearance_status_0_watchman_7_pressed[] = {
	0x00000180,
};
static const seqMask seqg_mask_IBL_clearance_status_0_vault_cleared[] = {
	0x00000010,
};
static const seqMask seqg_mask_IBL_clearance_status_0_paniq_faillure[] = {
	0x00000010,
};
static const seqMask seqg_mask_IBL_clearance_status_0_recover_from_paniq[] = {
	0x00000200,
};
static const seqMask seqg_mask_IBL_clearance_status_0_clearance_faillures[] = {
	0x00000000,
};
static const seqMask seqg_mask_IBL_clearance_status_0_recover_from_faillure[] = {
	0x00000100,
};

/* State table for state set "IBL_clearance_status" */
static seqState seqg_states_IBL_clearance_status[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_IBL_clearance_status_0_init,
	/* event function */    seqg_event_IBL_clearance_status_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_IBL_clearance_status_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_9_pressed",
	/* action function */   seqg_action_IBL_clearance_status_0_watchman_9_pressed,
	/* event function */    seqg_event_IBL_clearance_status_0_watchman_9_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_IBL_clearance_status_0_watchman_9_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "clearance_pending",
	/* action function */   seqg_action_IBL_clearance_status_0_clearance_pending,
	/* event function */    seqg_event_IBL_clearance_status_0_clearance_pending,
	/* entry function */    seqg_entry_IBL_clearance_status_0_clearance_pending,
	/* exit function */     0,
	/* event mask array */  seqg_mask_IBL_clearance_status_0_clearance_pending,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
	{
	/* state name */        "watchman_9_released",
	/* action function */   seqg_action_IBL_clearance_status_0_watchman_9_released,
	/* event function */    seqg_event_IBL_clearance_status_0_watchman_9_released,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_IBL_clearance_status_0_watchman_9_released,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_8_pressed",
	/* action function */   seqg_action_IBL_clearance_status_0_watchman_8_pressed,
	/* event function */    seqg_event_IBL_clearance_status_0_watchman_8_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_IBL_clearance_status_0_watchman_8_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_8_released",
	/* action function */   seqg_action_IBL_clearance_status_0_watchman_8_released,
	/* event function */    seqg_event_IBL_clearance_status_0_watchman_8_released,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_IBL_clearance_status_0_watchman_8_released,
	/* state options */     (0)
	},
	{
	/* state name */        "a13_switch_I_closed",
	/* action function */   seqg_action_IBL_clearance_status_0_a13_switch_I_closed,
	/* event function */    seqg_event_IBL_clearance_status_0_a13_switch_I_closed,
	/* entry function */    seqg_entry_IBL_clearance_status_0_a13_switch_I_closed,
	/* exit function */     0,
	/* event mask array */  seqg_mask_IBL_clearance_status_0_a13_switch_I_closed,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "a13_switch_II_closed",
	/* action function */   seqg_action_IBL_clearance_status_0_a13_switch_II_closed,
	/* event function */    seqg_event_IBL_clearance_status_0_a13_switch_II_closed,
	/* entry function */    seqg_entry_IBL_clearance_status_0_a13_switch_II_closed,
	/* exit function */     0,
	/* event mask array */  seqg_mask_IBL_clearance_status_0_a13_switch_II_closed,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "watchman_7_pressed",
	/* action function */   seqg_action_IBL_clearance_status_0_watchman_7_pressed,
	/* event function */    seqg_event_IBL_clearance_status_0_watchman_7_pressed,
	/* entry function */    seqg_entry_IBL_clearance_status_0_watchman_7_pressed,
	/* exit function */     0,
	/* event mask array */  seqg_mask_IBL_clearance_status_0_watchman_7_pressed,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "vault_cleared",
	/* action function */   seqg_action_IBL_clearance_status_0_vault_cleared,
	/* event function */    seqg_event_IBL_clearance_status_0_vault_cleared,
	/* entry function */    seqg_entry_IBL_clearance_status_0_vault_cleared,
	/* exit function */     0,
	/* event mask array */  seqg_mask_IBL_clearance_status_0_vault_cleared,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "paniq_faillure",
	/* action function */   seqg_action_IBL_clearance_status_0_paniq_faillure,
	/* event function */    seqg_event_IBL_clearance_status_0_paniq_faillure,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_IBL_clearance_status_0_paniq_faillure,
	/* state options */     (0)
	},
	{
	/* state name */        "recover_from_paniq",
	/* action function */   seqg_action_IBL_clearance_status_0_recover_from_paniq,
	/* event function */    seqg_event_IBL_clearance_status_0_recover_from_paniq,
	/* entry function */    0,
	/* exit function */     seqg_exit_IBL_clearance_status_0_recover_from_paniq,
	/* event mask array */  seqg_mask_IBL_clearance_status_0_recover_from_paniq,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
	{
	/* state name */        "clearance_faillures",
	/* action function */   seqg_action_IBL_clearance_status_0_clearance_faillures,
	/* event function */    seqg_event_IBL_clearance_status_0_clearance_faillures,
	/* entry function */    seqg_entry_IBL_clearance_status_0_clearance_faillures,
	/* exit function */     0,
	/* event mask array */  seqg_mask_IBL_clearance_status_0_clearance_faillures,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
	{
	/* state name */        "recover_from_faillure",
	/* action function */   seqg_action_IBL_clearance_status_0_recover_from_faillure,
	/* event function */    seqg_event_IBL_clearance_status_0_recover_from_faillure,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_IBL_clearance_status_0_recover_from_faillure,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "IBL_clearance_status",
	/* states */            seqg_states_IBL_clearance_status,
	/* number of states */  14
	},
};

/* Program table (global) */
seqProgram iblClearanceSNC = {
	/* magic number */      2002001,
	/* program name */      "iblClearanceSNC",
	/* channels */          seqg_chans,
	/* num. channels */     9,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 246 "../iblClearanceSNC.stt"
static void initVault(SS_ID seqg_env)
{
# line 248 "../iblClearanceSNC.stt"
	IBL_RST_OUTS = TRUE;
# line 249 "../iblClearanceSNC.stt"
	IBL_OLD_FAIL_COND = IBL_FAIL_COND;
# line 250 "../iblClearanceSNC.stt"
	not_cleared(IBL_CLR_STATS);
# line 251 "../iblClearanceSNC.stt"
	report_error(IBL_INTLCK_STATS, 0);
# line 252 "../iblClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*IBL_RST_OUTS*/, SYNC, DEFAULT_TIMEOUT);
# line 254 "../iblClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*IBL_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 255 "../iblClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*IBL_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 259 "../iblClearanceSNC.stt"
static void resetVault(SS_ID seqg_env)
{
# line 260 "../iblClearanceSNC.stt"
	not_cleared(IBL_CLR_STATS);
# line 261 "../iblClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*IBL_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 264 "../iblClearanceSNC.stt"
static void IBL_update_failed(SS_ID seqg_env, short report)
{
# line 266 "../iblClearanceSNC.stt"
	clear_failed(IBL_CLR_STATS);
# line 267 "../iblClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*IBL_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 268 "../iblClearanceSNC.stt"
	report_error(IBL_INTLCK_STATS, report);
# line 269 "../iblClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*IBL_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 270 "../iblClearanceSNC.stt"
	printf("%s%s%s\n", ERROR, IBL_INTLCK_STATS, DEF);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 273 "../iblClearanceSNC.stt"
static void IBL_update_report(SS_ID seqg_env, short intlck)
{
# line 274 "../iblClearanceSNC.stt"
	report_error(IBL_INTLCK_STATS, intlck);
# line 275 "../iblClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*IBL_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 278 "../iblClearanceSNC.stt"
static void IBL_status(SS_ID seqg_env)
{
# line 280 "../iblClearanceSNC.stt"
	cleared(IBL_CLR_STATS);
# line 281 "../iblClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*IBL_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 282 "../iblClearanceSNC.stt"
	report_error(IBL_INTLCK_STATS, 0);
# line 283 "../iblClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*IBL_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 286 "../iblClearanceSNC.stt"
static void IBL_clear_underway(SS_ID seqg_env)
{
# line 288 "../iblClearanceSNC.stt"
	clear_underway(IBL_CLR_STATS);
# line 289 "../iblClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*IBL_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

/* Register sequencer commands and program */
#include "epicsExport.h"
static void iblClearanceSNCRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&iblClearanceSNC);
}
epicsExportRegistrar(iblClearanceSNCRegistrar);
