/* C code for program ev1ClearanceSNC, generated by snc from ../ev1ClearanceSNC.stt */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 3 "../ev1ClearanceSNC.stt"

#include "vcs_var_mes.h" // define this here so C functions are seen
#define STOK      0
#define FAIL      -1
#define WFVC      55
#define	B19OFF    102
#define	B18ON     99
#define DA6S1OFF  100 
#define DA6S2OFF  101
#define RA6ON     144
#define RA7ON     145 
#define EV1PNK    131 


/* Variable declarations */
struct seqg_vars {
# line 18 "../ev1ClearanceSNC.stt"
	short EV1_INIT;
# line 19 "../ev1ClearanceSNC.stt"
	short EV1_VC;
# line 20 "../ev1ClearanceSNC.stt"
	short EV1_W18_STS;
# line 21 "../ev1ClearanceSNC.stt"
	short EV1_W19_STS;
# line 22 "../ev1ClearanceSNC.stt"
	short EV1_FAIL_COND;
# line 23 "../ev1ClearanceSNC.stt"
	short EV1_PNK;
# line 24 "../ev1ClearanceSNC.stt"
	short EV1_RST_OUTS;
# line 25 "../ev1ClearanceSNC.stt"
	string EV1_CLR_STATS;
# line 26 "../ev1ClearanceSNC.stt"
	string EV1_INTLCK_STATS;
# line 28 "../ev1ClearanceSNC.stt"
	short ev1_failed_rst;
# line 29 "../ev1ClearanceSNC.stt"
	short EV1_OLD_FAIL_COND;
# line 30 "../ev1ClearanceSNC.stt"
	short ev1_not_cleared;
};


/* Function declarations */
# line 226 "../ev1ClearanceSNC.stt"
static void initVault(SS_ID seqg_env);
# line 236 "../ev1ClearanceSNC.stt"
static void resetVault(SS_ID seqg_env);
# line 241 "../ev1ClearanceSNC.stt"
static void EV1_update_failed(SS_ID seqg_env, short report);
# line 250 "../ev1ClearanceSNC.stt"
static void EV1_update_report(SS_ID seqg_env, short intlck);
# line 255 "../ev1ClearanceSNC.stt"
static void EV1_status(SS_ID seqg_env);
# line 263 "../ev1ClearanceSNC.stt"
static void EV1_clear_underway(SS_ID seqg_env);

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 30 "../ev1ClearanceSNC.stt"
	static short seqg_initvar_ev1_not_cleared = FALSE;
	memcpy(&seqg_var->ev1_not_cleared, &seqg_initvar_ev1_not_cleared, sizeof(seqg_initvar_ev1_not_cleared));
	}
}

/****** Code for state "init" in state set "EV1_clearance_status" ******/

/* Event function for state "init" in state set "EV1_clearance_status" */
static seqBool seqg_event_EV1_clearance_status_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 52 "../ev1ClearanceSNC.stt"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "EV1_clearance_status" */
static void seqg_action_EV1_clearance_status_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 53 "../ev1ClearanceSNC.stt"
			initVault(seqg_env);
# line 54 "../ev1ClearanceSNC.stt"
			printf("\n%sEXPERIMENTAL VAULT 1 INITIALISATION COMPLETED%s\n", OK, DEF);
		}
		return;
	}
}

/****** Code for state "watchman_18_pressed" in state set "EV1_clearance_status" ******/

/* Event function for state "watchman_18_pressed" in state set "EV1_clearance_status" */
static seqBool seqg_event_EV1_clearance_status_0_watchman_18_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 60 "../ev1ClearanceSNC.stt"
	if (seqg_var->EV1_FAIL_COND != STOK)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 65 "../ev1ClearanceSNC.stt"
	if (seqg_var->EV1_W18_STS == WFVC)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 69 "../ev1ClearanceSNC.stt"
	if (seqg_var->EV1_W18_STS == B18ON)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_18_pressed" in state set "EV1_clearance_status" */
static void seqg_action_EV1_clearance_status_0_watchman_18_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 61 "../ev1ClearanceSNC.stt"
			seqg_var->EV1_OLD_FAIL_COND = seqg_var->EV1_FAIL_COND;
		}
		return;
	case 1:
		{
		}
		return;
	case 2:
		{
# line 70 "../ev1ClearanceSNC.stt"
			EV1_clear_underway(seqg_env);
# line 71 "../ev1ClearanceSNC.stt"
			EV1_update_report(seqg_env, B18ON);
		}
		return;
	}
}

/****** Code for state "clearance_pending" in state set "EV1_clearance_status" ******/

/* Entry function for state "clearance_pending" in state set "EV1_clearance_status" */
static void seqg_entry_EV1_clearance_status_0_clearance_pending(SS_ID seqg_env)
{
# line 79 "../ev1ClearanceSNC.stt"
	resetVault(seqg_env);
# line 80 "../ev1ClearanceSNC.stt"
	EV1_update_report(seqg_env, WFVC);
# line 81 "../ev1ClearanceSNC.stt"
	seqg_var->ev1_not_cleared = TRUE;
}

/* Event function for state "clearance_pending" in state set "EV1_clearance_status" */
static seqBool seqg_event_EV1_clearance_status_0_clearance_pending(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 83 "../ev1ClearanceSNC.stt"
	if (seqg_var->EV1_W18_STS != WFVC)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "clearance_pending" in state set "EV1_clearance_status" */
static void seqg_action_EV1_clearance_status_0_clearance_pending(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "watchman_18_released" in state set "EV1_clearance_status" ******/

/* Event function for state "watchman_18_released" in state set "EV1_clearance_status" */
static seqBool seqg_event_EV1_clearance_status_0_watchman_18_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 90 "../ev1ClearanceSNC.stt"
	if (seqg_var->EV1_FAIL_COND != STOK)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 94 "../ev1ClearanceSNC.stt"
	if (seqg_var->EV1_W18_STS != B18ON)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_18_released" in state set "EV1_clearance_status" */
static void seqg_action_EV1_clearance_status_0_watchman_18_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "a6_switch_I_closed" in state set "EV1_clearance_status" ******/

/* Entry function for state "a6_switch_I_closed" in state set "EV1_clearance_status" */
static void seqg_entry_EV1_clearance_status_0_a6_switch_I_closed(SS_ID seqg_env)
{
# line 104 "../ev1ClearanceSNC.stt"
	EV1_update_report(seqg_env, DA6S1OFF);
}

/* Event function for state "a6_switch_I_closed" in state set "EV1_clearance_status" */
static seqBool seqg_event_EV1_clearance_status_0_a6_switch_I_closed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 107 "../ev1ClearanceSNC.stt"
	if (seqg_var->EV1_FAIL_COND != STOK)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 111 "../ev1ClearanceSNC.stt"
	if (seqg_var->EV1_W19_STS != DA6S1OFF)
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "a6_switch_I_closed" in state set "EV1_clearance_status" */
static void seqg_action_EV1_clearance_status_0_a6_switch_I_closed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "a6_switch_II_closed" in state set "EV1_clearance_status" ******/

/* Entry function for state "a6_switch_II_closed" in state set "EV1_clearance_status" */
static void seqg_entry_EV1_clearance_status_0_a6_switch_II_closed(SS_ID seqg_env)
{
# line 122 "../ev1ClearanceSNC.stt"
	EV1_update_report(seqg_env, DA6S2OFF);
}

/* Event function for state "a6_switch_II_closed" in state set "EV1_clearance_status" */
static seqBool seqg_event_EV1_clearance_status_0_a6_switch_II_closed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 125 "../ev1ClearanceSNC.stt"
	if (seqg_var->EV1_FAIL_COND != STOK)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 130 "../ev1ClearanceSNC.stt"
	if (seqg_var->EV1_W19_STS == DA6S1OFF)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 134 "../ev1ClearanceSNC.stt"
	if (seqg_var->EV1_W19_STS != DA6S2OFF)
	{
		*seqg_pnst = 6;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "a6_switch_II_closed" in state set "EV1_clearance_status" */
static void seqg_action_EV1_clearance_status_0_a6_switch_II_closed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	case 2:
		{
		}
		return;
	}
}

/****** Code for state "watchman_19_pressed" in state set "EV1_clearance_status" ******/

/* Entry function for state "watchman_19_pressed" in state set "EV1_clearance_status" */
static void seqg_entry_EV1_clearance_status_0_watchman_19_pressed(SS_ID seqg_env)
{
# line 144 "../ev1ClearanceSNC.stt"
	EV1_update_report(seqg_env, B19OFF);
}

/* Event function for state "watchman_19_pressed" in state set "EV1_clearance_status" */
static seqBool seqg_event_EV1_clearance_status_0_watchman_19_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 147 "../ev1ClearanceSNC.stt"
	if (seqg_var->EV1_FAIL_COND != STOK)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 152 "../ev1ClearanceSNC.stt"
	if (seqg_var->EV1_W19_STS == STOK)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 156 "../ev1ClearanceSNC.stt"
	if (seqg_var->EV1_W19_STS != B19OFF)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_19_pressed" in state set "EV1_clearance_status" */
static void seqg_action_EV1_clearance_status_0_watchman_19_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	case 2:
		{
		}
		return;
	}
}

/****** Code for state "vault_cleared" in state set "EV1_clearance_status" ******/

/* Entry function for state "vault_cleared" in state set "EV1_clearance_status" */
static void seqg_entry_EV1_clearance_status_0_vault_cleared(SS_ID seqg_env)
{
# line 164 "../ev1ClearanceSNC.stt"
	EV1_status(seqg_env);
# line 165 "../ev1ClearanceSNC.stt"
	printf("%sEXPERIMENTAL VAULT 1 IN CLEARED STATE%s\n", CLR, DEF);
}

/* Event function for state "vault_cleared" in state set "EV1_clearance_status" */
static seqBool seqg_event_EV1_clearance_status_0_vault_cleared(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 167 "../ev1ClearanceSNC.stt"
	if (seqg_var->EV1_VC != STOK)
	{
		*seqg_pnst = 8;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "vault_cleared" in state set "EV1_clearance_status" */
static void seqg_action_EV1_clearance_status_0_vault_cleared(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "paniq_faillure" in state set "EV1_clearance_status" ******/

/* Event function for state "paniq_faillure" in state set "EV1_clearance_status" */
static seqBool seqg_event_EV1_clearance_status_0_paniq_faillure(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 175 "../ev1ClearanceSNC.stt"
	if (seqg_var->EV1_VC != EV1PNK)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
	if (TRUE)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "paniq_faillure" in state set "EV1_clearance_status" */
static void seqg_action_EV1_clearance_status_0_paniq_faillure(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 180 "../ev1ClearanceSNC.stt"
			printf("EV1 VAULT CLEARED FAILURE CONDITION: ");
# line 181 "../ev1ClearanceSNC.stt"
			EV1_update_failed(seqg_env, EV1PNK);
		}
		return;
	}
}

/****** Code for state "recover_from_paniq" in state set "EV1_clearance_status" ******/

/* Exit function for state "recover_from_paniq" in state set "EV1_clearance_status" */
static void seqg_exit_EV1_clearance_status_0_recover_from_paniq(SS_ID seqg_env)
{
# line 193 "../ev1ClearanceSNC.stt"
	seqg_var->ev1_failed_rst = FALSE;
# line 194 "../ev1ClearanceSNC.stt"
	seqg_var->ev1_not_cleared = FALSE;
}

/* Event function for state "recover_from_paniq" in state set "EV1_clearance_status" */
static seqBool seqg_event_EV1_clearance_status_0_recover_from_paniq(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 188 "../ev1ClearanceSNC.stt"
	if (!seqg_var->EV1_PNK)
	{
		*seqg_pnst = 11;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "recover_from_paniq" in state set "EV1_clearance_status" */
static void seqg_action_EV1_clearance_status_0_recover_from_paniq(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "clearance_faillures" in state set "EV1_clearance_status" ******/

/* Entry function for state "clearance_faillures" in state set "EV1_clearance_status" */
static void seqg_entry_EV1_clearance_status_0_clearance_faillures(SS_ID seqg_env)
{
# line 203 "../ev1ClearanceSNC.stt"
	printf("EV1 CLEARANCE FAILURE CONDITION: ");
# line 204 "../ev1ClearanceSNC.stt"
	seqg_var->ev1_failed_rst = FALSE;
# line 205 "../ev1ClearanceSNC.stt"
	seqg_var->ev1_not_cleared = FALSE;
# line 206 "../ev1ClearanceSNC.stt"
	seqg_var->EV1_OLD_FAIL_COND = seqg_var->EV1_FAIL_COND;
# line 207 "../ev1ClearanceSNC.stt"
	EV1_update_failed(seqg_env, seqg_var->EV1_FAIL_COND == FAIL ? STOK : seqg_var->EV1_FAIL_COND);
}

/* Event function for state "clearance_faillures" in state set "EV1_clearance_status" */
static seqBool seqg_event_EV1_clearance_status_0_clearance_faillures(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 11;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "clearance_faillures" in state set "EV1_clearance_status" */
static void seqg_action_EV1_clearance_status_0_clearance_faillures(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "recover_from_faillure" in state set "EV1_clearance_status" ******/

/* Event function for state "recover_from_faillure" in state set "EV1_clearance_status" */
static seqBool seqg_event_EV1_clearance_status_0_recover_from_faillure(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 216 "../ev1ClearanceSNC.stt"
	if (seqg_var->EV1_FAIL_COND == STOK)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 220 "../ev1ClearanceSNC.stt"
	if (seqg_var->EV1_FAIL_COND != seqg_var->EV1_OLD_FAIL_COND)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "recover_from_faillure" in state set "EV1_clearance_status" */
static void seqg_action_EV1_clearance_status_0_recover_from_faillure(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 217 "../ev1ClearanceSNC.stt"
			printf("%sEV1 RECOVERING FROM CLEARANCE  FAILLURE : ENTERING W18 STATE%s\n", OK, DEF);
		}
		return;
	case 1:
		{
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{SYS}:RST-EV1.PROC", offsetof(struct seqg_vars, EV1_RST_OUTS), "EV1_RST_OUTS", P_SHORT, 1, 1, 0, 0, 0, 0},
	{"{SYS}:EV1-CLR-STATS", offsetof(struct seqg_vars, EV1_CLR_STATS), "EV1_CLR_STATS", P_STRING, 1, 2, 0, 0, 0, 0},
	{"{SYS}:EV1-INTLCK-STATS", offsetof(struct seqg_vars, EV1_INTLCK_STATS), "EV1_INTLCK_STATS", P_STRING, 1, 3, 0, 0, 0, 0},
	{"{SYS}:EV1-VC", offsetof(struct seqg_vars, EV1_VC), "EV1_VC", P_SHORT, 1, 4, 0, 1, 0, 0},
	{"{SYS}:EV1-W18-STS", offsetof(struct seqg_vars, EV1_W18_STS), "EV1_W18_STS", P_SHORT, 1, 5, 0, 1, 0, 0},
	{"{SYS}:EV1-W19-STS", offsetof(struct seqg_vars, EV1_W19_STS), "EV1_W19_STS", P_SHORT, 1, 6, 0, 1, 0, 0},
	{"{SYS}:EV1-FAIL-COND", offsetof(struct seqg_vars, EV1_FAIL_COND), "EV1_FAIL_COND", P_SHORT, 1, 7, 0, 1, 0, 0},
	{"{SYS}:EV1-PNK", offsetof(struct seqg_vars, EV1_PNK), "EV1_PNK", P_SHORT, 1, 8, 0, 1, 0, 0},
};

/* Event masks for state set "EV1_clearance_status" */
static const seqMask seqg_mask_EV1_clearance_status_0_init[] = {
	0x00000000,
};
static const seqMask seqg_mask_EV1_clearance_status_0_watchman_18_pressed[] = {
	0x000000a0,
};
static const seqMask seqg_mask_EV1_clearance_status_0_clearance_pending[] = {
	0x00000020,
};
static const seqMask seqg_mask_EV1_clearance_status_0_watchman_18_released[] = {
	0x000000a0,
};
static const seqMask seqg_mask_EV1_clearance_status_0_a6_switch_I_closed[] = {
	0x000000c0,
};
static const seqMask seqg_mask_EV1_clearance_status_0_a6_switch_II_closed[] = {
	0x000000c0,
};
static const seqMask seqg_mask_EV1_clearance_status_0_watchman_19_pressed[] = {
	0x000000c0,
};
static const seqMask seqg_mask_EV1_clearance_status_0_vault_cleared[] = {
	0x00000010,
};
static const seqMask seqg_mask_EV1_clearance_status_0_paniq_faillure[] = {
	0x00000010,
};
static const seqMask seqg_mask_EV1_clearance_status_0_recover_from_paniq[] = {
	0x00000100,
};
static const seqMask seqg_mask_EV1_clearance_status_0_clearance_faillures[] = {
	0x00000000,
};
static const seqMask seqg_mask_EV1_clearance_status_0_recover_from_faillure[] = {
	0x00000080,
};

/* State table for state set "EV1_clearance_status" */
static seqState seqg_states_EV1_clearance_status[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_EV1_clearance_status_0_init,
	/* event function */    seqg_event_EV1_clearance_status_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_EV1_clearance_status_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_18_pressed",
	/* action function */   seqg_action_EV1_clearance_status_0_watchman_18_pressed,
	/* event function */    seqg_event_EV1_clearance_status_0_watchman_18_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_EV1_clearance_status_0_watchman_18_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "clearance_pending",
	/* action function */   seqg_action_EV1_clearance_status_0_clearance_pending,
	/* event function */    seqg_event_EV1_clearance_status_0_clearance_pending,
	/* entry function */    seqg_entry_EV1_clearance_status_0_clearance_pending,
	/* exit function */     0,
	/* event mask array */  seqg_mask_EV1_clearance_status_0_clearance_pending,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
	{
	/* state name */        "watchman_18_released",
	/* action function */   seqg_action_EV1_clearance_status_0_watchman_18_released,
	/* event function */    seqg_event_EV1_clearance_status_0_watchman_18_released,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_EV1_clearance_status_0_watchman_18_released,
	/* state options */     (0)
	},
	{
	/* state name */        "a6_switch_I_closed",
	/* action function */   seqg_action_EV1_clearance_status_0_a6_switch_I_closed,
	/* event function */    seqg_event_EV1_clearance_status_0_a6_switch_I_closed,
	/* entry function */    seqg_entry_EV1_clearance_status_0_a6_switch_I_closed,
	/* exit function */     0,
	/* event mask array */  seqg_mask_EV1_clearance_status_0_a6_switch_I_closed,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "a6_switch_II_closed",
	/* action function */   seqg_action_EV1_clearance_status_0_a6_switch_II_closed,
	/* event function */    seqg_event_EV1_clearance_status_0_a6_switch_II_closed,
	/* entry function */    seqg_entry_EV1_clearance_status_0_a6_switch_II_closed,
	/* exit function */     0,
	/* event mask array */  seqg_mask_EV1_clearance_status_0_a6_switch_II_closed,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "watchman_19_pressed",
	/* action function */   seqg_action_EV1_clearance_status_0_watchman_19_pressed,
	/* event function */    seqg_event_EV1_clearance_status_0_watchman_19_pressed,
	/* entry function */    seqg_entry_EV1_clearance_status_0_watchman_19_pressed,
	/* exit function */     0,
	/* event mask array */  seqg_mask_EV1_clearance_status_0_watchman_19_pressed,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "vault_cleared",
	/* action function */   seqg_action_EV1_clearance_status_0_vault_cleared,
	/* event function */    seqg_event_EV1_clearance_status_0_vault_cleared,
	/* entry function */    seqg_entry_EV1_clearance_status_0_vault_cleared,
	/* exit function */     0,
	/* event mask array */  seqg_mask_EV1_clearance_status_0_vault_cleared,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "paniq_faillure",
	/* action function */   seqg_action_EV1_clearance_status_0_paniq_faillure,
	/* event function */    seqg_event_EV1_clearance_status_0_paniq_faillure,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_EV1_clearance_status_0_paniq_faillure,
	/* state options */     (0)
	},
	{
	/* state name */        "recover_from_paniq",
	/* action function */   seqg_action_EV1_clearance_status_0_recover_from_paniq,
	/* event function */    seqg_event_EV1_clearance_status_0_recover_from_paniq,
	/* entry function */    0,
	/* exit function */     seqg_exit_EV1_clearance_status_0_recover_from_paniq,
	/* event mask array */  seqg_mask_EV1_clearance_status_0_recover_from_paniq,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
	{
	/* state name */        "clearance_faillures",
	/* action function */   seqg_action_EV1_clearance_status_0_clearance_faillures,
	/* event function */    seqg_event_EV1_clearance_status_0_clearance_faillures,
	/* entry function */    seqg_entry_EV1_clearance_status_0_clearance_faillures,
	/* exit function */     0,
	/* event mask array */  seqg_mask_EV1_clearance_status_0_clearance_faillures,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
	{
	/* state name */        "recover_from_faillure",
	/* action function */   seqg_action_EV1_clearance_status_0_recover_from_faillure,
	/* event function */    seqg_event_EV1_clearance_status_0_recover_from_faillure,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_EV1_clearance_status_0_recover_from_faillure,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "EV1_clearance_status",
	/* states */            seqg_states_EV1_clearance_status,
	/* number of states */  12
	},
};

/* Program table (global) */
seqProgram ev1ClearanceSNC = {
	/* magic number */      2002001,
	/* program name */      "ev1ClearanceSNC",
	/* channels */          seqg_chans,
	/* num. channels */     8,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 226 "../ev1ClearanceSNC.stt"
static void initVault(SS_ID seqg_env)
{
# line 227 "../ev1ClearanceSNC.stt"
	seqg_var->EV1_OLD_FAIL_COND = seqg_var->EV1_FAIL_COND;
# line 228 "../ev1ClearanceSNC.stt"
	seqg_var->EV1_RST_OUTS = TRUE;
# line 229 "../ev1ClearanceSNC.stt"
	not_cleared(seqg_var->EV1_CLR_STATS);
# line 230 "../ev1ClearanceSNC.stt"
	report_error(seqg_var->EV1_INTLCK_STATS, 0);
# line 231 "../ev1ClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*EV1_RST_OUTS*/, SYNC, DEFAULT_TIMEOUT);
# line 232 "../ev1ClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*EV1_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 233 "../ev1ClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*EV1_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 236 "../ev1ClearanceSNC.stt"
static void resetVault(SS_ID seqg_env)
{
# line 237 "../ev1ClearanceSNC.stt"
	not_cleared(seqg_var->EV1_CLR_STATS);
# line 238 "../ev1ClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*EV1_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 241 "../ev1ClearanceSNC.stt"
static void EV1_update_failed(SS_ID seqg_env, short report)
{
# line 243 "../ev1ClearanceSNC.stt"
	clear_failed(seqg_var->EV1_CLR_STATS);
# line 244 "../ev1ClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*EV1_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 245 "../ev1ClearanceSNC.stt"
	report_error(seqg_var->EV1_INTLCK_STATS, report);
# line 246 "../ev1ClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*EV1_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 247 "../ev1ClearanceSNC.stt"
	printf("%s%s%s\n", ERROR, seqg_var->EV1_INTLCK_STATS, DEF);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 250 "../ev1ClearanceSNC.stt"
static void EV1_update_report(SS_ID seqg_env, short intlck)
{
# line 251 "../ev1ClearanceSNC.stt"
	report_error(seqg_var->EV1_INTLCK_STATS, intlck);
# line 252 "../ev1ClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*EV1_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 255 "../ev1ClearanceSNC.stt"
static void EV1_status(SS_ID seqg_env)
{
# line 257 "../ev1ClearanceSNC.stt"
	cleared(seqg_var->EV1_CLR_STATS);
# line 258 "../ev1ClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*EV1_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 259 "../ev1ClearanceSNC.stt"
	report_error(seqg_var->EV1_INTLCK_STATS, 0);
# line 260 "../ev1ClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*EV1_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 263 "../ev1ClearanceSNC.stt"
static void EV1_clear_underway(SS_ID seqg_env)
{
# line 265 "../ev1ClearanceSNC.stt"
	clear_underway(seqg_var->EV1_CLR_STATS);
# line 266 "../ev1ClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*EV1_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var
# line 270 "../ev1ClearanceSNC.stt"


inline void cleared(string vault_status) {   
    strcpy(vault_status, mes_array[1]); // Area cleared  
}
////////////////////////////////////////////////
inline void not_cleared(string vault_status) {  
   strcpy(vault_status, mes_array[2]); // Area not cleared    
}
///////////////////////////////////////////////
inline void clear_underway(string vault_status) { 
   strcpy(vault_status, mes_array[3]);  // Area clearance underway    
}
//////////////////////////////////////////////
inline void clear_failed(string vault_status) { 
   strcpy(vault_status, mes_array[5]); // Area clearance fail   
}
////////////////////////////////////////////////
inline void report_error(string vault_interlock, short intlock)
{
   strcpy(vault_interlock, mes_array[intlock]);
}
	


/* Register sequencer commands and program */
#include "epicsExport.h"
static void ev1ClearanceSNCRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&ev1ClearanceSNC);
}
epicsExportRegistrar(ev1ClearanceSNCRegistrar);
