#! /bin/sh

### BEGIN INIT INFO
# provide:              startioc
# Required-Start:       ethercat
# Required-Stop:        ethercat
# Default-Start:        3 5
# Default-Stop          0 1 2 6
# Short Description:    Manager script for epics and ethercat scanner service
# Description:          st.cmd and scanner starting script
### END INIT INFO


case "$1" in
  start)
    /etc/init.d/ethercat start
    echo "ethercat started "
    sleep 2
    cd /epics/ethercat-4-3/iocs/iocvcs/iocBoot/iocvcs
    tmux new -s SCANNER -d ./start_scanner &
    echo "scanner started "
    sleep 2
    tmux new -s IOC -d ./st.cmd &
    echo "IOC started "
    ;;
  stop)
    tmux kill-session -t IOC
    tmux kill-session -t SCANNER
    echo "IOC stopped"
    echo "Scanner Stopped"
    ;;
  *)
    echo "Usage: /etc/init.d/startioc {start|stop}"
    exit 1
    ;;
esac

exit 0
