/* C code for program speClearanceSNC, generated by snc from ../speClearanceSNC.stt */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 3 "../speClearanceSNC.stt"

#include "vcs_var_mes.h" // define this here so C functions are seen
#define STOK        0
#define FAIL        -1
#define WFVC        55
#define	B25OFF      116
#define	B24ON       115
#define DA9S1OFF    117
#define DA9S2OFF    118
#define SPEPNK      113 


/* Variable declarations */
struct seqg_vars {
# line 17 "../speClearanceSNC.stt"
	short SPE_INIT;
# line 18 "../speClearanceSNC.stt"
	short SPE_VC;
# line 19 "../speClearanceSNC.stt"
	short SPE_W24_STS;
# line 20 "../speClearanceSNC.stt"
	short SPE_W25_STS;
# line 21 "../speClearanceSNC.stt"
	short SPE_FAIL_COND;
# line 22 "../speClearanceSNC.stt"
	short SPE_PNK;
# line 23 "../speClearanceSNC.stt"
	short SPE_RST_OUTS;
# line 24 "../speClearanceSNC.stt"
	string SPE_CLR_STATS;
# line 25 "../speClearanceSNC.stt"
	string SPE_INTLCK_STATS;
# line 27 "../speClearanceSNC.stt"
	short SPE_failed_rst;
# line 28 "../speClearanceSNC.stt"
	short SPE_OLD_FAIL_COND;
# line 29 "../speClearanceSNC.stt"
	short SPE_not_cleared;
};


/* Function declarations */
# line 226 "../speClearanceSNC.stt"
static void initVault(SS_ID seqg_env);
# line 236 "../speClearanceSNC.stt"
static void resetVault(SS_ID seqg_env);
# line 241 "../speClearanceSNC.stt"
static void SPE_update_failed(SS_ID seqg_env, short report);
# line 250 "../speClearanceSNC.stt"
static void SPE_update_report(SS_ID seqg_env, short intlck);
# line 255 "../speClearanceSNC.stt"
static void SPE_status(SS_ID seqg_env);
# line 263 "../speClearanceSNC.stt"
static void SPE_clear_underway(SS_ID seqg_env);

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 29 "../speClearanceSNC.stt"
	static short seqg_initvar_SPE_not_cleared = FALSE;
	memcpy(&seqg_var->SPE_not_cleared, &seqg_initvar_SPE_not_cleared, sizeof(seqg_initvar_SPE_not_cleared));
	}
}

/****** Code for state "init" in state set "SPE_clearance_status" ******/

/* Event function for state "init" in state set "SPE_clearance_status" */
static seqBool seqg_event_SPE_clearance_status_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 52 "../speClearanceSNC.stt"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "SPE_clearance_status" */
static void seqg_action_SPE_clearance_status_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 53 "../speClearanceSNC.stt"
			initVault(seqg_env);
# line 54 "../speClearanceSNC.stt"
			printf("\n%sSPECTROMETER VAULT INITIALISATION COMPLETED%s\n", OK, DEF);
		}
		return;
	}
}

/****** Code for state "watchman_24_pressed" in state set "SPE_clearance_status" ******/

/* Event function for state "watchman_24_pressed" in state set "SPE_clearance_status" */
static seqBool seqg_event_SPE_clearance_status_0_watchman_24_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 60 "../speClearanceSNC.stt"
	if (seqg_var->SPE_FAIL_COND != STOK)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 65 "../speClearanceSNC.stt"
	if (seqg_var->SPE_W24_STS == WFVC)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 69 "../speClearanceSNC.stt"
	if (seqg_var->SPE_W24_STS == B24ON)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_24_pressed" in state set "SPE_clearance_status" */
static void seqg_action_SPE_clearance_status_0_watchman_24_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 61 "../speClearanceSNC.stt"
			seqg_var->SPE_OLD_FAIL_COND = seqg_var->SPE_FAIL_COND;
		}
		return;
	case 1:
		{
		}
		return;
	case 2:
		{
# line 70 "../speClearanceSNC.stt"
			SPE_clear_underway(seqg_env);
# line 71 "../speClearanceSNC.stt"
			SPE_update_report(seqg_env, B24ON);
		}
		return;
	}
}

/****** Code for state "clearance_pending" in state set "SPE_clearance_status" ******/

/* Entry function for state "clearance_pending" in state set "SPE_clearance_status" */
static void seqg_entry_SPE_clearance_status_0_clearance_pending(SS_ID seqg_env)
{
# line 79 "../speClearanceSNC.stt"
	resetVault(seqg_env);
# line 80 "../speClearanceSNC.stt"
	SPE_update_report(seqg_env, WFVC);
# line 81 "../speClearanceSNC.stt"
	seqg_var->SPE_not_cleared = TRUE;
}

/* Event function for state "clearance_pending" in state set "SPE_clearance_status" */
static seqBool seqg_event_SPE_clearance_status_0_clearance_pending(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 83 "../speClearanceSNC.stt"
	if (seqg_var->SPE_W24_STS != WFVC)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "clearance_pending" in state set "SPE_clearance_status" */
static void seqg_action_SPE_clearance_status_0_clearance_pending(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "watchman_24_released" in state set "SPE_clearance_status" ******/

/* Event function for state "watchman_24_released" in state set "SPE_clearance_status" */
static seqBool seqg_event_SPE_clearance_status_0_watchman_24_released(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 90 "../speClearanceSNC.stt"
	if (seqg_var->SPE_FAIL_COND != STOK)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 94 "../speClearanceSNC.stt"
	if (seqg_var->SPE_W24_STS != B24ON)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_24_released" in state set "SPE_clearance_status" */
static void seqg_action_SPE_clearance_status_0_watchman_24_released(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "A9_switch_I_closed" in state set "SPE_clearance_status" ******/

/* Entry function for state "A9_switch_I_closed" in state set "SPE_clearance_status" */
static void seqg_entry_SPE_clearance_status_0_A9_switch_I_closed(SS_ID seqg_env)
{
# line 104 "../speClearanceSNC.stt"
	SPE_update_report(seqg_env, DA9S1OFF);
}

/* Event function for state "A9_switch_I_closed" in state set "SPE_clearance_status" */
static seqBool seqg_event_SPE_clearance_status_0_A9_switch_I_closed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 107 "../speClearanceSNC.stt"
	if (seqg_var->SPE_FAIL_COND != STOK)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 111 "../speClearanceSNC.stt"
	if (seqg_var->SPE_W25_STS != DA9S1OFF)
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "A9_switch_I_closed" in state set "SPE_clearance_status" */
static void seqg_action_SPE_clearance_status_0_A9_switch_I_closed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "A9_switch_II_closed" in state set "SPE_clearance_status" ******/

/* Entry function for state "A9_switch_II_closed" in state set "SPE_clearance_status" */
static void seqg_entry_SPE_clearance_status_0_A9_switch_II_closed(SS_ID seqg_env)
{
# line 122 "../speClearanceSNC.stt"
	SPE_update_report(seqg_env, DA9S2OFF);
}

/* Event function for state "A9_switch_II_closed" in state set "SPE_clearance_status" */
static seqBool seqg_event_SPE_clearance_status_0_A9_switch_II_closed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 125 "../speClearanceSNC.stt"
	if (seqg_var->SPE_FAIL_COND != STOK)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 130 "../speClearanceSNC.stt"
	if (seqg_var->SPE_W25_STS == DA9S1OFF)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 134 "../speClearanceSNC.stt"
	if (seqg_var->SPE_W25_STS != DA9S2OFF)
	{
		*seqg_pnst = 6;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "A9_switch_II_closed" in state set "SPE_clearance_status" */
static void seqg_action_SPE_clearance_status_0_A9_switch_II_closed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	case 2:
		{
		}
		return;
	}
}

/****** Code for state "watchman_25_pressed" in state set "SPE_clearance_status" ******/

/* Entry function for state "watchman_25_pressed" in state set "SPE_clearance_status" */
static void seqg_entry_SPE_clearance_status_0_watchman_25_pressed(SS_ID seqg_env)
{
# line 144 "../speClearanceSNC.stt"
	SPE_update_report(seqg_env, B25OFF);
}

/* Event function for state "watchman_25_pressed" in state set "SPE_clearance_status" */
static seqBool seqg_event_SPE_clearance_status_0_watchman_25_pressed(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 147 "../speClearanceSNC.stt"
	if (seqg_var->SPE_FAIL_COND != STOK)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 152 "../speClearanceSNC.stt"
	if (seqg_var->SPE_W25_STS == STOK)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 156 "../speClearanceSNC.stt"
	if (seqg_var->SPE_W25_STS != B25OFF)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "watchman_25_pressed" in state set "SPE_clearance_status" */
static void seqg_action_SPE_clearance_status_0_watchman_25_pressed(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	case 2:
		{
		}
		return;
	}
}

/****** Code for state "vault_cleared" in state set "SPE_clearance_status" ******/

/* Entry function for state "vault_cleared" in state set "SPE_clearance_status" */
static void seqg_entry_SPE_clearance_status_0_vault_cleared(SS_ID seqg_env)
{
# line 164 "../speClearanceSNC.stt"
	SPE_status(seqg_env);
# line 165 "../speClearanceSNC.stt"
	printf("%sSPECTROMETER VAULT IN CLEARED STATE%s\n", CLR, DEF);
}

/* Event function for state "vault_cleared" in state set "SPE_clearance_status" */
static seqBool seqg_event_SPE_clearance_status_0_vault_cleared(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 167 "../speClearanceSNC.stt"
	if (seqg_var->SPE_VC != STOK)
	{
		*seqg_pnst = 8;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "vault_cleared" in state set "SPE_clearance_status" */
static void seqg_action_SPE_clearance_status_0_vault_cleared(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "paniq_faillure" in state set "SPE_clearance_status" ******/

/* Event function for state "paniq_faillure" in state set "SPE_clearance_status" */
static seqBool seqg_event_SPE_clearance_status_0_paniq_faillure(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 175 "../speClearanceSNC.stt"
	if (seqg_var->SPE_VC != SPEPNK)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
	if (TRUE)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "paniq_faillure" in state set "SPE_clearance_status" */
static void seqg_action_SPE_clearance_status_0_paniq_faillure(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 180 "../speClearanceSNC.stt"
			printf("SPE VAULT CLEARED FAILURE CONDITION: ");
# line 181 "../speClearanceSNC.stt"
			SPE_update_failed(seqg_env, SPEPNK);
		}
		return;
	}
}

/****** Code for state "recover_from_paniq" in state set "SPE_clearance_status" ******/

/* Exit function for state "recover_from_paniq" in state set "SPE_clearance_status" */
static void seqg_exit_SPE_clearance_status_0_recover_from_paniq(SS_ID seqg_env)
{
# line 193 "../speClearanceSNC.stt"
	seqg_var->SPE_failed_rst = FALSE;
# line 194 "../speClearanceSNC.stt"
	seqg_var->SPE_not_cleared = FALSE;
}

/* Event function for state "recover_from_paniq" in state set "SPE_clearance_status" */
static seqBool seqg_event_SPE_clearance_status_0_recover_from_paniq(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 188 "../speClearanceSNC.stt"
	if (!seqg_var->SPE_PNK)
	{
		*seqg_pnst = 11;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "recover_from_paniq" in state set "SPE_clearance_status" */
static void seqg_action_SPE_clearance_status_0_recover_from_paniq(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "clearance_faillures" in state set "SPE_clearance_status" ******/

/* Entry function for state "clearance_faillures" in state set "SPE_clearance_status" */
static void seqg_entry_SPE_clearance_status_0_clearance_faillures(SS_ID seqg_env)
{
# line 203 "../speClearanceSNC.stt"
	printf("SPE CLEARANCE FAILURE CONDITION: ");
# line 204 "../speClearanceSNC.stt"
	seqg_var->SPE_failed_rst = FALSE;
# line 205 "../speClearanceSNC.stt"
	seqg_var->SPE_not_cleared = FALSE;
# line 206 "../speClearanceSNC.stt"
	seqg_var->SPE_OLD_FAIL_COND = seqg_var->SPE_FAIL_COND;
# line 207 "../speClearanceSNC.stt"
	SPE_update_failed(seqg_env, seqg_var->SPE_FAIL_COND == FAIL ? STOK : seqg_var->SPE_FAIL_COND);
}

/* Event function for state "clearance_faillures" in state set "SPE_clearance_status" */
static seqBool seqg_event_SPE_clearance_status_0_clearance_faillures(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 11;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "clearance_faillures" in state set "SPE_clearance_status" */
static void seqg_action_SPE_clearance_status_0_clearance_faillures(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "recover_from_faillure" in state set "SPE_clearance_status" ******/

/* Event function for state "recover_from_faillure" in state set "SPE_clearance_status" */
static seqBool seqg_event_SPE_clearance_status_0_recover_from_faillure(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 216 "../speClearanceSNC.stt"
	if (seqg_var->SPE_FAIL_COND == STOK)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 220 "../speClearanceSNC.stt"
	if (seqg_var->SPE_FAIL_COND != seqg_var->SPE_OLD_FAIL_COND)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "recover_from_faillure" in state set "SPE_clearance_status" */
static void seqg_action_SPE_clearance_status_0_recover_from_faillure(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 217 "../speClearanceSNC.stt"
			printf("%sSPE RECOVERING FROM CLEARANCE  FAILLURE : ENTERING W24 STATE%s\n", OK, DEF);
		}
		return;
	case 1:
		{
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{SYS}:RST-SPE.PROC", offsetof(struct seqg_vars, SPE_RST_OUTS), "SPE_RST_OUTS", P_SHORT, 1, 1, 0, 0, 0, 0},
	{"{SYS}:SPE-CLR-STATS", offsetof(struct seqg_vars, SPE_CLR_STATS), "SPE_CLR_STATS", P_STRING, 1, 2, 0, 0, 0, 0},
	{"{SYS}:SPE-INTLCK-STATS", offsetof(struct seqg_vars, SPE_INTLCK_STATS), "SPE_INTLCK_STATS", P_STRING, 1, 3, 0, 0, 0, 0},
	{"{SYS}:SPE-VC", offsetof(struct seqg_vars, SPE_VC), "SPE_VC", P_SHORT, 1, 4, 0, 1, 0, 0},
	{"{SYS}:SPE-W24-STS", offsetof(struct seqg_vars, SPE_W24_STS), "SPE_W24_STS", P_SHORT, 1, 5, 0, 1, 0, 0},
	{"{SYS}:SPE-W25-STS", offsetof(struct seqg_vars, SPE_W25_STS), "SPE_W25_STS", P_SHORT, 1, 6, 0, 1, 0, 0},
	{"{SYS}:SPE-FAIL-COND", offsetof(struct seqg_vars, SPE_FAIL_COND), "SPE_FAIL_COND", P_SHORT, 1, 7, 0, 1, 0, 0},
	{"{SYS}:SPE-PNK", offsetof(struct seqg_vars, SPE_PNK), "SPE_PNK", P_SHORT, 1, 8, 0, 1, 0, 0},
};

/* Event masks for state set "SPE_clearance_status" */
static const seqMask seqg_mask_SPE_clearance_status_0_init[] = {
	0x00000000,
};
static const seqMask seqg_mask_SPE_clearance_status_0_watchman_24_pressed[] = {
	0x000000a0,
};
static const seqMask seqg_mask_SPE_clearance_status_0_clearance_pending[] = {
	0x00000020,
};
static const seqMask seqg_mask_SPE_clearance_status_0_watchman_24_released[] = {
	0x000000a0,
};
static const seqMask seqg_mask_SPE_clearance_status_0_A9_switch_I_closed[] = {
	0x000000c0,
};
static const seqMask seqg_mask_SPE_clearance_status_0_A9_switch_II_closed[] = {
	0x000000c0,
};
static const seqMask seqg_mask_SPE_clearance_status_0_watchman_25_pressed[] = {
	0x000000c0,
};
static const seqMask seqg_mask_SPE_clearance_status_0_vault_cleared[] = {
	0x00000010,
};
static const seqMask seqg_mask_SPE_clearance_status_0_paniq_faillure[] = {
	0x00000010,
};
static const seqMask seqg_mask_SPE_clearance_status_0_recover_from_paniq[] = {
	0x00000100,
};
static const seqMask seqg_mask_SPE_clearance_status_0_clearance_faillures[] = {
	0x00000000,
};
static const seqMask seqg_mask_SPE_clearance_status_0_recover_from_faillure[] = {
	0x00000080,
};

/* State table for state set "SPE_clearance_status" */
static seqState seqg_states_SPE_clearance_status[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_SPE_clearance_status_0_init,
	/* event function */    seqg_event_SPE_clearance_status_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPE_clearance_status_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "watchman_24_pressed",
	/* action function */   seqg_action_SPE_clearance_status_0_watchman_24_pressed,
	/* event function */    seqg_event_SPE_clearance_status_0_watchman_24_pressed,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPE_clearance_status_0_watchman_24_pressed,
	/* state options */     (0)
	},
	{
	/* state name */        "clearance_pending",
	/* action function */   seqg_action_SPE_clearance_status_0_clearance_pending,
	/* event function */    seqg_event_SPE_clearance_status_0_clearance_pending,
	/* entry function */    seqg_entry_SPE_clearance_status_0_clearance_pending,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPE_clearance_status_0_clearance_pending,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
	{
	/* state name */        "watchman_24_released",
	/* action function */   seqg_action_SPE_clearance_status_0_watchman_24_released,
	/* event function */    seqg_event_SPE_clearance_status_0_watchman_24_released,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPE_clearance_status_0_watchman_24_released,
	/* state options */     (0)
	},
	{
	/* state name */        "A9_switch_I_closed",
	/* action function */   seqg_action_SPE_clearance_status_0_A9_switch_I_closed,
	/* event function */    seqg_event_SPE_clearance_status_0_A9_switch_I_closed,
	/* entry function */    seqg_entry_SPE_clearance_status_0_A9_switch_I_closed,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPE_clearance_status_0_A9_switch_I_closed,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "A9_switch_II_closed",
	/* action function */   seqg_action_SPE_clearance_status_0_A9_switch_II_closed,
	/* event function */    seqg_event_SPE_clearance_status_0_A9_switch_II_closed,
	/* entry function */    seqg_entry_SPE_clearance_status_0_A9_switch_II_closed,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPE_clearance_status_0_A9_switch_II_closed,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "watchman_25_pressed",
	/* action function */   seqg_action_SPE_clearance_status_0_watchman_25_pressed,
	/* event function */    seqg_event_SPE_clearance_status_0_watchman_25_pressed,
	/* entry function */    seqg_entry_SPE_clearance_status_0_watchman_25_pressed,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPE_clearance_status_0_watchman_25_pressed,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "vault_cleared",
	/* action function */   seqg_action_SPE_clearance_status_0_vault_cleared,
	/* event function */    seqg_event_SPE_clearance_status_0_vault_cleared,
	/* entry function */    seqg_entry_SPE_clearance_status_0_vault_cleared,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPE_clearance_status_0_vault_cleared,
	/* state options */     (0 | OPT_DOENTRYFROMSELF)
	},
	{
	/* state name */        "paniq_faillure",
	/* action function */   seqg_action_SPE_clearance_status_0_paniq_faillure,
	/* event function */    seqg_event_SPE_clearance_status_0_paniq_faillure,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPE_clearance_status_0_paniq_faillure,
	/* state options */     (0)
	},
	{
	/* state name */        "recover_from_paniq",
	/* action function */   seqg_action_SPE_clearance_status_0_recover_from_paniq,
	/* event function */    seqg_event_SPE_clearance_status_0_recover_from_paniq,
	/* entry function */    0,
	/* exit function */     seqg_exit_SPE_clearance_status_0_recover_from_paniq,
	/* event mask array */  seqg_mask_SPE_clearance_status_0_recover_from_paniq,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
	{
	/* state name */        "clearance_faillures",
	/* action function */   seqg_action_SPE_clearance_status_0_clearance_faillures,
	/* event function */    seqg_event_SPE_clearance_status_0_clearance_faillures,
	/* entry function */    seqg_entry_SPE_clearance_status_0_clearance_faillures,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPE_clearance_status_0_clearance_faillures,
	/* state options */     (0 | OPT_DOENTRYFROMSELF | OPT_DOEXITTOSELF)
	},
	{
	/* state name */        "recover_from_faillure",
	/* action function */   seqg_action_SPE_clearance_status_0_recover_from_faillure,
	/* event function */    seqg_event_SPE_clearance_status_0_recover_from_faillure,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_SPE_clearance_status_0_recover_from_faillure,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "SPE_clearance_status",
	/* states */            seqg_states_SPE_clearance_status,
	/* number of states */  12
	},
};

/* Program table (global) */
seqProgram speClearanceSNC = {
	/* magic number */      2002001,
	/* program name */      "speClearanceSNC",
	/* channels */          seqg_chans,
	/* num. channels */     8,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 226 "../speClearanceSNC.stt"
static void initVault(SS_ID seqg_env)
{
# line 227 "../speClearanceSNC.stt"
	seqg_var->SPE_OLD_FAIL_COND = seqg_var->SPE_FAIL_COND;
# line 228 "../speClearanceSNC.stt"
	seqg_var->SPE_RST_OUTS = TRUE;
# line 229 "../speClearanceSNC.stt"
	not_cleared(seqg_var->SPE_CLR_STATS);
# line 230 "../speClearanceSNC.stt"
	report_error(seqg_var->SPE_INTLCK_STATS, 0);
# line 231 "../speClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 0/*SPE_RST_OUTS*/, SYNC, DEFAULT_TIMEOUT);
# line 232 "../speClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SPE_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 233 "../speClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*SPE_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 236 "../speClearanceSNC.stt"
static void resetVault(SS_ID seqg_env)
{
# line 237 "../speClearanceSNC.stt"
	not_cleared(seqg_var->SPE_CLR_STATS);
# line 238 "../speClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SPE_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 241 "../speClearanceSNC.stt"
static void SPE_update_failed(SS_ID seqg_env, short report)
{
# line 243 "../speClearanceSNC.stt"
	clear_failed(seqg_var->SPE_CLR_STATS);
# line 244 "../speClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SPE_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 245 "../speClearanceSNC.stt"
	report_error(seqg_var->SPE_INTLCK_STATS, report);
# line 246 "../speClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*SPE_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 247 "../speClearanceSNC.stt"
	printf("%s%s%s\n", ERROR, seqg_var->SPE_INTLCK_STATS, DEF);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 250 "../speClearanceSNC.stt"
static void SPE_update_report(SS_ID seqg_env, short intlck)
{
# line 251 "../speClearanceSNC.stt"
	report_error(seqg_var->SPE_INTLCK_STATS, intlck);
# line 252 "../speClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*SPE_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 255 "../speClearanceSNC.stt"
static void SPE_status(SS_ID seqg_env)
{
# line 257 "../speClearanceSNC.stt"
	cleared(seqg_var->SPE_CLR_STATS);
# line 258 "../speClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SPE_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
# line 259 "../speClearanceSNC.stt"
	report_error(seqg_var->SPE_INTLCK_STATS, 0);
# line 260 "../speClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 2/*SPE_INTLCK_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var

#define seqg_var (*(struct seqg_vars *const *)seqg_env)
# line 263 "../speClearanceSNC.stt"
static void SPE_clear_underway(SS_ID seqg_env)
{
# line 265 "../speClearanceSNC.stt"
	clear_underway(seqg_var->SPE_CLR_STATS);
# line 266 "../speClearanceSNC.stt"
	seq_pvPutTmo(seqg_env, 1/*SPE_CLR_STATS*/, SYNC, DEFAULT_TIMEOUT);
}
#undef seqg_var
# line 270 "../speClearanceSNC.stt"


inline void cleared(string vault_status) {   
    strcpy(vault_status, mes_array[1]); // Area cleared  
}
////////////////////////////////////////////////
inline void not_cleared(string vault_status) {  
   strcpy(vault_status, mes_array[2]); // Area not cleared    
}
///////////////////////////////////////////////
inline void clear_underway(string vault_status) { 
   strcpy(vault_status, mes_array[3]);  // Area clearance underway    
}
//////////////////////////////////////////////
inline void clear_failed(string vault_status) { 
   strcpy(vault_status, mes_array[5]); // Area clearance fail   
}
////////////////////////////////////////////////
inline void report_error(string vault_interlock, short intlock)
{
   strcpy(vault_interlock, mes_array[intlock]);
}
	


/* Register sequencer commands and program */
#include "epicsExport.h"
static void speClearanceSNCRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&speClearanceSNC);
}
epicsExportRegistrar(speClearanceSNCRegistrar);
